### ISSUE TITLE
Completion error

### ISSUE THREAD

**Issue by violetkitty87** [Thaumic-Tinkerer/ThaumicTinkerer#1002]
i am trying to complete the beginnings of thaumic tinkerer and it wont stay completed. its not giving errors in the console or logs. it doesnt cause a crash but it makes the mod unusable. The version is thaumictinkerer-1.12.2-5.0-353c71c on my modpack called Frisky Business Reloaded on the twitch launcher. I think it may be a coding error with the mod but im unsure.

**Comment by AbyssalRemark** [comment]
I am also having this issue. It seems that It has been mentioned in opened and closed Issues without anyone talking about a solution.

**Comment by ace10102** [comment]
youre not using the bleeding edge version found on discord

**Comment by violetkitty87** [comment]
im using what curse provides you need to add it to that version

**Comment by ace10102** [comment]
![image](https://user-images.githubusercontent.com/33331567/75496467-3b66a700-598f-11ea-9eee-bfc914a0875a.png)

**Comment by violetkitty87** [comment]
heres the issue curse doesnt approve mods that arent in their list of approved mods and cause my pack is officially on the twitch launcher it doesnt work that way

**Comment by violetkitty87** [comment]
the other problem is the people who dont know of the discord dont know to get it there

**Comment by ace10102** [comment]
the bleeding edge versions arent uploaded to curse specifically to stop people from using it in their modpacks

**Comment by violetkitty87** [comment]
oh ok then why isnt an actual version out then

**Comment by ace10102** [comment]
because the mod is in extreme alpha

**Comment by nekosune** [comment]
I put it on curse marked as alpha, thinking people would listen to the thing saying not to add alpha mods to packs. to let people try it, mostly in creative mode, and so on. Turns out people add it to packs anyway ignoring that, and I get flooded with issues like this for a mod still being completed.
