### ISSUE TITLE
No research exists for dissimulation block 

### ISSUE THREAD

**Issue by ace10102** [Thaumic-Tinkerer/ThaumicTinkerer#1003]
Even giving all research to the player doesnt unlock the research required to craft the dissimulation block-indicating that the research for the block just doesnt exist
![HneEf9](https://user-images.githubusercontent.com/33331567/75080398-e2ec6100-54d9-11ea-9cc2-7a4cdcdc1422.png)
![CYIu8H](https://user-images.githubusercontent.com/33331567/75080447-03b4b680-54da-11ea-8722-d010a05f07c6.png)

**Comment by nekosune** [comment]
This has been fixed
