### ISSUE TITLE
[1.12.2] Transvector Dislocator won't swap blocks back after redstone signal is lost.

### ISSUE THREAD

**Issue by Artleksandr** [Thaumic-Tinkerer/ThaumicTinkerer#1008]
Sorry for eye-bleeding gif
![gif](https://user-images.githubusercontent.com/60533582/80440956-2be2ea80-894d-11ea-8ffb-348fbd1adf2f.gif)

**Comment by nekosune** [comment]
The Dislocator has always been toggle, not duration of symbol

**Comment by nekosune** [comment]
It seems I was mistaken in my lore, this will be corrected
