### ISSUE TITLE
Crash client

### ISSUE THREAD

**Issue by SeagalKru** [Thaumic-Tinkerer/ThaumicTinkerer#1016]
Hey.
Updated the mods in its assembly, as well as the forge version. For some reason, a client crashed. I see your mod in the log file and 1 more mod, the developer of which I will also unsubscribe. I hope you find a solution to the problem. Good luck.
[crash-2020-05-15_00.43.57-server.txt](https://github.com/Thaumic-Tinkerer/ThaumicTinkerer/files/4631048/crash-2020-05-15_00.43.57-server.txt)

Following and the server crashed ...
[crash-2020-05-15_01.09.39-server.txt](https://github.com/Thaumic-Tinkerer/ThaumicTinkerer/files/4631159/crash-2020-05-15_01.09.39-server.txt)

**Comment by SeagalKru** [comment]
Following and the server crashed ...
[crash-2020-05-15_01.09.39-server.txt](https://github.com/Thaumic-Tinkerer/ThaumicTinkerer/files/4631156/crash-2020-05-15_01.09.39-server.txt)

**Comment by nekosune** [comment]
This will be fixed immidiately

**Comment by nekosune** [comment]
Fixed with commit 620a0c53435a83bbf4874ba04139430e82af3409 will upload a new build to curseforge within today
