### ISSUE TITLE
Osmotic Enchanter takes crystals but does not enchant 

### ISSUE THREAD

**Issue by andythe15th** [Thaumic-Tinkerer/ThaumicTinkerer#1020]
After first building it out of botania smokey quartz the Osmotic Enchanter took my crystals but did not enchant my item. After finding out that I made it out of the wrong smokey quartz I rebuilt it using thaumic tinkerer's smokey quartz blocks. However, this did not solve the issue, I even tried breaking the structure and rebuilding it with salis mundus but no luck.

Here is a link to a video of me trying to enchant a pickaxe:
https://www.youtube.com/watch?v=mY_F1I3h7sk&feature=youtu.be

**Comment by nekosune** [comment]
Do you have the logs for this?

**Comment by andythe15th** [comment]
I've just tried it again and it seems to be working just fine now. I do not know what caused it to work as I have restarted both the system and the game multiple times. Thank you for the quick reply.
