### ISSUE TITLE
Adding enchants to osmotic enchanter

### ISSUE THREAD

**Issue by FakeMan2332** [Thaumic-Tinkerer/ThaumicTinkerer#1023]
How I can add enchant to osmotic enchanter, using mod tweaker?

**Comment by nekosune** [comment]
Hi there! The enchanter should detect every available enchant for an item already.

**Comment by FakeMan2332** [comment]
How can he see the enchantment without setup vis and icons?

**Comment by FakeMan2332** [comment]
Minecraft version is 1.7.10 😳

**Comment by nekosune** [comment]
Ah, sorry I dont really support the older versions as much. The new version, it auto adds enchantments automatically based on enchantment category / what item it goes on, and it uses a ? icon with the option to add icons via resource pack.
The older one, it was done via a specific class, it is not something I believe mod-tweaker can alter

**Comment by FakeMan2332** [comment]
Okay, bye. Thanks for answer
