### ISSUE TITLE
1.12 continuation

### ISSUE THREAD

**Issue by coldfeudal** [Thaumic-Tinkerer/ThaumicTinkerer#1035]
Is there any way the 1.12 Thaumic Tinkerer version will be finished or is it permanently stopped? E.g. kami is not implemented yet

**Comment by Artleksandr** [comment]
Work will be continued after mffs is finished I guess.

**Comment by nekosune** [comment]
I am trying to balance work on it, but I want to get MFFS into a state where the projector works, then go back to adding features to both

**Comment by tkolarik** [comment]
Any link to the mffs repo? google is only giving me results from calclavia

**Comment by nekosune** [comment]
https://github.com/nekosune/modularforcefieldsystem/

**Comment by theaimeeknight** [comment]
Closing: Question answered above by dev.
