### ISSUE TITLE
1.7.10 Infused Seed drops for other TC addons

### ISSUE THREAD

**Issue by RUMisthepower** [Thaumic-Tinkerer/ThaumicTinkerer#1046]
I'm playing GTNH 2.1.1.0 mod pack
Infused crops that have composite aspects from Forbidden Magic or GregTech5 or MagicBees don't drop any items but seeds.
I don't know how to make such crops drop at least crystallized essence of it's type. 
// In particular, I need Nebrisum aspect from GregTech5 TC addon.
AspectCropLootManager.class doesn't have these AspectLoot lines. I don't know how to implement "new" aspects into the code with corresponding AspectLoot.
Please, help. 
Thank you.

**Comment by aimeesunflower** [comment]
Hi there! 

I'm closing this out, as it regards an old version of Minecraft, that we no longer support. The ThaumicTinkerer team are currently focused on 1.12.2 and further.

Please know that we're only able to help with ThaumicTinkerer issues here, for help with other mods, or their modpacks, you'll need to contact their creators/developers. This being said, you may be able to find help from the community on the ThaumicTinkerer [Discord Server](https://discord.gg/wdK3GfN37m).

Thanks!
