### ISSUE TITLE
[1.12.2] hyperenergetic nitor glitch

### ISSUE THREAD

**Issue by AtomicMisery** [Thaumic-Tinkerer/ThaumicTinkerer#1057]
found that while holding the hyperenergetic nitor whenever you walk by a fence at head level its connects the fence to nothing and leaves the connecter attached to nothing, i am playing in a modpack so it could be other mods interfering. My proposed reason for the occurrence of this glitch is that the hyperenergetic nitor makes the top half of your body register as a block to fence posts, or something along those lines. thanks for reading.

edit: i did a small amount of testing and found that the floating fence connection disappears after a short amount of time, around a minute twenty seconds is my estimate. this could be caused from problems of being on a server, which i neglected to mention i was playing on.

**Comment by aimeesunflower** [comment]
Confirmed reproduce. Working on fix now.
