### ISSUE TITLE
Discord Issue

### ISSUE THREAD

**Issue by Joes101** [Thaumic-Tinkerer/ThaumicTinkerer#1074]
Hi, this isn't really a mod issue, so much as it is one relating to the discord server. I love this project and wanted to keep up to date on it, so I tried to join the discord via the invite link on the Readme. However, everytime I join it, it brings me to an empty "#rules" channel, and no channels appear under the server (including said "#rules"). This is the only Discord server I've had this issue with, hence why I'm bringing it up. I'm hoping there's something you can do, because I love your work and this mod, and would like to follow progress on the discord server.

**Comment by KatrinaAS** [comment]
Hi there! Hopefuly this link should work. if not hang around in #rules before leaving and I will check your perms
