### ISSUE TITLE
Recent releases?

### ISSUE THREAD

**Issue by xJon** [Thaumic-Tinkerer/ThaumicTinkerer#1075]
Any reason why the last 2 years of commits (albeit not many) didn't see a new release? Thanks :)

**Comment by KatrinaAS** [comment]
It is an old version of Minecraft I can't even run on my development machine anymore.

**Comment by KatrinaAS** [comment]
https://www.minecraftforum.net/forums/support/java-edition-support/3129515-modded-minecraft-will-not-launch-on-m1-mac-mini

**Comment by Dream-Master** [comment]
not sure if you want to try gtnh forked versions. In my pack it works well need to be tested outside GTNH
<https://github.com/GTNewHorizons/ThaumicTinkerer>

**Comment by xJon** [comment]
@Dream-Master Your forks are great but not for 1.12.2 :)

**Comment by Dream-Master** [comment]
sure its for 1.7.10 not for 1.12

**Comment by xJon** [comment]
@Dream-Master Yeah I was referring to a recent 1.12.2 build (for my 1.12.2 modpacks. I'm actually already using GTNH builds for my 1.7.10 modpack).

**Comment by xJon** [comment]
@KatrinaAS Any update on this for 1.12.2? Thank you!

**Comment by Newtboy** [comment]
@KatrinaAS I also am on an M1 mac mini, and I've only ever seen that problem when I fullscreen or double tap the top bar to fit screen while it's still loading the game, so maybe try waiting until it shows the main menu? Not sure if this will work, but that's what I know. Also, sometimes I've had to switch between java JDK version 8 and 16+ to get some mods to run.
Hope this helps!

**Comment by xJon** [comment]
Closing thanks to the release of https://www.curseforge.com/minecraft/mc-mods/thaumic-tinkerer-unofficial.
