### ISSUE TITLE
[1.6.4]Robes of the Stratosphere breaks Botania

### ISSUE THREAD

**Issue by MajorCooke** [Thaumic-Tinkerer/ThaumicTinkerer#423]
This is a rather old issue, and I dont know if this was fixed anytime recently before updating to 1.7.10.

https://github.com/TPPI-Dev/TestPackPleaseIgnore/issues/410

In short, the KAMI robes interfere with different mods like Botania and are quite disruptive, such as with mana spreaders and the energy bazooka from Blood Magic.

(I can understand if the 1.6.4 version is no longer supported, but I wanted to check and see for sure...)

**Comment by Adaptivity** [comment]
@nekosune should be fixed by https://github.com/Thaumic-Tinkerer/ThaumicTinkerer/commit/9572fcdd010fac3caf9d081b701a96e803824789 ?

**Comment by nekosune** [comment]
Should be right, :)
