### ISSUE TITLE
worldshaper's looking glass looking odd in th action bar

### ISSUE THREAD

**Issue by wiiv** [Thaumic-Tinkerer/ThaumicTinkerer#524]
I have noticed a bug with the item rendering in the action bar, I would also like to ask why is it rotated in there:

I'll leave an image so you can see hat I mean:

http://imgur.com/NNyUNM8

**Comment by wiiv** [comment]
Can someone take a look at this please?

**Comment by nekosune** [comment]
@TeliUmbrarum  May I know which versions.

**Comment by wiiv** [comment]
The latest version from jenkins. ;)

**Comment by nekosune** [comment]
@wiiv I am afraid the graphical bug is low priority,  I am trying to sort out the crash bugs first like the one @TeliUmbrarum foumd

**Comment by wiiv** [comment]
Forge{10.13.0.1208}
ThaumicTinkerer{2.5-1.7.10-158}
Thaumcraft{4.2.0.1} 
Are the version in the log he posted. ;)

**Comment by nekosune** [comment]
Yeah looks like crash is either fixed by then or hard to activate then



—

**Comment by wiiv** [comment]
I can confirm that the visual glitch I reported doesn't happen anymore.
