### ISSUE TITLE
Infused Crops crash when attempting to gather

### ISSUE THREAD

**Issue by mbaramidze** [Thaumic-Tinkerer/ThaumicTinkerer#544]
I was messing around with infused crops and attempting to gather a mature Volatus crop crashes the game: http://pastebin.com/Z75vNSmJ

I'm running build 160.

**Comment by Dreghert** [comment]
I am having this same issue. I even tried updating, but it still happens with build 470.

**Comment by katzenpapst** [comment]
Same issure here as well, volatus, too. In addition it happened with ForbiddenMagic's ira. For me, only the client crashes, the server keeps running. Neither the seed nor any drops remain then I reconnect, but the aspect remains in the soil
