### ISSUE TITLE
Essentia funnel

### ISSUE THREAD

**Issue by aahaselgrove** [Thaumic-Tinkerer/ThaumicTinkerer#55]
Breaking the hopper below an essentia funnel causes the warded jar in the funnel to be lost. 

~~Also, attempting to break the funnel by clicking on the jar causes the item behind the jar to be broken.~~ (not a bug, mind the bounding box)

**Comment by WebDragon** [comment]
thaumictinkerer-1.12.2-5.0-353c71c.jar 

seeing this same issue in FTB Ultimate Reloaded 1.7.1 release - break the hopper and the now-empty warded jar on top disappears. If there's another maintainer post report tracking this, I will gladly redirect
