### ISSUE TITLE
Stall During Infusion of Awaking Ichorium Pickaxe

### ISSUE THREAD

**Issue by Shamadruu** [Thaumic-Tinkerer/ThaumicTinkerer#558]
When I try to infuse an awakened ichorium pickaxe, the infusion starts normally but stalls after absorbing all of the required essentia and several items. Afterwards, it just stalls as though an item were missing, and consumes my essentia/disintegrates items. I've checked numerous times, and I've all of the items in the right positions when I do this.

**Comment by Brycey92** [comment]
I cannot reproduce this issue.
