### ISSUE TITLE
Duping Glitch

### ISSUE THREAD

**Issue by ghost** [Thaumic-Tinkerer/ThaumicTinkerer#564]
The duping glitch consists of a Bottomless Pouch and a good friend or a puddle of water.
1. Open the bottomless pouch and place items inside.
2. Close the bottomless pouch to update the inventory.
3. Open the inventory and take out the items and leave the inventory menu open.
4. Drown in water or get someone to kill you while the inventory menu is open.
5. You have successfully duped whatever was in the bag.

**Comment by KasperFranz** [comment]
Is this getting fixed?

**Comment by Adaptivity** [comment]
@nekosune confirmed in the latest version.
