### ISSUE TITLE
[Suggestion] Kami Armor Customization

### ISSUE THREAD

**Issue by ZeekDaGeek** [Thaumic-Tinkerer/ThaumicTinkerer#578]
SUGGESTION / ENHANCEMENT

Kami armor is very powerful, however, not all the bonuses are desirable at all times. It would be nice to be able to customize every special ability.

Personally I'm not too much a fan of the ability to walk up one block forced by the boots, or the forced grass block conversions at all times as it can make the edges of dirt walls look weird as grass is oddly spread if you fly by them.

If you were able to hold a piece of armor then shift right click to edit the abilities per armor that you wish to enable/disable it would be much more favourable that way they don't have to be enabled at all time.

This style of system also allows for the option of adding more experimental abilities if you wished without  harming a players experience.

EDIT: This could also allow tweaks to features such as flight speed for the chest piece and variable jump height.

**Comment by AlfieSR** [comment]
Could also go the Advanced Thaumaturgy route of infusing them with the extra abilities. By themselves, the awakened kami armour would be little more than it's sheer invulnerability but would also be required for the process of upgrading them where basic ichorcloth robes would be unable.
