### ISSUE TITLE
infused crops drops broken

### ISSUE THREAD

**Issue by shadoxxhd** [Thaumic-Tinkerer/ThaumicTinkerer#591]
-beast seeds drop unusable spawn eggs (white&nothing happens on right-click)
-flesh seeds drop zombie brain with wrong id (item name "zombie brain (defunct)")

ill continue searching for broken drops and post back when i find any

**Comment by katzenpapst** [comment]
Have not experienced the zombie brain problem, but can confirm the spawn egg one. Most eggs produced by a bestia plant contain things like the item frame entity, thrown snowballs, flying wither skulls, ignited TNT etc, and are unusable (Rightclicking doesn't work, dispensers just destroy the eggs). I think the only valid eggs I ever got were two GalactiCraft mobs
