### ISSUE TITLE
Robes of the Stratosphere blocking Botania's mana spreaders.

### ISSUE THREAD

**Issue by QF5690** [Thaumic-Tinkerer/ThaumicTinkerer#604]
Everytime I wear Robes to the Stratosphere all botania's mana spreaders stop working. Earlier, Blood magic's Bound armor with whirlwind caused same issue, but it was fixed. It is related to projectile protection that these armours offers.
I'm using 161th build, also saw changelog for 162, there is nothing about it.

**Comment by ken-noland** [comment]
Any news on this?

**Comment by nekosune** [comment]
This has been fixed

**Comment by nekosune** [comment]
@QF5690  Talking of Way of Time, looks like we both originally fixed it wrong, as damage lens spreaders would NOT be deflected, fixed and both mods now only deflect the harmful ones.
