### ISSUE TITLE
Crash when finishing enchantment with osmotic enchanter

### ISSUE THREAD

**Issue by drifter397** [Thaumic-Tinkerer/ThaumicTinkerer#605]
I enchanted my equal trade focus recently and as soon as it finished, my game crashed.

Crash Log: http://pastebin.com/SuqJUeg3

Mod List: http://pastebin.com/f0n8HSJ6

**Comment by Brycey92** [comment]
This issue is fixed in the latest dev buid, and should be closed.

**Comment by nekosune** [comment]
@Brycey92 Look at the crash log, different crash to the vis one
