### ISSUE TITLE
Kicked when putting Repair on anything with osmotic enchanter

### ISSUE THREAD

**Issue by ghost** [Thaumic-Tinkerer/ThaumicTinkerer#606]
Well after the last update of Thaumcraft and Thaumic tinkerer I am getting kicked from a server I've been playing whenever I try to put the Repair enchant on any tool or armor. Even more, tools and armor that had Repair on them before the update are no longer repairing themselves even though the enchant shows to be there and my wands are all full. A friend of mine is playing in the same server and he said that he even didn't see the enchant on the tools, but they are still glowing.

I tried enchanting in single and everything is working fine, none of the problems above appeared, so it seems that the problem is server-side. Nothing shows up in the console of the server.

I don't get crash reports either, but I see this when I get kicked: http://i.imgur.com/i1lL6A0.png?1
In fact, I got a crash report, but only once: http://pastebin.com/3g9zNKRB
Mod List: http://i.imgur.com/8s5iF0P.png?1
Server FML log: https://secure.r3nt3r.com/b/?c219c70f3aeaa26d#hccPwbh6HCJGGGluBHoHFOjcsPCQ3VNyF70g1PYHG80=

Server is updated to the latest versions, my mods are also updated. So what can be causing this problem?

**Comment by arkD** [comment]
I can confirm this
thaumcraft 4.2.3.4
Thaumic Tinkerer 2.5-1.7.10-162
crash report: http://pastebin.com/5UwV3CMU
