### ISSUE TITLE
Enchanter Crashing

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [Thaumic-Tinkerer/ThaumicTinkerer#609]
Trying to put a crafting wand into the enchanter results in a crash:

https://paste.ee/p/1PQPq#AgeWx0EkKFDzsNAxpGJtzKNtGJwNIcJ4

**Comment by Unrepentant-Atheist** [comment]
https://paste.ee/p/2RJql

**Comment by Keridos** [comment]
This should be fixed in the next TC Release as far as I know.

**Comment by Devilin-Pixy** [comment]
Had the same issue, but reporting with full logs has already been done, so I don't think I will need to do that again.

Just want to mention a reasonably simple way of fixing the issue without removing the full enchanting table with item to enchant and wand placed. For this you can use NBTExplorer. Check the crash log and look for the 'Block location'. Then check the region file that contains it and open that in NBTExplorer. Then do a search for 'value > enchanter' within that region file and check the coordinates in the NBT data to make sure you have the right one. Remove just the entries for the wand placed in the enchanting table and the issue should be fixed. If you wish, you could even copy over those entries to the player.dat file for the player who placed the wand with again NBTExplorer. Make sure you place those entries into the inventory and use a slot that is not not used.

Screenshot from NBTExplorer showing the wand entries in the region file: http://imgur.com/sD2py6u
Screenshot from NBTExplorer for the player.dat file: http://imgur.com/desuPip

This way the enchanter, item to enchant as well as the wand with all the aspects do not get lost at all.

Hope this issue will be fixed soon, keep up the good work ;-)

**Comment by nekosune** [comment]
Issue allready been fixed
