### ISSUE TITLE
why doesn imbuedFire

### ISSUE THREAD

**Issue by Flukethoughts** [Thaumic-Tinkerer/ThaumicTinkerer#619]
Follow the game rule? and when i disable the config it's still in my world.

**Comment by nekosune** [comment]
I will try and have it obey the game rule in next update,  and I am
considering changing it to disappear on disabled but want to do a poll
first,  make sure people aren't relying on current functionality I know of
one adventure map in progress that use this not disappearing bit not
spreading when disabled to make a pretty looking fire in decorative

**Comment by Divineaspect** [comment]
It needs either this or a decay counter.

**Comment by Flukethoughts** [comment]
well i know a few servers that where grieved with it taking over the whole server.

**Comment by nekosune** [comment]
Looking into the code, it SHOULD obey the game rule allready, will investigate why not and test

**Comment by nekosune** [comment]
After testing, it has been determined this does obey the fire rule,
