### ISSUE TITLE
Osmotic Enchanter Client/Server Crash

### ISSUE THREAD

**Issue by groveham** [Thaumic-Tinkerer/ThaumicTinkerer#622]
A player has crashed my server using an item out of this mod. I am running 2.0.7 of the Infitech2 Modpack. I'm reporting it on their behalf to let you know of the issue. This was replicated in both single and multiplayer. I'm unable to start the server since this issue was reported. 

'I believe I crashed the server (and several clients) using the Thaumic Tinkerer osmotic enchanter. I posted in the bugs forum. My apologies. I have used the enchanter several times before with no issues.'
=======
Mod Version:
ThaumicTinkerer-2.5-1.7.10-436.jar

Server Crash Log:
http://pastebin.com/uFH7ch5S

Server console on Crash (in-case it's different from what's in the log - you never know these days):
http://pastebin.com/nFwKcT8D

Client Crash Log:
http://pastebin.com/9e4J4ZYW
(That's the crash log of the person who reported it, not me/my PC).

If you need any more information please give me a shout on here or at http://infitech.enjin.com

**Comment by nekosune** [comment]
Please update to latest

**Comment by yolp900** [comment]
Where is the newest TT? I can't seem to find it....... (only finding 2.5-1.7.10-162 on Curse and CurseForge)

**Comment by Yulife** [comment]
http://jenkins.nekokittygames.com:8080/job/Thaumic%20Tinkerer/439/

**Comment by yolp900** [comment]
THANK YOU!!
I think that'll fix my server (Having the same issue as this one, but on an older version.)

**Comment by Yulife** [comment]
![200](https://cloud.githubusercontent.com/assets/8559428/5632629/81553b9c-95d0-11e4-91f2-0c548ab28381.gif)
