### ISSUE TITLE
Osmotic Enchanter 347 miss counting magic use error

### ISSUE THREAD

**Issue by seannyyx** [Thaumic-Tinkerer/ThaumicTinkerer#623]
The 437 patch that fixes the server crash with osmotic enchanter has caused a new error that means magic used from enchanter is calculated as 0,## of a number i.e. if something costs 50 aer it will only take 0.50 from the aer of the wand used. making for a VERY over OP enchanting. :)
![2015-01-03_20 19 46](https://cloud.githubusercontent.com/assets/10383684/5603615/ecf74e5a-9385-11e4-9482-eed3a04942f4.png)

**Comment by nekosune** [comment]
That will be fixed in update though I don't see why it happened but I
consider op enchantment better then crash for now
