### ISSUE TITLE
Crahs and world corruption during enchanting 

### ISSUE THREAD

**Issue by LiSirNo** [Thaumic-Tinkerer/ThaumicTinkerer#624]
Well as title says

version used: ThaumicTinkerer-2.5-1.7.10-162

crash log:

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 04.01.15 18:50
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at thaumcraft.common.items.wands.ItemWandCasting.consumeAllVis(ItemWandCasting.java:322)
	at thaumcraft.common.items.wands.ItemWandCasting.consumeAllVisCrafting(ItemWandCasting.java:305)
	at thaumic.tinkerer.common.block.tile.TileEnchanter.func_145845_h(TileEnchanter.java:159)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1995)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at thaumcraft.common.items.wands.ItemWandCasting.consumeAllVis(ItemWandCasting.java:322)
	at thaumcraft.common.items.wands.ItemWandCasting.consumeAllVisCrafting(ItemWandCasting.java:305)
	at thaumic.tinkerer.common.block.tile.TileEnchanter.func_145845_h(TileEnchanter.java:159)

-- Block entity being ticked --
Details:
	Name: ttinkerer:enchanter // thaumic.tinkerer.common.block.tile.TileEnchanter
	Block type: ID #753 (tile.enchanter // thaumic.tinkerer.common.block.BlockEnchanter)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-170,78,-445), Chunk: (at 6,4,3 in -11,-28; contains blocks -176,0,-448 to -161,255,-433), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Actual block type: ID #753 (tile.enchanter // thaumic.tinkerer.common.block.BlockEnchanter)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Gannv'/11526, l='MpServer', x=-168,49, y=79,62, z=-444,66]]
	Chunk stats: MultiplayerChunkCache: 272, 281
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-240,64,180), Chunk: (at 0,4,4 in -15,11; contains blocks -240,0,176 to -225,255,191), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 126100 game time, 16785 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 96 total; [EntityCreeper['Creeper'/14824, l='MpServer', x=-128,31, y=20,00, z=-463,42], EntityCreeper['Creeper'/14825, l='MpServer', x=-129,61, y=20,00, z=-462,93], EntityBat['Bat'/13613, l='MpServer', x=-210,22, y=25,56, z=-386,41], EntityBat['Bat'/13612, l='MpServer', x=-167,06, y=35,00, z=-390,56], EntityWolf['Wolf'/11948, l='MpServer', x=-91,50, y=63,00, z=-461,50], EntityWolf['Wolf'/11951, l='MpServer', x=-89,75, y=69,00, z=-462,31], EntityItem['item.tile.doublePlant.syringa'/11924, l='MpServer', x=-119,69, y=64,13, z=-399,09], EntityItem['item.item.witchery:seedsbelladonna'/11922, l='MpServer', x=-119,16, y=63,13, z=-396,16], EntityItem['item.item.seeds'/11923, l='MpServer', x=-120,72, y=63,13, z=-396,16], EntityItem['item.tile.doublePlant.syringa'/11921, l='MpServer', x=-120,75, y=63,13, z=-396,28], EntityItem['item.item.feather'/13179, l='MpServer', x=-144,31, y=65,13, z=-405,91], EntityItem['item.tile.stonebrick'/11911, l='MpServer', x=-124,19, y=24,13, z=-411,13], EntityItem['item.tile.gravel'/11910, l='MpServer', x=-126,81, y=23,13, z=-410,69], EntityItem['item.tile.stonebrick'/11909, l='MpServer', x=-126,19, y=24,13, z=-412,13], EntityItem['item.item.enderPearl'/11908, l='MpServer', x=-126,75, y=24,13, z=-409,84], BlueSlime['Blue Slime'/11906, l='MpServer', x=-117,22, y=63,00, z=-433,38], BlueSlime['Blue Slime'/11905, l='MpServer', x=-123,31, y=63,00, z=-391,56], BlueSlime['Blue Slime'/11904, l='MpServer', x=-113,47, y=148,00, z=-411,75], BlueSlime['Blue Slime'/11918, l='MpServer', x=-114,28, y=146,63, z=-415,78], BlueSlime['Blue Slime'/11917, l='MpServer', x=-118,31, y=62,00, z=-388,00], EntityItem['item.tile.doublePlant.syringa'/11916, l='MpServer', x=-120,63, y=64,13, z=-400,19], EntityItem['item.tile.stonebrick'/11915, l='MpServer', x=-127,06, y=24,13, z=-411,66], EntityItem['item.tile.stonebrick'/11914, l='MpServer', x=-126,88, y=23,73, z=-410,22], EntityItem['item.tile.stonebrick'/11913, l='MpServer', x=-126,88, y=23,13, z=-410,13], EntityItem['item.tile.gravel'/11912, l='MpServer', x=-125,13, y=24,13, z=-411,47], EntityItem['item.item.sulphur'/13072, l='MpServer', x=-187,28, y=70,13, z=-401,22], EntitySpider['Spider'/13087, l='MpServer', x=-122,00, y=21,00, z=-506,00], EntitySkeleton['Skeleton'/11837, l='MpServer', x=-160,09, y=77,00, z=-464,53], EntityChicken['Chicken'/11839, l='MpServer', x=-175,38, y=75,00, z=-475,56], EntitySpider['Spider'/11838, l='MpServer', x=-165,22, y=77,00, z=-467,03], EntityItem['item.item.dyePowder.black'/13736, l='MpServer', x=-215,31, y=58,13, z=-464,91], EntityWolf['Wolf'/11897, l='MpServer', x=-121,50, y=69,00, z=-523,50], EntitySquid['Squid'/11899, l='MpServer', x=-112,50, y=61,88, z=-474,69], EntitySpider['Spider'/13211, l='MpServer', x=-230,94, y=68,31, z=-508,28], EntityZombie['Zombie'/13205, l='MpServer', x=-202,50, y=69,00, z=-388,50], EntityChicken['Chicken'/11880, l='MpServer', x=-137,47, y=68,00, z=-406,84], EntityChicken['Chicken'/11883, l='MpServer', x=-139,50, y=63,00, z=-383,50], EntityChicken['Chicken'/11884, l='MpServer', x=-135,16, y=62,36, z=-380,75], EntityItem['item.tile.stonebrick'/11878, l='MpServer', x=-128,59, y=24,13, z=-412,84], EntityChicken['Chicken'/11879, l='MpServer', x=-142,50, y=65,00, z=-406,50], EntityZombie['Zombie'/11870, l='MpServer', x=-142,50, y=57,00, z=-440,50], EntityPig['Pig'/11858, l='MpServer', x=-155,50, y=64,00, z=-400,50], EntityChicken['Chicken'/11857, l='MpServer', x=-150,47, y=64,00, z=-404,53], EntityChicken['Chicken'/11856, l='MpServer', x=-151,41, y=63,00, z=-401,56], EntityPig['Pig'/11861, l='MpServer', x=-153,34, y=63,00, z=-397,88], EntityPig['Pig'/11860, l='MpServer', x=-154,53, y=63,00, z=-398,53], BlueSlime['Blue Slime'/13230, l='MpServer', x=-136,72, y=69,00, z=-390,34], EntityCow['Cow'/11850, l='MpServer', x=-149,22, y=71,00, z=-522,22], EntityCow['Cow'/11851, l='MpServer', x=-150,81, y=71,00, z=-523,53], EntityCow['Cow'/11848, l='MpServer', x=-150,75, y=70,00, z=-527,22], EntityChicken['Chicken'/11842, l='MpServer', x=-147,47, y=77,00, z=-443,63], EntitySkeleton['Skeleton'/11843, l='MpServer', x=-167,38, y=78,00, z=-458,13], EntityChicken['Chicken'/11840, l='MpServer', x=-175,53, y=76,00, z=-458,56], EntityChicken['Chicken'/11841, l='MpServer', x=-154,56, y=78,00, z=-460,20], EntityPig['Pig'/11844, l='MpServer', x=-165,31, y=69,00, z=-389,50], EntityZombie['Zombie'/13839, l='MpServer', x=-176,50, y=64,00, z=-385,50], EntityZombie['Zombie'/13838, l='MpServer', x=-155,59, y=74,00, z=-473,00], EntityZombie['Zombie'/13837, l='MpServer', x=-172,00, y=72,00, z=-483,44], EntityPig['Pig'/11651, l='MpServer', x=-228,13, y=93,00, z=-373,06], EntityPig['Pig'/11652, l='MpServer', x=-231,53, y=96,00, z=-375,56], EntityBat['Bat'/13347, l='MpServer', x=-156,23, y=17,16, z=-465,98], EntityChicken['Chicken'/11663, l='MpServer', x=-208,50, y=71,00, z=-523,50], EntityChicken['Chicken'/11662, l='MpServer', x=-209,50, y=70,00, z=-522,50], EntityCreeper['Creeper'/11666, l='MpServer', x=-222,03, y=53,00, z=-473,44], EntitySpider['Spider'/13372, l='MpServer', x=-139,50, y=63,00, z=-395,50], EntityZombie['Zombie'/11669, l='MpServer', x=-222,28, y=46,00, z=-451,25], EntityMinecartChest['entity.MinecartChest.name'/11673, l='MpServer', x=-219,50, y=24,50, z=-416,50], EntitySpider['Spider'/11675, l='MpServer', x=-218,50, y=20,00, z=-414,50], EntitySkeleton['Skeleton'/13841, l='MpServer', x=-93,50, y=63,00, z=-367,50], EntityPig['Pig'/11699, l='MpServer', x=-220,16, y=85,00, z=-372,88], EntityCreeper['Creeper'/12915, l='MpServer', x=-169,41, y=76,00, z=-467,94], EntityChicken['Chicken'/11704, l='MpServer', x=-205,50, y=71,00, z=-521,50], EntityChicken['Chicken'/11705, l='MpServer', x=-207,50, y=70,00, z=-521,50], EntityBlock['unknown'/12257, l='MpServer', x=-278,75, y=62,01, z=-391,75], EntityItem['item.item.bone'/12812, l='MpServer', x=-184,03, y=26,13, z=-418,44], EntityCovenWitch['Coven Witch'/11754, l='MpServer', x=-195,13, y=73,00, z=-407,50], EntityMinecartChest['entity.MinecartChest.name'/11753, l='MpServer', x=-181,50, y=18,50, z=-513,50], EntityTrail['unknown'/11531, l='MpServer', x=-168,49, y=79,62, z=-444,66], EntityClientPlayerMP['Gannv'/11526, l='MpServer', x=-168,49, y=79,62, z=-444,66], EntityBat['Bat'/14437, l='MpServer', x=-121,38, y=14,00, z=-512,31], EntityBat['Bat'/14436, l='MpServer', x=-120,94, y=14,00, z=-510,25], EntityBat['Bat'/14439, l='MpServer', x=-212,56, y=24,00, z=-515,25], EntityBat['Bat'/14438, l='MpServer', x=-212,38, y=24,00, z=-516,88], EntityBat['Bat'/13022, l='MpServer', x=-150,25, y=16,10, z=-389,25], EntityBat['Bat'/14435, l='MpServer', x=-195,25, y=21,00, z=-448,75], EntityBat['Bat'/13021, l='MpServer', x=-144,34, y=14,11, z=-385,66], EntityBat['Bat'/14434, l='MpServer', x=-209,41, y=20,19, z=-439,66], EntityBat['Bat'/14442, l='MpServer', x=-185,41, y=22,41, z=-475,69], EntitySquid['Squid'/13055, l='MpServer', x=-215,50, y=58,00, z=-463,63], EntitySkeleton['Skeleton'/13046, l='MpServer', x=-206,50, y=70,00, z=-390,50], EntityItem['item.item.sulphur'/12939, l='MpServer', x=-208,44, y=68,13, z=-415,75], EntitySkeleton['Skeleton'/12969, l='MpServer', x=-226,50, y=47,00, z=-525,50], EntityCow['Cow'/11624, l='MpServer', x=-226,25, y=63,00, z=-466,50], EntityPig['Pig'/11622, l='MpServer', x=-243,78, y=98,00, z=-375,56], EntityPig['Pig'/11621, l='MpServer', x=-242,97, y=97,00, z=-371,88], EntityBat['Bat'/14367, l='MpServer', x=-200,25, y=21,00, z=-440,88]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2433)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:908)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.7.0_71, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 30562008 bytes (29 MB) / 523501568 bytes (499 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.85.1232 Minecraft Forge 10.13.2.1232 Optifine OptiFine_1.7.10_HD_U_B4 46 mods loaded, 46 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	FML{7.10.85.1232} [Forge Mod Loader] (forge-1.7.10-10.13.2.1232.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	Forge{10.13.2.1232} [Minecraft Forge] (forge-1.7.10-10.13.2.1232.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	appliedenergistics2-core{rv1-beta-37} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	ivtoolkit{1.0} [IvToolkit] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	NotEnoughItems{1.0.3.74} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.74-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	battlegear2{1.0.6.3} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.6.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	WorldStateCheckpoints{1.7.10.r03} [WorldStateCheckpoints] ([1.7.10]WorldStateCheckpoints-client-1.7.10.r03.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	appliedenergistics2{rv1-beta-37} [Applied Energistics 2] (appliedenergistics2-rv1-beta-37.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	BiblioCraft{1.8.2} [BiblioCraft] (BiblioCraft[v1.8.2][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	CoFHCore{1.7.10R3.0.0B8} [CoFH Core] (CoFHCore-[1.7.10]3.0.0B8-36.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	BigReactors{0.4.0rc11} [Big Reactors] (BigReactors-0.4.0rc11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	AWWayofTime{v1.3.0a} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.0a-1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	Thaumcraft{4.2.2.1} [Thaumcraft] (Thaumcraft-1.7.10-4.2.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	Botania{r1.3-148} [Botania] (Botania r1.3-148.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	bountifulbreadsmod{1.0} [Bountiful Bread Mod] (bountifulbreadsmod-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	BuildCraft|Core{6.2.6} [BuildCraft] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	BuildCraft|Transport{6.2.6} [BC Transport] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	BuildCraft|Silicon{6.2.6} [BC Silicon] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	BuildCraft|Builders{6.2.6} [BC Builders] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	BuildCraft|Energy{6.2.6} [BC Energy] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	BuildCraft|Factory{6.2.6} [BC Factory] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	craftingpillars{1.5.5} [Crafting Pillars] (craftingpillars-1.7.10-1.5.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	EnderIO{1.7.10-2.1.6.250} [Ender IO] (EnderIO-1.7.10-2.1.6.250.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	ForgeMultipart{1.1.0.300} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.0.300-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	ExtraUtilities{1.2.1} [Extra Utilities] (extrautilities-1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	McMultipart{1.1.0.300} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.0.300-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	ModGeochests{1.1.1} [§aGeochests] (geochests-1.7.10-v1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	gravestonemod{1.7.2} [GraveStone] (GraveStones-1.7.2_1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	iChunUtil{4.0.0} [iChunUtil] (iChunUtil-4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	Mantle{1.7.10-0.3.1.jenkins180} [Mantle] (Mantle-mc1.7.10-0.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	testdummy{1.0} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	Morph{0.9.1} [Morph] (Morph-Beta-0.9.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	endercompass{1.0} [Ender Compass] (stronghold compass 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	Sync{4.0.0} [Sync] (Sync-4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	TConstruct{1.7.10-1.6.0.build611} [Tinkers' Construct] (TConstruct_mc1.7.10_1.6.0d40.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	thaumicinfusion{3.8.1} [Thaumic Infusion] (thaumicinfusion-1710-3838451769.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-162.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	UtilityMobs{3.1.1} [Utility Mobs] (UtilityMobs-1.7.10-3.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	witchery{0.20.6} [Witchery] (witchery-1.7.10-0.20.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	ForgeMicroblock{1.1.0.300} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.0.300-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	AE2 Version: beta rv1-beta-37 for Forge 10.13.0.1187
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	TConstruct Environment: Environment healthy.
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BC:ON, MJ6:ON, MJ5:ON, RF:ON, RFItem:ON, MFR:OFF, DSU:OFF, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:OFF, InvTweaks:OFF, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Launched Version: 1.7.10-Forge10.13.2.1232
	LWJGL: 2.9.1
	OpenGL: GeForce 9400 GT/PCIe/SSE2 GL version 3.3.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by nekosune** [comment]
Already fixed in latest 

http://jenkins.nekokittygames.com:8080/job/Thaumic%20Tinkerer/

**Comment by Keridos** [comment]
http://jenkins.nekokittygames.com:8080/job/Thaumic%20Tinkerer/439/

download that build, the bug is fixed already
