### ISSUE TITLE
Osmotic Enchanter crashes while enchanting Assassin armor

### ISSUE THREAD

**Issue by kevinkjt2000** [Thaumic-Tinkerer/ThaumicTinkerer#627]
The Assassin armor is part of Custom NPCs mod.
https://gist.github.com/kevinkjt2000/665389e578a99ef05ad3

**Comment by BluSunrize** [comment]
You are using an outdated version of TT, incompatible with the new Thaumcraft. See issue #622.

**Comment by kevinkjt2000** [comment]
I built the version myself from the develop branch of TT.  It is not outdated.

**Comment by BluSunrize** [comment]
Develop /is/ outdated. Try Master. Null pointer caused by parsing null as a player in consumeAllVis, which is replaced by a TT internal method in the latest builds.

**Comment by nekosune** [comment]
My bad there dont have the connection currently to even switch branch,
took 20 tries to push commits

**Comment by kevinkjt2000** [comment]
Ah I see thanks.
