### ISSUE TITLE
Osmotic Enchanter crash - Ticking block entity

### ISSUE THREAD

**Issue by kidrebel123** [Thaumic-Tinkerer/ThaumicTinkerer#628]
While trying to enchant an item using the osmotic enchanter the server crashes and throws out this crash report. 
http://pastebin.com/h9S3BpGC
Tried first using a thaumium bossed silverwood scepter, wasnt sure if it was a bug that the sceptre went in the table and could be used. Tried it again with a gold capped greatwood wand and produced the same error.

**Comment by Yulife** [comment]
Are you using the latest version? ._.

**Comment by kidrebel123** [comment]
2.5-1.7.10-436. thats the version currently used in the RR3 mainline pack :/

**Comment by Yulife** [comment]
It got fixed in 437 and 438 so please close this issue xD

**Comment by kidrebel123** [comment]
O.o
