### ISSUE TITLE
Robes of the Stratosphere interfere with own projectiles

### ISSUE THREAD

**Issue by Jaitsu** [Thaumic-Tinkerer/ThaumicTinkerer#633]
The Robes of the Stratosphere destroy some projectiles fired by the player as well as by enemies, including the player's own ice shards, and the disruption feature can't be disabled without killing flight as well. Ice shards especially, from the scatter-shot upgraded Frost focus, seem to be half fizzled and half momentarily vanished before reappearing some distance away.

**Comment by nekosune** [comment]
Which version of TT and TC are you using?

**Comment by Brycey92** [comment]
I can confirm this issue exists on both TT 162 and 470, with latest TC 4.2.3.5.
