### ISSUE TITLE
Awakened ichorium pickaxe arcane bore

### ISSUE THREAD

**Issue by DynamicSurbus** [Thaumic-Tinkerer/ThaumicTinkerer#637]
The awakened ichorium pickaxe does not work in the arcane bore (I know it is because it has no durability but for all the effort it takes to make it should be able to be used in a vanilla thaumcraft item)

**Comment by nekosune** [comment]
Last time looked into it wouldn't  be possible without rewriting part of tc

**Comment by nekosune** [comment]
Yeah looking into this again, would not be possible without either rewriting a lot of the arcane bore, OR setting kami tool to have instead of inifite durability, a rediculously high one, neither of which are practical, sorry

**Comment by ryukra** [comment]
Why not high finite durability and a selfhealing effect ontop? O:
