### ISSUE TITLE
Unknown crash

### ISSUE THREAD

**Issue by Stepan1404** [Thaumic-Tinkerer/ThaumicTinkerer#639]
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 1/23/15 8:28 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.entity.Entity.func_70016_h(DDD)V
    at thaumic.tinkerer.common.potion.PotionEffectHandler.onTick(PotionEffectHandler.java:90)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_94_PotionEffectHandler_onTick_ServerTickEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:252)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:851)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
    at java.lang.Thread.run(Thread.java:745)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    FML: MCP v9.05 FML v7.10.85.1240 git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212 (MC: 1.7.10) (API v1.7.10-R0.1-SNAPSHOT) Minecraft Forge 10.13.2.1240 19 mods loaded, 19 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.10.85.1240} [Forge Mod Loader](Core.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.13.2.1240} [Minecraft Forge](Core.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{1.0.4.29} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems{1.0.4.83} [Not Enough Items](NotEnoughItems-1.7.10-1.0.4.83-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Thaumcraft{4.2.3.3} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    chisel{2.2.1} [Chisel](Chisel 2-2.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    dungeonpack{1.7.10-1.0} [Dungeon Pack](dungeonpack-1.7.10-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThaumicTinkerer{unspecified} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-440.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ForbiddenMagic{1.7.10-0.552} [Forbidden Magic](Forbidden Magic-1.7.10-0.552.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    inventorytweaks{1.58-147-645ca10} [Inventory Tweaks](InventoryTweaks-1.58-147.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IronChest{6.0.62.742} [Iron Chest](IronChests.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Mantle{1.7.10-0.3.1.jenkins180} [Mantle](Mantle-mc1.7.10-0.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TConstruct{1.7.10-1.6.0.build611} [Tinkers' Construct](TConstruct_mc1.7.10_1.6.0d40.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThaumicExploration{0.6.0} [Thaumic Exploration](ThaumicExploration-1.7.10-1.1-36.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TwilightForest{2.3.2} [The Twilight Forest](twilightforest-1.7.10-2.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    bspkrsCore{6.15} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: bukkit
    TConstruct Environment: Environment healthy.
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 7 / 100
    Is Modded: Definitely; Server brand changed to 'cauldron,craftbukkit,mcpc,fml,forge'
    Type: Dedicated Server (map_server.txt)
Crash in Server part. i don't know why.

**Comment by nekosune** [comment]
What versions TC and TT are you using?

**Comment by IKilledTheDevil** [comment]
I'm also having problems note that I'm using the Driewolf20 mod pack with extra mods added.
Crash Report: http://pastebin.com/RLGsuuje

**Comment by IKilledTheDevil** [comment]
Nevermind the problem was with Thaumic Energistics not TT.

**Comment by nekosune** [comment]
@IKilledTheDevil Yeah it helps to use the non dev jar :)

**Comment by Stepan1404** [comment]
ThaumCraft 4.2.3.2.  ThaumicTinkerer 2.5 1.7.10-440

**Comment by nekosune** [comment]
Please try upgrading, and if it stil breaks, post new crashlog

**Comment by Stepan1404** [comment]
Now i don't have this crash. If i will have it i will write.

**Comment by Stepan1404** [comment]
*In new version

**Comment by xJon** [comment]
Happened now with v2.5-1.7.10-508, any idea?

**Comment by nekosune** [comment]
It looks like the air potion was used on something that can't have a velocity, if you can find a test case that guarantees the crash, can fix

**Comment by xJon** [comment]
It's something that related to the Twilight Forest bosses. Anyway I told the guy who had the problem to come here.
