### ISSUE TITLE
Thaumic Tinkerer Foci Bugs

### ISSUE THREAD

**Issue by Dayyer1** [Thaumic-Tinkerer/ThaumicTinkerer#641]
The shadowbeam's texture shoots music notes, while the xp drain doesn't work at all. I'm using using thaumcraft 4.2.2.1, and the latest version of the crackpack 2. Help?

**Comment by DrQwertySilence** [comment]
I have a fix for that, if Nekosune like the change I will make a pull request.
http://imgur.com/tyhnFrO,CJ1Ioi0

**Comment by Dayyer1** [comment]
Ok

**Comment by nekosune** [comment]
@DrQwertySilence  Please just make the pull requests if you feel needed,. dont mention them on issues :p

**Comment by DrQwertySilence** [comment]
@nekosune
Counting with that then.
I can't do the pull in the current state.
How can I contact you? (irc, skype, derpbook...)

**Comment by nekosune** [comment]
on IRC irc.esper.net #pixlepix

**Comment by Dayyer1** [comment]
Also, are there no upgrades/enchantments for the kami foci?

**Comment by DrQwertySilence** [comment]
Already fixed, still won't pull, I still need to check more thing about the item. Maybe one/two days more. xd

**Comment by Dayyer1** [comment]
Maybe the crackpack isn't up to date. I'll have to figure that out I guess.
What do you mean by pull?

**Comment by DrQwertySilence** [comment]
A request to merge changes.

**Comment by Dayyer1** [comment]
How will I know when the update is ready? (If there will be one soon)

**Comment by DrQwertySilence** [comment]
Is ready now.

**Comment by Dayyer1** [comment]
One more question:
Where can I find it? c:

**Comment by DrQwertySilence** [comment]
Here: http://jenkins.nekokittygames.com:8080/job/Thaumic%20Tinkerer/
