### ISSUE TITLE
Unable to disable infused fires via config option

### ISSUE THREAD

**Issue by FakoTheGreat** [Thaumic-Tinkerer/ThaumicTinkerer#651]
Using build #457 and Thaumcraft 4.2.3.4, you can still craft imbued flames when they are disabled via config. Here is the config file I'm using: https://gist.github.com/FakoTheGreat/97c071bdd16f016d1e0c

I tested crafting in SSP and SMP using Forge 1236, using both manual and automated alchemy to make perditio imbued fire.

**Comment by DrQwertySilence** [comment]
Yeah, you can craft them but the effect doesn't work.
Dunno if is really a bug.

**Comment by nekosune** [comment]
This is something I am considering how to change, I might just remove crafting, but leave inworld ones, as some people like to use them as coloureful  fire for aesthetics.

**Comment by FakoTheGreat** [comment]
In all honesty, I had been too worried to try placing down one of the more violent ones, after an initial check to see if disabling was a good idea.  The config option turning them into pretty fires is more than sufficient for my needs...

**Comment by Zandorum** [comment]
I would like to add to this that a config option to limit their spread would be also sufficent. I'd like their functionality but I'd rather not have it consume a whole biome more like a whole tree would be a good nerfed distance.
