### ISSUE TITLE
 Osmotic  Enchanter Crash

### ISSUE THREAD

**Issue by KIdWither** [Thaumic-Tinkerer/ThaumicTinkerer#653]
Crash repot(mods are at the bottom): http://pastebin.com/C03iap32

**Comment by nekosune** [comment]
allready fixed

**Comment by netmc** [comment]
Fixed in Jenkin's Build.  You can grab the latest here. - http://jenkins.nekokittygames.com:8080/view/Thaumic%20Tinkerer/job/Thaumic%20Tinkerer/
