### ISSUE TITLE
Crash Without ComputerCraft

### ISSUE THREAD

**Issue by ubermentat** [Thaumic-Tinkerer/ThaumicTinkerer#655]
Forge: 1291
Thaumic Tinkerer: Build 465
Crash Report: <https://gist.github.com/ubermentat/c95897d9ea7f1db3a3b0>

Crash happens on startup, only when Thaumic Tinkerer is installed. It seems like Thaumic Tinkerer is looking for part of ComputerCraft's api.

**Comment by Dream-Master** [comment]
The error is not gone. test with 466.

https://gist.github.com/Dream-Master/9a1a12089a98ec22eb3d#file-gistfile1-txt
