### ISSUE TITLE
Thrown Potion => Crash

### ISSUE THREAD

**Issue by sheynandr** [Thaumic-Tinkerer/ThaumicTinkerer#657]
If thrown any potion to player server will be crashed.
Full detailed crash-report see in gist https://gist.github.com/sheynandr/9caf3ede2de2d6123438

**Comment by nekosune** [comment]
Please  test with latest jenkins version, http://jenkins.nekokittygames.com:8080/job/Thaumic%20Tinkerer/ also we only support bugs that show in vanilla forge,  so if this is a craftbukkit  only bug it will be lower priority. 



—
