### ISSUE TITLE
[461]Robes of the Stratosphere vs. Botania strikes again!

### ISSUE THREAD

**Issue by MajorCooke** [Thaumic-Tinkerer/ThaumicTinkerer#665]
Botania r1.4-157
ThaumicTinkerer-2.5-1.7.10-461

Posted here as well: https://github.com/Vazkii/Botania/issues/536

Thankfully not as bad as my last report though. For some reason, when standing on top of, or in the way of the mana beams, they now pass through every single object -- even solid ones -- while ROTS is enabled. Try it with a gaia mana spreader for example.

This is until it gets out of range of the player (which is... I dont know how many blocks away) but one can tell it happens when the beam suddenly vanishes and stops emitting particles. When it reappears, it's open to hitting blocks again.

**Comment by nekosune** [comment]
Please give versions when submitting bug reports

**Comment by MajorCooke** [comment]
Ah sorry.
Botania r1.4-157
ThaumicTinkerer-2.5-1.7.10-461
