### ISSUE TITLE
Osmotic Enchanter crashing when I try to use it.

### ISSUE THREAD

**Issue by davidfizz32** [Thaumic-Tinkerer/ThaumicTinkerer#666]
Whenever I try to use the Osmotic Enchanter, it crashes my world. I've been able to fix it by deleting the enchanter in MCedit. This bug happens with each wand/scepter, and vanilla/mod tools. Essentially, it's unusable.

P.S. I did have the correct setup with the 6 pillars of obsidian totems with nitor on top. They also met the height required, and were within 3 blocks of the enchanter.

**Comment by Meegooo** [comment]
Use lastest jenkins build, fixed already
