### ISSUE TITLE
Where are the downloads for TT?

### ISSUE THREAD

**Issue by horfius** [Thaumic-Tinkerer/ThaumicTinkerer#669]
Not really an issue, but I can't seem to find the downloads for this mod as the official posts aren't updated and the jenkins server downloads from http://jenkins.nekokittygames.com/tt/ are down. Where are the latest builds of this?

**Comment by Adaptivity** [comment]
http://jenkins.nekokittygames.com:8080/job/Thaumic%20Tinkerer/

**Comment by horfius** [comment]
Thanks! Google searches weren't turning that up.
