### ISSUE TITLE
Minecraft 1.7.10 kami armor error

### ISSUE THREAD

**Issue by facux3** [Thaumic-Tinkerer/ThaumicTinkerer#670]
hi, im traying to infusion craft the kami pants and helmet but the infussion never start...  i've checked all the ingredients more than 10 time in every part, but it is not the problem... can anybody tell what can it be? I could craft the chest and the boots, but I can not with the rest.. pls help me

**Comment by Erelaszun** [comment]
Seems my server is having the same problem. Using ThaumicTinkerer-2.5-1.7.10-465.jar

**Comment by mattakaslash** [comment]
Just piping up as another person experiencing this issue. I'm using ThaumicTinkerer-2.5-1.7.10-470.jar

**Comment by UlricWulfhere** [comment]
I have made the Leggings, but I get same problem with the Cowl. I haven't tried the other recipes yet.

**Comment by mattakaslash** [comment]
The Worldshaper tool also fails to start infusing for me. As it may be relevant, the version of Thaumcraft for me is Thaumcraft-1.7.10-4.2.3.4.jar

**Comment by neilometer** [comment]
I commented on #692, but I feel it bears repeating:  Make sure the metadata on your potion of night vision is correct. For example, 373:8230 will NOT work, but 373:8198 will. I found the same thing with the leggings. The fire resist potion had to match a specific metadata. Luckily, the loot bags drop them fairly frequently.
