### ISSUE TITLE
Inv Tweaks compatibility?

### ISSUE THREAD

**Issue by Hazado** [Thaumic-Tinkerer/ThaumicTinkerer#672]
I attempted to add InvTweaks compatibility using the InvTweaksCompatibility.xml file and it failed horribly.
Do you think you could add something to make this work?

Crash log from my attempts - http://pastebin.com/dRqdEK8J

Below is what I tried in the compatibility file.
InvTweaksCompatibility.xml
```xml
<root>
<chest class="thaumic.tinkerer.common.item.kami.ItemIchorPouch" row_size="9" large_chest="false"/>
<inventory class="thaumic.tinkerer.common.item.kami.ItemIchorPouch" disable_buttons="false"/>
</root>
```

**Comment by nekosune** [comment]
"thaumic.tinkerer.common.block.tile.container.kami.ContainerIchorPouch" is the needed string, and you only need ONE of them not both chest OR inventory, you probably wanted chest
