### ISSUE TITLE
Gregtech ore in bedrock dimension

### ISSUE THREAD

**Issue by Hazado** [Thaumic-Tinkerer/ThaumicTinkerer#673]
Gregtech Ore spawns incorrectly in the bedrock dimension.
Is there any way to fix this?
![untitled](https://cloud.githubusercontent.com/assets/416114/6260829/6ab4a374-b799-11e4-8d1f-b159397b08cd.jpg)

**Comment by TheJulianJES** [comment]
@Hazado I think Greg has to fix this.

**Comment by secirpac** [comment]
[https://github.com/Blood-Asp/GT5-Unofficial/issues/572](url)

> That is because they do not run the ore-gen calls so the GT ores never get setup, instead they just setBlock and forget, which is a bad bad bad way of doing it. Need to report it to the devs to tell them to run the oregen code on the ore they setup. GT is not the only mod their method will break.

Would you please fix this bug? @nekosune
