### ISSUE TITLE
[162]Black Hole Ring completely broken?

### ISSUE THREAD

**Issue by MajorCooke** [Thaumic-Tinkerer/ThaumicTinkerer#676]
First, all thaumcraft mods and subsets:
Thaumcraft 4.2.3.5
TT 162
Thaumic Horizons 1.0.2
Automagy 0.19.3

Should note that I've tried creative spawning this item in, and after activating and turning on to suck up any kind of block, it doesnt work at all. It's literally a dead item in my inventory: active and inactive.

**Comment by nekosune** [comment]
Have you tried putting it in it's bauble slot?

**Comment by MajorCooke** [comment]
Wait, it's an actual ring now? Aw man. :(

**Comment by nekosune** [comment]
Did it work? marking as closed until I get more information
