### ISSUE TITLE
Change Osmotic Enchanter from wand vis to CV+EXP

### ISSUE THREAD

**Issue by Serifina** [Thaumic-Tinkerer/ThaumicTinkerer#678]
The Osmotic Enchanter might be better balanced and better integrated into Thaumcraft's feel if it works similarly to the new foci manipulator - which is to say, it should be updated to use CV and EXP to place enchantments, rather than wand vis.

**Comment by nekosune** [comment]
The CV was going to be a requiement, but people didnt seem to like it, and no, it is meant to be a replacement for experience, not something as WELL as

**Comment by Serifina** [comment]
What about at least adding the wand relay charger that goes on the arcane workbench? Then it can utilize both, at least by proxy.

**Comment by nekosune** [comment]
That is hard coded in TC, there is no way to use that . it would have to be a new item, that would do the same thing. No real difference then.
