### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by EmanYm** [Thaumic-Tinkerer/ThaumicTinkerer#681]
I decided to go through my log file because I was tired of all the red text...Searching "error" in the texxt file I found a few missing textures related to Thaumic Tinkerer.

[Client thread/ERROR]: Using missing texture, unable to load ttinkerer:textures/blocks/repairer.png, java.io.FileNotFoundException
[Client thread/ERROR]: Using missing texture, unable to load ttinkerer:textures/blocks/magnet.png, java.io.FileNotFoundException
[Client thread/ERROR]: Using missing texture, unable to load ttinkerer:textures/items/ichorSwordGem.png, java.io.FileNotFoundException
[Client thread/ERROR]: Using missing texture, unable to load ttinkerer:textures/items/ichorAxeGem.png, java.io.FileNotFoundException
[Client thread/ERROR]: Using missing texture, unable to load ttinkerer:textures/items/ichorPickGem.png, java.io.FileNotFoundException
[Client thread/ERROR]: Using missing texture, unable to load ttinkerer:textures/items/mobAspect.png, java.io.FileNotFoundException

I thought I could replace any missing textures by downloading them from the GitHub, but they are not there either...I assume the items have been removed?

**Comment by Adaptivity** [comment]
Textures still here but they seems to be renamed/moved and the code still looking for old names.

**Comment by belathus** [comment]
To add to the missing textures, the soul aspect for Messis is showing the "missing texture" texture.

**Comment by EmanYm** [comment]
I am assuming this has been fixed long ago.
