### ISSUE TITLE
[Idea]would you consider requesting an Ichor armor texture from damien_hazard

### ISSUE THREAD

**Issue by kurokuno** [Thaumic-Tinkerer/ThaumicTinkerer#683]
he works for free/fun and takes requests from devs as right now the armor texture is Very out of place next to the rest of thaumcraft given he made all the armors for it he would likely be happy to do ichor for you

**Comment by AlfieSR** [comment]
If/when the armour texture is updated, could you also also update it to use the void/crimson robes models? The default armour model is.. unflattering next to the considerably fancier models used by newer thaumcraft armours.

**Comment by Dayyer1** [comment]
I hope this gets attention eventually because it would be awesome
