### ISSUE TITLE
Osmotic Enchanter causing fatal crash

### ISSUE THREAD

**Issue by Monkey-Puzzle** [Thaumic-Tinkerer/ThaumicTinkerer#684]
Hello! 
In the DW20 FTB pack 1.0.4, with Thaumic Tinker 2.5-1.7.10-162 and Thaumcraft 4.2.3.4, I'm getting fatal crashes when using the Osmotic Enchanter that require me to roll back to a backup. You can see it happen in a video I made: https://www.youtube.com/watch?v=_ZNDjziMgXk&feature=player_detailpage#t=731

Here is the full crash report: http://pastebin.com/feGwXD81

A commenter told me this: With the Thaumcraft update the wands have changed. Thaumic Tinkerer calls a function that doesn't exist anymore in the Thaumcraft code while draining the vis out of the wand.

Thank you for your time and this awesome mod,
Monkeypuzzle

**Comment by nekosune** [comment]
Is fixed in update, http://jenkins.nekokittygames.com:8080/job/Thaumic%20Tinkerer/

**Comment by Monkey-Puzzle** [comment]
Thank you so much, nekosune. I'm updating our server now.

**Comment by nekosune** [comment]
The latest version there fixes quite a few bugs, like there is no longer a
crash bug if you spawn a skellington in the nether with the tablet, and all
that. There is more ocmining and in the upcoming week or so it will be
released to curseforge as 163

**Comment by Monkey-Puzzle** [comment]
That's really great to know. I'll give a shout out about the update in my next ep. This is the first time I'm getting all the way through Thaumic Tinkerer and I'm very excited about it--just opened up Ichor yesterday...

**Comment by nekosune** [comment]
No trouble, Would you wish a more compelte changelog? though this has been
pure bug fixes no new features

**Comment by Monkey-Puzzle** [comment]
That's fine; only if you wish me to link to it. I haven't had a chance yet to find most of the bugs you've fixed. It's enough for me to know that a compatible build exists. I'm sure you will encounter some confusion for a while since the 1.0.4 DW20 update got it wrong. Thank you again for doing the work of maintaining this great mod.
