### ISSUE TITLE
hoping for some help compiling TT

### ISSUE THREAD

**Issue by arkD** [Thaumic-Tinkerer/ThaumicTinkerer#686]
I run a server with a lot of mob modifiers significantly increasing the difficulty of the server. I thought it would be cool to have ichor armor implement IRunicArmor. 
I have forked thaumic tinkerer, created a project in Idea, setup decomp workspace, but I need thaumcraft dependencies. I used BON to deobf and even took it a step further and decompiled.
the trouble is that even though I have added the source/class to the external libraries it still cant find the thaumcraft packages when compiling: "error: package thaumcraft.client.gui.research does not exist"

How do I get IDEA to recognize the thaumcraft packages so i can test my custom build of TTkami?

thanks in advance!

**Comment by nekosune** [comment]
Firstly, Azanor gives you the dev package on the thread, you just put that in a folder named libs THEN run gradlew setupDecompWorkspace and gradlew idea
Secondly, idea does decompile on its own once it can see 
Thirdly there will be a possibility of Runic armor added, but to be honest, the idea for kami is going to be something different, though no less powerful, it may or it may not have runic armor, but if it dosnt, it will be to make sure it fits in well
