### ISSUE TITLE
Black hole ring doesn't work with torches?

### ISSUE THREAD

**Issue by jgilmore** [Thaumic-Tinkerer/ThaumicTinkerer#687]
I have two black hole rings, cobblestone works fine. Torches do not. Neither does short tesselated bamboo (from the mo' plants mod)

Stone, obsidian, greatwood logs, all work fine. Coal does not. Neither (predictably enough) does redstone.

Perhaps we should be able to toss an _item_ out and click on it (like we do so often with the thaumometer) to select which _item_ to absorb, instead of only being able to select _block_ type items.

Still no idea why torches and bamboo don't work.

**Comment by nickgalderisi** [comment]
The Black Hole Ring or Block Talisman as it is refered to as in the code only works with blocks as seen in ItemBlockTalisman.java so, this is an intended feature.
