### ISSUE TITLE
Awakened Ichorium Pickaxe (and possibly shovel) destroying blocks

### ISSUE THREAD

**Issue by Sakata-MC** [Thaumic-Tinkerer/ThaumicTinkerer#688]
I'm not sure exactly how the ratio works out or if it is just with certain blocks, but the pickaxe in square mode seems to destroy some blocks instead of being picked up.  Not exactly sure of the reason, but could be related to some blocks being broken despite not showing being broken until the client updates, or how block updates don't seem to trigger when using the tools (water doesn't fall, and such, until something triggers a block update)

Possible that it is some interaction with another mod in DW20 FtB pack (1.0.4), or that this has already been addressed and I'm behind due to FtB update lag.
If so, please close the issue, but figured I'd report it.

Also occuring in ftb 1.1.1 with ThaumicTinkerer-2.5-1.7.10-469
Fastcraft is also in the pack so you are aware

**Comment by Brycey92** [comment]
I have this issue as well. I can confirm that some ratio of blocks broken do not drop at all, regardless of relog or block / chunk update.
