### ISSUE TITLE
Legging of the Burning Mantle - fake torches not being removed

### ISSUE THREAD

**Issue by Sakata-MC** [Thaumic-Tinkerer/ThaumicTinkerer#691]
Title pretty much sums it up. The fake lights that are placed don't seem to time out, or if they do it is seemingly random. This is in ThaumicTinkerer-2.5-1.7.10-469
Fastcraft is also installed if that may have bearing.

**Comment by AnAverageHuman** [comment]
It seems to function similarly to the Gaseous Illuminae. You might be able to get rid of it by using Gaseous Tenebrae after turning off your KAMI armor (defaults to `u`) or by having someone else place it after you leave the area.
