### ISSUE TITLE
Awakened Ichorium Pickaxe odd block update behavior

### ISSUE THREAD

**Issue by Brycey92** [Thaumic-Tinkerer/ThaumicTinkerer#694]
When mining in line or square mode, the pick either:
- destroys the block on the server, but does not remove it from the client, allowing the player to walk into the "ghost" block and see an x-ray of the world
- destroys the block on the client, but not on the server, causing the player to "rubber band" back and forth if they try to move through this block
- or successfully destroys the block on both client and server.

All 3 cases can be recreated simply by going on a short mining trip with the pick. It should also be noted that the blocks around those broken do not receive block updates. Thus, liquids do not flow, things do not pop off walls, etc.

**Comment by Euphoreich** [comment]
Hey having the same issue on tppi2 atm. Have you guys fixed this?
