### ISSUE TITLE
Breaking Extra Utilities drums with Awakened Ichorium Pickaxe causes them to disappear

### ISSUE THREAD

**Issue by AnAverageHuman** [Thaumic-Tinkerer/ThaumicTinkerer#697]
Using the Awakened Ichorium Pickaxe in "square mode" or "line mode" causes an Extra Utilities drum to be destroyed but not dropped if it is in the pickaxe's range. Using the pickaxe in "block mode" seems to work.

**Comment by Brycey92** [comment]
Seems to be related to #688.
