### ISSUE TITLE
[Feature] Config to disable certain enchantments

### ISSUE THREAD

**Issue by Brycey92** [Thaumic-Tinkerer/ThaumicTinkerer#698]
I propose a config section for disabling individual enchantments. For example, I would want to disable the pounce enchantment because people on my server have been using it to easily and inexpensively deal massive damage to players with expensive high-tier armor, such as the awakened Kami armor and the QuantumSuit.

**Comment by Brycey92** [comment]
Does this being closed mean this was implemented? @nekosune

**Comment by MajorCooke** [comment]
He's starting again from scratch. But he did make a note on all the things people have requested.

**Comment by nekosune** [comment]
All of the enchantments will be enabled/disabled in config
