### ISSUE TITLE
bug with texturepack

### ISSUE THREAD

**Issue by partyanimal** [Thaumic-Tinkerer/ThaumicTinkerer#703]
Hello i am experiencing a weird bug I am using this version ThaumicTinkerer-2.5-1.7.10-162 (should be the latest build ) everytime i put in a texturepack patch for TT my fps goes from 140 fps to 0 (it is the 128x by sphax) and no my pc can handle it i am using a lot of these textures and if i put even more patches in from other mods it still is 140 fps but the moment i put in the one from TT it goes to 0 anyone have an idea as in why ? the link of the patch http://www.mediafire.com/download/p93rfv0frbe6b3e/Sphax128x_ThaumicTinkerer_2.5.1.7.10-160.zip

**Comment by O13SC3N3** [comment]
Uhm, off subject but you wouldn't even seen a difference from 60 to 140, most monitors, TVs or any screen format doesn't. Your card is essentially working harder then it needs to. And in a lot of cases that can cause fps spikes, try enabling vsynch
