### ISSUE TITLE
Transvector Interface not working with RF power

### ISSUE THREAD

**Issue by timrockz123** [Thaumic-Tinkerer/ThaumicTinkerer#705]
I can't seem to find a way to get the transvector interface to supply power to a Thermal Expansion pulverizer. Ive tried every way of rf transport and none of them work

**Comment by Daedalus11069** [comment]
This still appears to be broken, at least on my end.  Tried with Thermal Dynamics fluxducts as well as enderio conduits, and rednet cables.  All failed to work.
![2015-08-03_16 45 48](https://cloud.githubusercontent.com/assets/1094363/9050135/3b36533e-39ff-11e5-823c-5e5b03d7b825.png)

Given I don't see any commits that reference any further fixes for this issue(I'm on 502 of 1.7-final), I'm guessing something changed.  If it matters at all, I'm using the 1.5.0 Direwolf20 modpack from ftb, which of course currently uses Thermal Expansion 4/Thermal Dynamics/etc.  I'm not sure what other mods could cause this to fail.. though curiously, fluids from Thermal Dynamics still work.
