### ISSUE TITLE
Awakend Ichorium Pickaxe + Blocks with metadata issue

### ISSUE THREAD

**Issue by SirWilli** [Thaumic-Tinkerer/ThaumicTinkerer#706]
hey,

if you break a block with the ID 343:4 for example it will drop the block 343 which is an big issue with creative items from thermal expansion or ender io because it will drop the creative type of the block if you break the normal one for example Hardened Strongbox -> Creative Strongbox.

**Comment by bookerthegeek** [comment]
Is this something we can update server side until the respective modpacks update to this version as well? Or would it be required that the client would match?

**Comment by nekosune** [comment]
It is a major update so yes, clients need to match too
