### ISSUE TITLE
Computer Blocks only appear if ComputerCraft is installed

### ISSUE THREAD

**Issue by Vexatos** [Thaumic-Tinkerer/ThaumicTinkerer#707]
Despite having full OpenComputers compatibility, blocks like the Aspectalyzer only get registered if ComputerCraft is there. This makes them impossible to use with OpenComputers when ComputerCraft isn't installed. This should be pretty easy to fix.

**Comment by nf404** [comment]
Without Aspectalyzer the only way in OpenComputers to view item aspects is enabling NBT data view by computer.
