### ISSUE TITLE
Crash involving glass.....?

### ISSUE THREAD

**Issue by Megachuggayoshi** [Thaumic-Tinkerer/ThaumicTinkerer#708]
am glad that this web site exist so people can help me with this (sorry for the wall : /)

---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 3/29/15 7:22 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoSuchFieldError: glass
at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:515)
at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchFieldError: glass
at flaxbeard.thaumicexploration.block.BlockThinkTank.(BlockThinkTank.java:49)
at flaxbeard.thaumicexploration.ThaumicExploration.preInit(ThaumicExploration.java:347)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
... 10 more
A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
Minecraft Version: 1.7.10
Operating System: Mac OS X (x86_64) version 10.9.4
Java Version: 1.8.0_40, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 183143032 bytes (174 MB) / 729284608 bytes (695 MB) up to 954728448 bytes (910 MB)
JVM Flags: 1 total; -Xmx1G
AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 106 mods loaded, 106 mods active
mcp{9.05} Minecraft Coder Pack Unloaded->Constructed->Pre-initialized
FML{7.10.85.1291} Forge Mod Loader Unloaded->Constructed->Pre-initialized
Forge{10.13.2.1291} Minecraft Forge Unloaded->Constructed->Pre-initialized
appliedenergistics2-core{rv1-stable-1} AppliedEnergistics2 Core Unloaded->Constructed->Pre-initialized
CodeChickenCore{1.0.4.29} CodeChicken Core Unloaded->Constructed->Pre-initialized
NotEnoughItems{1.0.4.83} Not Enough Items Unloaded->Constructed->Pre-initialized
OpenModsCore{0.6} OpenModsCore Unloaded->Constructed->Pre-initialized
{000} CoFH ASM Data Initialization Unloaded->Constructed->Pre-initialized
bspkrsCore{6.15} bspkrsCore Unloaded->Constructed->Pre-initialized
Treecapitator{1.7.10} Treecapitator Unloaded->Constructed->Pre-initialized
AppleCore{1.1.0} AppleCore Unloaded->Constructed->Pre-initialized
appliedenergistics2{rv1-stable-1} Applied Energistics 2 Unloaded->Constructed->Pre-initialized
ArchimedesShips{1.7.10 v1.7.1} Archimedes' Ships Unloaded->Constructed->Pre-initialized
Backpack{2.0.0} Backpack Unloaded->Constructed->Pre-initialized
BiblioCraft{1.9.2} BiblioCraft Unloaded->Constructed->Pre-initialized
CoFHCore{1.7.10R3.0.0RC7} CoFH Core Unloaded->Constructed->Pre-initialized
ThermalFoundation{1.7.10R1.0.0RC7} Thermal Foundation Unloaded->Constructed->Pre-initialized
ThermalExpansion{1.7.10R4.0.0RC7} Thermal Expansion Unloaded->Constructed->Pre-initialized
BigReactors{0.4.1A} Big Reactors Unloaded->Constructed->Pre-initialized
AWWayofTime{v1.3.0b} Blood Magic: Alchemical Wizardry Unloaded->Constructed->Pre-initialized
BuildCraft|Core{6.4.3} BuildCraft Unloaded->Constructed->Pre-initialized
BuildCraft|Transport{6.4.3} BC Transport Unloaded->Constructed->Pre-initialized
BuildCraft|Silicon{6.4.3} BC Silicon Unloaded->Constructed->Pre-initialized
BuildCraft|Builders{6.4.3} BC Builders Unloaded->Constructed->Pre-initialized
BuildCraft|Energy{6.4.3} BC Energy Unloaded->Constructed->Pre-initialized
BuildCraft|Factory{6.4.3} BC Factory Unloaded->Constructed->Pre-initialized
CarpentersBlocks{3.3.5} Carpenter's Blocks Unloaded->Constructed->Pre-initialized
ChickenChunks{1.3.4.16} ChickenChunks Unloaded->Constructed->Pre-initialized
Baubles{1.0.1.10} Baubles Unloaded->Constructed->Pre-initialized
Thaumcraft{4.2.3.4} Thaumcraft Unloaded->Constructed->Pre-initialized
ForgeMultipart{1.1.0.314} Forge Multipart Unloaded->Constructed->Pre-initialized
chisel{2.3.7.34} Chisel 2 Unloaded->Constructed->Pre-initialized
ComputerCraft{1.65} ComputerCraft Unloaded->Constructed->Pre-initialized
customnpcs{1.7.10c} CustomNpcs Unloaded->Constructed->Pre-initialized
Waila{1.5.8} Waila Unloaded->Constructed->Pre-initialized
extracells{2.1.37} ExtraCells Unloaded->Constructed->Pre-initialized
ExtraUtilities{1.2.2} Extra Utilities Unloaded->Constructed->Pre-initialized
flansmod{4.9.0} Flan's Mod Unloaded->Constructed->Pre-initialized
ForbiddenMagic{1.7.10-0.562} Forbidden Magic Unloaded->Constructed->Pre-initialized
Forestry{3.4.0.7} Forestry for Minecraft Unloaded->Constructed->Pre-initialized
Growthcraft{2.1.0a} Growthcraft Unloaded->Constructed->Pre-initialized
Growthcraft|Cellar{2.1.0a} Growthcraft Cellar Unloaded->Constructed->Pre-initialized
Growthcraft|Apples{2.1.0} Growthcraft Apples Unloaded->Constructed->Pre-initialized
Growthcraft|Bamboo{2.1.0} Growthcraft Bamboo Unloaded->Constructed->Pre-initialized
Growthcraft|Bees{2.1.0} Growthcraft Bees Unloaded->Constructed->Pre-initialized
Growthcraft|Fishtrap{2.1.0a} Growthcraft Fishtrap Unloaded->Constructed->Pre-initialized
Growthcraft|Grapes{2.1.0} Growthcraft Grapes Unloaded->Constructed->Pre-initialized
Growthcraft|Hops{2.1.0} Growthcraft Hops Unloaded->Constructed->Pre-initialized
Growthcraft|Rice{2.1.0a} Growthcraft Rice Unloaded->Constructed->Pre-initialized
iChunUtil{4.1.3} iChunUtil Unloaded->Constructed->Pre-initialized
inventorytweaks{1.58-147-645ca10} Inventory Tweaks Unloaded->Constructed->Pre-initialized
IronChest{6.0.62.742} Iron Chest Unloaded->Constructed->Pre-initialized
JABBA{1.1.4} JABBA Unloaded->Constructed->Pre-initialized
Mantle{1.7.10-0.3.2.jenkins184} Mantle Unloaded->Constructed->Pre-initialized
MineFactoryReloaded{1.7.10R2.8.0RC8} MineFactory Reloaded Unloaded->Constructed->Pre-initialized
TConstruct{1.7.10-1.8.2.build858} Tinkers' Construct Unloaded->Constructed->Pre-initialized
MagicBees{1.7.10-2.1.22} Magic Bees Unloaded->Constructed->Pre-initialized
RedstoneArsenal{1.7.10R1.1.0RC7} Redstone Arsenal Unloaded->Constructed->Pre-initialized
Mekanism{7.1.1} Mekanism Unloaded->Constructed->Pre-initialized
MekanismGenerators{7.1.1} MekanismGenerators Unloaded->Constructed->Pre-initialized
MekanismTools{7.1.1} MekanismTools Unloaded->Constructed->Pre-initialized
minechem{5.0.5.385} Minechem Unloaded->Constructed->Pre-initialized
MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0RC8} MFR Compat: Applied Energistics Unloaded->Constructed->Pre-initialized
MineFactoryReloaded|CompatAtum{1.7.10R2.8.0RC8} MFR Compat: Atum Unloaded->Constructed->Pre-initialized
MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0RC8} MFR Compat: BackTools Unloaded->Constructed->Pre-initialized
MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0RC8} MFR Compat: BuildCraft Unloaded->Constructed->Pre-initialized
MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0RC8} MFR Compat: Chococraft Unloaded->Constructed->Pre-initialized
MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0RC8} MFR Compat: ExtraBiomes Unloaded->Constructed->Pre-initialized
MineFactoryReloaded|CompatForestry{1.7.10R2.8.0RC8} MFR Compat: Forestry Unloaded->Constructed->Pre-initialized
MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0RC8} MFR Compat: ForgeMicroblock Unloaded->Constructed->Pre-initialized
MineFactoryReloaded|CompatIC2{1.7.10R2.8.0RC8} MFR Compat: IC2 Unloaded->Constructed->Pre-initialized
MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0RC8} MFR Compat: Mystcraft Unloaded->Constructed->Pre-initialized
MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0RC8} MFR Compat ProjectRed Unloaded->Constructed->Pre-initialized
MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC8} MFR Compat: Railcraft Unloaded->Constructed->Pre-initialized
MineFactoryReloaded|CompatRP2{1.7.10R2.8.0RC8} MFR Compat: RP2 Unloaded->Constructed->Pre-initialized
MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0RC8} MFR Compat: Sufficient Biomes Unloaded->Constructed->Pre-initialized
MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC8} MFR Compat: Thaumcraft Unloaded->Constructed->Pre-initialized
MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0RC8} MFR Compat: Thermal Expansion Unloaded->Constructed->Pre-initialized
MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0RC8} MFR Compat: Tinkers' Construct Unloaded->Constructed->Pre-initialized
MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0RC8} MFR Compat: TwilightForest Unloaded->Constructed->Pre-initialized
MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC8} MFR Compat: Vanilla Unloaded->Constructed->Pre-initialized
testdummy{1.0} MmmMmmMmmMmm Unloaded->Constructed->Pre-initialized
NEIAddons{1.12.4.16} NEI Addons Unloaded->Constructed->Pre-initialized
NEIAddons|Botany{1.12.4.16} NEI Addons: Botany Unloaded->Constructed->Pre-initialized
NEIAddons|Forestry{1.12.4.16} NEI Addons: Forestry Unloaded->Constructed->Pre-initialized
NEIAddons|CraftingTables{1.12.4.16} NEI Addons: Crafting Tables Unloaded->Constructed->Pre-initialized
NEIAddons|ExNihilo{1.12.4.16} NEI Addons: Ex Nihilo Unloaded->Constructed->Pre-initialized
NetherOres{1.7.10R2.3.0RC4} Nether Ores Unloaded->Constructed->Pre-initialized
OpenMods{0.6} OpenMods Unloaded->Constructed->Pre-initialized
OpenBlocks{1.3} OpenBlocks Unloaded->Constructed->Pre-initialized
harvestcraft{1.7.10d} Pam's HarvestCraft Unloaded->Constructed->Pre-initialized
RandomThings{2.2.4} Random Things Unloaded->Constructed->Pre-initialized
Roguelike{1.3.5} Roguelike Dungeons Unloaded->Constructed->Pre-initialized
simplyjetpacks{1.3.2} Simply Jetpacks Unloaded->Constructed->Pre-initialized
TabulaRasa{1.7.10R1.0.1} Tabula Rasa Unloaded->Constructed->Pre-initialized
ThaumicExploration{0.6.0} Thaumic Exploration Unloaded->Constructed->Errored
ThermalDynamics{1.7.10R1.0.0RC7} Thermal Dynamics Unloaded->Constructed->Pre-initialized
TiCTooltips{1.2.3} TiC Tooltips Unloaded->Constructed->Pre-initialized
TMechworks{0.2.13.96} Tinkers' Mechworks Unloaded->Constructed->Pre-initialized
taverns{2.2.1-0} Village Taverns Unloaded->Constructed->Pre-initialized
warpbook{1.1.40} Warp Book Unloaded->Constructed->Pre-initialized
weaponmod{v1.14.3} Balkon's WeaponMod Unloaded->Constructed->Pre-initialized
YALSM{2.1.3} Yet Another Leather Smelting Mod Unloaded->Constructed->Pre-initialized
McMultipart{1.1.0.314} Minecraft Multipart Plugin Unloaded->Constructed->Pre-initialized
HungerOverhaul{1.7.10-beta.5.jenkins47} Hunger Overhaul Unloaded->Constructed->Pre-initialized
ForgeMicroblock{1.1.0.314} Forge Microblocks Unloaded->Constructed->Pre-initialized
OpenModsLib crash transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:ENABLED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
AE2 Version: stable rv1-stable-1 for Forge 10.13.0.1187
CoFHCore: -[1.7.10]3.0.0RC7-211
ThermalFoundation: -[1.7.10]1.0.0RC7-62
ThermalExpansion: -[1.7.10]4.0.0RC7-141
Mantle Environment: Environment healthy.
MineFactoryReloaded: -[1.7.10]2.8.0RC8-86
TConstruct Environment: Environment healthy.
RedstoneArsenal: -[1.7.10]1.1.0RC7-65
NetherOres: Lacking version information.
ThermalDynamics: -[1.7.10]1.0.0RC7-98
Stencil buffer state: Function set: ARB, pool: internal, bits: 8

**Comment by nekosune** [comment]
You are using the wrong version, you need the one that DOES NOT have -dev at the end, that is for other developers, not users

**Comment by Megachuggayoshi** [comment]
....I should have known that, Thanks : )

**Comment by nekosune** [comment]
No trouble, sorry for the poke here,

**Comment by Megachuggayoshi** [comment]
ok now my head hurts from confusion I Put  the  not  dev jar file in the  mods folder and launched minecraft and it kinda didnt work? it didnt crash it just doesnt show any of the content

**Comment by nekosune** [comment]
Need to know that crash then as it will be different

**Comment by Megachuggayoshi** [comment]
![screen shot 2015-03-29 at 8 37 27 pm](https://cloud.githubusercontent.com/assets/10993521/6889081/f7f93c4e-d653-11e4-9631-8c071c677e08.png)



See it is in the mods folder but the mods content doesnt show up in the game

**Comment by nekosune** [comment]
You have Thaumic Exploration, Not Thaumic Tinkerer

**Comment by nekosune** [comment]
This is the github for Thaumic TInkerer, not Thaumic Exploration,

**Comment by Megachuggayoshi** [comment]
....ou dont know how embarraed I am right know....But I maust say pretty good job at figuring out some of my issues >.<

**Comment by Megachuggayoshi** [comment]
*you
*must

**Comment by nekosune** [comment]
You had the right person at least! https://github.com/nekosune/Thaumic_Exploration/issues

**Comment by Megachuggayoshi** [comment]
So...I just figured out you need TT for thaumic exploration ....is it mentioned clearly any where on the fourms, if so I am a derp, if not maybe it should be

**Comment by nekosune** [comment]
Please post logs on the TX issue tracker as it shouldn't 



—
