### ISSUE TITLE
Bedrock dimension missing ores

### ISSUE THREAD

**Issue by bookerthegeek** [Thaumic-Tinkerer/ThaumicTinkerer#709]
Just an idea, don't know if I missed it somewhere but here it is anyways :)
1. What I can tell:
   - Bedrock dimension spawns massive veins of almost every ore
   - Their is a blacklist if you do not want certain ores to spawn in it. (thank you btw)
2. What I'm missing:
   - What to do if an ore is not spawning, 
   - How to add it so that it will.
3. How to solve:
   - Add a config option to force the spawning of other ores in this dimension.
   - Some other hopefully super simple server side patch we can add to get the ore to spawn.

Thank you for taking the time to read.

**Comment by AnAverageHuman** [comment]
Last time I checked, ores don't generate there; they only start to appear when you mine bedrock with the Awakened Ichorium Pickaxe.

**Comment by bookerthegeek** [comment]
Ok. Please consider the first post suitable modified to request the ability to add ores to the list of ores that appear wheb you start to mine.
