### ISSUE TITLE
[Feature] KAMI void protection

### ISSUE THREAD

**Issue by MajorCooke** [Thaumic-Tinkerer/ThaumicTinkerer#711]
A couple of mods are starting to use void damage, and they're inserting armor that are more protective against mobs that actually deal void damage themselves, i.e. draconic evolution.

Considering it's easier to get their super armor which is on par with kami, I think that's a little unfair due to the amount of work one had to go through to get KAMI armor.

http://www.tolkiencraft.com/draconic-evolution/

**Comment by skizzerz** [comment]
Correction: Draconic Evolution doesn't actually deal void damage (assuming you're talking about the Chaos Guardians), it deals a new source of damage added by that mod called "Chaos Damage," which specifies that it should ignore armor and is unblockable. That mod then decides to disregard said restrictions and has its armor reduce it anyway. Any armor that correctly doesn't reduce damage that is not supposed to be reduced by armor won't actually help against the Chaos Guardian.

That said, void protection would be nice for those times where you fall into it for whatever reason :)

**Comment by MajorCooke** [comment]
Fair enough but yes, I do think KAMI can extend to protecting from it.

**Comment by MajorCooke** [comment]
So was this fixed?

**Comment by nekosune** [comment]
I will be remaking Kami armor as i recreate the mod for 1.12. This was marked down as one of the requirements for ichor armour
