### ISSUE TITLE
Crash server on config, where 

### ISSUE THREAD

**Issue by ShadowT1me** [Thaumic-Tinkerer/ThaumicTinkerer#713]
Then you make such option B:imbuedFire.enabled=false ( default is true ) than if you make research of imbuedFire and you will get crash ( link is down ). In version 461 all was okey.. In crash i am simple disconnecting from the server, client dont crash.

crash-log - http://pastebin.com/8H7LNx2V
Thaum Tinkerer - 479 version
Forge - 1291
Thaum Craft - 4.2.3.5

**Comment by Shadow232** [comment]
in versiona 481 problem fixed.

**Comment by Yorkforce** [comment]
This is still occurring in version 493
