### ISSUE TITLE
Items getting consumed when crafting

### ISSUE THREAD

**Issue by JasonMcRay** [Thaumic-Tinkerer/ThaumicTinkerer#714]
Since build 475 there is a big bug with certain items. All the items which are used in crafting and they returns the item back, but slightly damaged, are getting completely consumed.

Issue can be replicated 100% time for example with Etheric Sword from Extra Utilities. Normaly that sword when used in crafting will give player a Soul Fragment and it will lower the durability of the sword. With Thaumic Tinkerer build 475+ it will give player a Soul Fragment, but it will destroy the sword.

It also affect most of GregTech tools

This is only happening with Thaumic Tinkerer 475+ installed.

Tested on forge: 1291

**Comment by nekosune** [comment]
Looks like this is a sideffect of a fix did to stop a dupe, will look into it but tbh a hole bug is beter then a dupe, so will leave in effect until i find something that fixes both sides

**Comment by JasonMcRay** [comment]
Ok I guess I will downgrage to 474, because some of the players are bit "ragy" about this

**Comment by nekosune** [comment]
I am not saying I wont fix, just that I wont remove the dupe bug fix because of this in the meantime

**Comment by JasonMcRay** [comment]
Yea sure... What I meant I will downgrade to 474 for the time being :)

**Comment by JasonMcRay** [comment]
Actually looking at the changelog, wasnt the dupe bug fixed in 474?

**Comment by nekosune** [comment]
No, 475 was the fix

**Comment by nekosune** [comment]
This SHOULD fix it, looking at my fix I spotted a mistake I missed, where it thought ANY item was the spell cloth

**Comment by JasonMcRay** [comment]
Ok.. I see you are building it on Jenkins... Will try it right away

**Comment by JasonMcRay** [comment]
Ok... This issue is solved in 480. And also the spellcloth thing is fixed as well... Thank you very much for quick fix on this @nekosune
