### ISSUE TITLE
Add option to disable ImbuedFire usage

### ISSUE THREAD

**Issue by SirWilli** [Thaumic-Tinkerer/ThaumicTinkerer#715]
hey,
it would be great to have a option which allows to disable the usage of imbued fire. At the moment there are already 2 config options which removes the imbued fire completly but it causes issues with the reasearch and creates client crashes if the client doesn't have it disabled too.

**Comment by nekosune** [comment]
There will always be crashes or errors if the client does not share the same config.

**Comment by SirWilli** [comment]
Seems that I had read the code for an hour to find out how to disable the fire spread.

**Comment by nekosune** [comment]
disabling firespread is a vanilla option in /gamerules
