### ISSUE TITLE
[481]Fire doesn't 'harm/heal' with KAMI

### ISSUE THREAD

**Issue by MajorCooke** [Thaumic-Tinkerer/ThaumicTinkerer#717]
The pants, thanks to the fire resistance buff, cause lava to no longer heal because the player can't take fire damage, so the biggest point to the awakened leggings is completely muted.

**Comment by AnAverageHuman** [comment]
I never noticed that it heals you while in lava, even though that is described in the Thauminomicon. I do notice that the helmet gives blindness when you go head-deep in lava though.

**Comment by MajorCooke** [comment]
Exactly.
