### ISSUE TITLE
dupe

### ISSUE THREAD

**Issue by MrHelp** [Thaumic-Tinkerer/ThaumicTinkerer#721]
http://www.youtube.com/watch?v=Ru5UfK2tGxI

**Comment by nekosune** [comment]
What would help more, then a video in a language I don't speak that dosnt seem to show any duping, is version numbers, and reproduction steps

**Comment by MrHelp** [comment]
https://github.com/Azanor/thaumcraft/issues/1724

**Comment by nekosune** [comment]
That does not contain either version numbers, OR actualy any understandable steps on how to reproduce, still the same ununderstandable video for anyone who does not speak russian.

**Comment by MrHelp** [comment]
It is last version ThaumicTinkerer and thaumcraft 4.2.5

**Comment by nekosune** [comment]
The video was two weeks ago, there has been a version since then. and AGAIN steps to reproduce this, because again I do NOT speak russian, and watching it,  without speaking russian I can not see any dupe
