### ISSUE TITLE
Crash On Game Startup

### ISSUE THREAD

**Issue by MtnDrew** [Thaumic-Tinkerer/ThaumicTinkerer#722]
I do have everything installed that this mod requires to run but my game crashes if I try to use your mod.I'm thinking this might be a compatibility issue, I do have a lot of mods installed. Here's the crash report. http://pastebin.com/K5mpFxML I'd love to use this mod, so any insight on what I could do to get it working would be greatly appreciated.

**Comment by pixlepix** [comment]
Enchantment id issue. Change the conflicting enchantment id in either TT or better storage.

(Also, I really need to unsub from email notification)

**Comment by MtnDrew** [comment]
Thank you very much! It's all fixed now.
