### ISSUE TITLE
Config options for Leggings of Burning Mantle

### ISSUE THREAD

**Issue by duhadventure** [Thaumic-Tinkerer/ThaumicTinkerer#723]
Can you add a config option to turn off lighting and healing?
(I know you can turn off lighting by shifting I mean disabling it completely as it causes lag)

**Comment by Brycey92** [comment]
I second this!

**Comment by Adkkid** [comment]
I know this is old and all, but I third this! Disabling all the effects of the armor piece is a pretty big inconvenience, and banning it outright is the only way to guarantee server users won't lag the server or other people.
