### ISSUE TITLE
Breaking bedrock in overworld

### ISSUE THREAD

**Issue by FlkSrvr** [Thaumic-Tinkerer/ThaumicTinkerer#725]
If you mine a bedrock in the overworld (near the bottom layers) it will open a portal, if on square mode it will also break the surrounding bedrock and drop as an item.

**Comment by katzenpapst** [comment]
Not sure about dropping it as item, but I just noticed that using line mode straight down on y=3 or so will break all the bedrock down to the void. Seems to work in the bedrock dimension as well, I just accidentally went on top of it (aka y > 256)
