### ISSUE TITLE
Cursed Spirit's Blade Essentia Harvesting vs Forbidden Magic

### ISSUE THREAD

**Issue by katzenpapst** [Thaumic-Tinkerer/ThaumicTinkerer#727]
It seems the blade does not consider the aspects added/changed by FM (or other mods?) when in essentia harvesting mode. For example, Pigs are being displayed as having Terra, Bestia, Gula, hitting them yields Terra, Bestia, Iter. Creepers are displayed as Herba, Ignis, Ira, and yield Bestia, Praecantatio, Alienis. Seems to me that it doesn't consider the aspects a mob actually has, instead being hardcoded

**Comment by nekosune** [comment]
It cant be changed thanks to the fact we can only use a small subset of available aspects. We never claim to balanece around other mods, only vanilla thaumcraft

**Comment by pixlepix** [comment]
To expand on this answer: The aspects were carefully balanced so that every aspect would have multiple sources.
