### ISSUE TITLE
Ichor Infusion only yields one Ichor

### ISSUE THREAD

**Issue by DJLowrider** [Thaumic-Tinkerer/ThaumicTinkerer#732]
The first time we did an Ichor infusion on our server it yielded the 8 that the Thaumonomicon says it's supposed to, but subsequent attempts (when they haven't gone utterly haywire) have only yielded one per Infusion.  Is this intentional, or are we somehow getting screwed out of Ichor?

**Comment by Pirschjager84** [comment]
Any progress on this? I've experienced this several times on a server I'm currently playing on.
Of note, I'm using the Infusion Core (replacement for center pedestal of infusion altar from Thaumic Infusion - v3.966).  All other recipes seem fine.
ThaumicTinkerer-2.5-1.7.10-164

**Comment by Pirschjager84** [comment]
@nekosune Why was this closed? Was it fixed?

This is a very frustrating bug, as it's directly tied to the tech progression of the mod.

**Comment by nekosune** [comment]
Hi there, I am currently re-writing things for 1.12, this is one of the things that is not re-implemented yet

**Comment by Pirschjager84** [comment]
Ah, ok. Thanks for the info!

Some work friends and I are actually just getting started with a 1.12
server today and included the updated pack, so we'll see how it goes.

Thanks for taking on the project and keeping it alive!
Good luck to ya :)
