### ISSUE TITLE
Awakened Ichorium Pickaxe Area of Effect ability causing TE blocks to loose damage value information.

### ISSUE THREAD

**Issue by TheDarkVoid** [Thaumic-Tinkerer/ThaumicTinkerer#735]
When using the awakened ichorium pickaxe in line or square mode and it indirectly breaks a block from Thermal Expansion it will cause the block to loose it's damage value and become the item at the base block id. In the case of Portable tanks, energy cells and strong boxes it causes a creative version of those blocks to drop since the creative one has the base block id. This might be some conflict with how the pickaxe does area block breaking revealing an issue with how TE handles broken blocks. I have tested and it does not seen to affect blocks from other mods.

**Comment by yrsegal** [comment]
fixed in recent versions of Thermal Expansion.
