### ISSUE TITLE
Transvector Dislocator and Ender IO machines cause dupes, blacklist for dislocateable blocks?

### ISSUE THREAD

**Issue by Fusty** [Thaumic-Tinkerer/ThaumicTinkerer#736]
Hello,

I ran across this issue (VERY low priority) and wanted to make you aware.  I bet the actual issue is with how EnderIO deals with vanishing blocks (seems to pop the block's entity form when dislocated).  However, it would be very nice if there was a blacklist for blocks that the dislocator would not be able to move.

Just an idea!  Feel free to close this if you'd rather not deal with it (because as I said, the root issue is how EnderIO deals with vanishing machines).

**Comment by nekosune** [comment]
We use ThaumcraftApi.portableHoleBlackList to tell if we should dislocate a block or not.
