### ISSUE TITLE
Ichor armor blocks unblockable damage

### ISSUE THREAD

**Issue by mDiyo** [Thaumic-Tinkerer/ThaumicTinkerer#739]
Ichorcloth (and its improved versions) armor block all incoming damage regardless of the source. Fall damage, piercing damage, explosions, everything gets blocked where it goes right through everything else.

**Comment by Dayyer1** [comment]
I'd like to think that this is not a problem but I get why it would be...

**Comment by mDiyo** [comment]
For this particular armor, it might not be a problem. I'd like to make sure it was not an oversight anyway.

How to replicate: Put on any Ichorcloth armor, find a cliff, and jump off. The armor will block fall damage. This is true of TNT blasts and void damage and any other kind of damage the game usually treats as unblockable. Test with diamond armor for comparison.
