### ISSUE TITLE
Feature Request - Disabling spawner pickup

### ISSUE THREAD

**Issue by raum266** [Thaumic-Tinkerer/ThaumicTinkerer#740]
I see there was a request for this 2 years ago (almost exactly) and it was closed shortly after with no response ... Is there no way to disable picking up spawners with the Focus of Dislocation? I'd really hate to stop using an entire mod because of 1 exceedingly OP item.

**Comment by Blue64** [comment]
You could disable the item… (now you have a response! Lol)

**Comment by raum266** [comment]
That'd be a great answer if there was an option to disable anything other than the Tome of Research. We've stopped using the mod, however - Can't have people running around with super OP items and no way to disable them.

**Comment by Blue64** [comment]
If I'm not mistaken, [```MineTweaker```](http://minetweaker3.powerofbytes.com) Mod combined with [```ModTweaker```](http://minecraft.curseforge.com/mc-mods/220954-modtweaker) Mod might let you [disable the recipe](http://minetweaker3.powerofbytes.com/wiki/ModTweaker:Thaumcraft_4_Support) for the Focus of Dislocation. Then you just gotta make sure nobody cheats it in. If it would allow you to disable the recipe, it'd do it via the ```MineTweaker```/```ModTweaker``` scripts.

**Comment by Blue64** [comment]
Worst comes to worst, overwrite the item's recipe with something else, like dirt lol
