### ISSUE TITLE
Protoclay always swaps to the Awakened Ichorium Pickaxe 

### ISSUE THREAD

**Issue by hbwh19** [Thaumic-Tinkerer/ThaumicTinkerer#743]
I have used Thaumic Tinkerer many times befor and I am familiar how it works but for some reason in build 164 (Latest release then I am writing this).

The Protoclay always swaps to the Awakened Ichorium Pickaxe regardless of what I am trying to dig up.

**Comment by Zsashas** [comment]
What other tools do you have in your hotbar? If I recall correctly, it only switches between Awakened Ichcorium tools. So if the Pick is the only AI tool you have, then it will select that. If you do indeed have other AI tools, then never mind.

**Comment by VicenteRD** [comment]
Can confirm, with all 3 Awakened Ichorium tools in my inventory, it will always go for the pickaxe.
FTB Infinity 1.6.2, TTinkerer 2.5-502

**Comment by Sakata-MC** [comment]
Having same issue in FTB infinity 1.8.2
ThaumicTinkerer-2.5-1.7.10-502

**Comment by vonbaronhans** [comment]
Same problem in FTB Infinity Evolved 2.3.5
Thaumic Tinkerer 2.5-1.7.10-512
Anybody found a fix yet?
