### ISSUE TITLE
thaumic tinkerer enchanter table crash

### ISSUE THREAD

**Issue by oks1998** [Thaumic-Tinkerer/ThaumicTinkerer#747]
http://pastebin.com/LGdiZE6q
http://pastebin.com/2zZSivRX

when i shift wand to the table, it crash
i also report this issue to thaumcraft Author

**Comment by nekosune** [comment]
please do NOT report bugs with OLD versions of thaumic tinkerer

**Comment by oks1998** [comment]
older version?
my version is ThaumicTinkerer-2.5-1.7.10-164.jar !
if got latest version where to download it?

**Comment by nekosune** [comment]
@oks1998  Your problem is solved in 164 and if you use the copy from the jenkins, the bedrock dimension problem is solved http://jenkins.nekokittygames.com:8080/job/Thaumic%20Tinkerer/503/

**Comment by oks1998** [comment]
thank you because I don't know that is jenkin for thaumic tinkerer, thanks~
