### ISSUE TITLE
Bedrock mining bug.

### ISSUE THREAD

**Issue by Meegooo** [Thaumic-Tinkerer/ThaumicTinkerer#748]
It's basically #719 and #730 issues, nothing new.
But it exists again. Using build 503, forge 1420 and lastest thaumcraft, i'm still able to collect bedrock like in issue 730 and square/line modes don't work in bedrock dimension like in issue 719

**Comment by nekosune** [comment]
This has been tested as working, unless you can provide evidence otherwise.

**Comment by Meegooo** [comment]
Ok, I'm going to record it when I come back home.

**Comment by nekosune** [comment]
Seeing as we have had people record an old version before, please include the version being used in recording.

**Comment by Meegooo** [comment]
So i just came home.
Currently i'm using build 503 and forge 1420.
Before update i used 481 and forge 1307 and bug wasn't here.

Going to test different builds now.

**Comment by Meegooo** [comment]
So, i just tested it.
It's build 503 that broke everything. On build 502 bedrock breaks as it should. On build 503 it's not.

**Comment by nekosune** [comment]
Build 503 https://github.com/Thaumic-Tinkerer/ThaumicTinkerer/commit/f6f37173bfecc7696b5850d02ca08b3f30040147 it didnt even touch any of the code to do with the block breaking, I would try redownloading the jar

**Comment by Meegooo** [comment]
I already did.
Also it says that there're some slabs missing.

**Comment by nekosune** [comment]
Can I have log about that?

**Comment by Meegooo** [comment]
Just the log with build 503?https://gist.github.com/Meegooo/4e9e5dcac1510e480060
Also i recorded a video. https://www.youtube.com/watch?v=gA2ht8TZ53M
It's still uploading. Should be there in like 5 minutes

**Comment by Meegooo** [comment]
Ah, okay then, thanks.
BTW, If it was the wrong bransh then build 504 is broken too.

**Comment by Meegooo** [comment]
Wait, 505 is master branch too.
Maybe Jenkins broke?
