### ISSUE TITLE
Pawing slab/stairs missing after Version 2.5.494

### ISSUE THREAD

**Issue by Dream-Master** [Thaumic-Tinkerer/ThaumicTinkerer#750]
Testet with Version 504.

**Comment by Dream-Master** [comment]
Add 494 back.

**Comment by Dream-Master** [comment]
? no comment ?

**Comment by nekosune** [comment]
Try looking at latest before reopening issues

**Comment by Dream-Master** [comment]
Ok sorry didn't see you implement it on 506 again because the change log are empty. Thanks
