### ISSUE TITLE
Suggestion: New Explosives

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [Thaumic-Tinkerer/ThaumicTinkerer#753]
Almost every techmod, magicmod, whathaveyoumod add new items, blocks, tools, etc. but strangely almost none of them add any new explosives to the game.

I kinda want to have more choices besides TNT. Bigger, smaller, better, different, anything, really :).

New kaboom is gud!

**Comment by Zsashas** [comment]
Ender IO adds several types or explosives (or is it Ender Zoo?) Also, Mekanism has Obsidian TnT which is rather powerful, and Thaumic Horizons has Alchemite, which is...different..
