### ISSUE TITLE
TT 2.3-140 for MC1.6.4 Never Showing any Ichor Research

### ISSUE THREAD

**Issue by redxpen** [Thaumic-Tinkerer/ThaumicTinkerer#755]
I've been driving myself mad trying to unlock Ichor research, and after much trial and error i've found that something about my setup means i don't get to see it.  i'm not running mods like computercraft (crashes me) or compycraft peripherals or anything which i see is very integrated to TT.  the ichor and all the stuff you make with it is available to me in NEI and Creative/Sandbox mode but otherwise it does not exist in my thaumonomicon. 

if this sounds confusing, i promise the answer isn't as simple as doing the matrix research or anything.  i'm all out of things to research (100% entirely researched everything, i swear. even all the different wands and staffs) and it's not there.  i've seen screen shots of other people's thaumonomicon and mine never has the ichor next to the "tome of knowledge sharing" no matter what i do.

**Comment by redxpen** [comment]
![untitled](https://cloud.githubusercontent.com/assets/12863925/8138277/5e66a32e-1117-11e5-9539-a8578bb5c23a.png)

this is what it looks like after doing all the researches in half of the tabs and just after finishing the infusion matrix research.  the ichor never shows up even when you go all the way to the end of researching everything

**Comment by TheMadmanofChaos** [comment]
You only unlock Ichor once all other researches from Thaumcraft,  Thaumic tinkerer, and any add on that loads before it is complete. Everything,  from golems to alchemy, must be unlocked before ichor is even visible.

Ichor is designed to be the last thing you unlock, since it is far better then everything.

**Comment by redxpen** [comment]
That pic was after I reinstalled everything and went back to default textures.  I did every single research my first time 100%, in survival mode, including the golems hats and every stupid staff core.  Its gotta be because I don't use computercraft or peripherals right?

**Comment by redxpen** [comment]
ok so i've reinstalled twice now and tried to find the ichor research 3 times with the same results.  In survival mode single player using NEI and addons to cheat my way through the whole book (78 or 80 research papers plus the researches you can buy outright).  Here's the proof, and which mods i'm running.  so if your setup is like mine concerning thaumcraft then you'll probably get the same annoying bug.

![no_ichor1](https://cloud.githubusercontent.com/assets/12863925/8152455/22911ffc-12eb-11e5-91dc-26024bbc7073.jpg)
![no_ichor2](https://cloud.githubusercontent.com/assets/12863925/8152457/2616d392-12eb-11e5-9b5b-b34dc8d989b6.jpg)
![no_ichor3](https://cloud.githubusercontent.com/assets/12863925/8152462/2a3cc468-12eb-11e5-8bba-2888ae88e6dc.jpg)

**Comment by TheMadmanofChaos** [comment]
There should be a chat command "/ISKAMIUNLOCKED", or something to this effect(Use the /help command to find it if this does not work). What this does is simple: It will tell you if KAMI is available(And KAMI is the subsection of Thaumic tinkerer with ichor), and if it isn't then it will list off all missing researches. I am almost certain this command was available back in 1.6.4.

**Comment by redxpen** [comment]
ok, the command /iskamiunlocked was available and it responded "Yes", but i still don't have any ichor.  it appears to be the only thing that i don't have, which leads me to believe that with the mods i'm using, it expects me to complete more research before unlocking it. 

at the same time i'm struggling to get a framerate of more than 20fps, so it seems that i'm going to have to quit playing minecraft anyway.  getting a very spotty 15-20fps on 8gb of ram and 2.3ghz of processing power is totally unacceptable to me.  i used to get more steady gameplay when i had 4gb of ram than after i upgraded (replaced two 2gig for two 4gig)

**Comment by Zsashas** [comment]
I thought that the Ichor research appeared way off to the bottom-right of the page? Past the enchantments section.

**Comment by redxpen** [comment]
No, to the bottom right of the enchantments' section is that little info tab about nether shards, the green and red one.  nothing else there.  i've seen in some random youtubers "let's play" that the ichor is just beside the book of knowledge sharing and helmet of revealing.  dead center pretty much
