### ISSUE TITLE
Legs of Burning Mantle disabling light

### ISSUE THREAD

**Issue by Grygon** [Thaumic-Tinkerer/ThaumicTinkerer#757]
Disabling the light feature of legs of the burning mantle by shift-right clicking as specified in the Thaumonomicon also disables the fire resistance effects of the legs. If this is intended behavior it should be reflected in the Thaumonomicon, if not then it should be fixed--keeping the documented behavior would be nice, as it allows players to disable the potentially laggy light-spreading feature while retaining the defensive advantages.

Using version ThaumicTinkerer-2.5-1.7.10-489

**Comment by nekosune** [comment]
Shift right clciking the armor removes all the special features of said
armor

**Comment by Grygon** [comment]
The entry in the thaumonomicon should be changed then to reflect that--it currently reads as if you can just disable the light source by shift-right clicking.
Like I said before though, it would be nice to have a way of just turning off the light source, as it makes both the client and server lag, but the fire resistance part of the legs is very nice.
