### ISSUE TITLE
Unable to craft the wand experience core

### ISSUE THREAD

**Issue by oks1998** [Thaumic-Tinkerer/ThaumicTinkerer#758]
When I prepared all the materials that needed for the infusion altar to craft wand experience core, I already double chek no wrong in the recipe that I prepared but when I right click using wand to craft this item, it is unable to start the infusion I don't know what wrong to my prepared...or this is a bug?

**Comment by Zsashas** [comment]
Screenshots help. Also (since I can't remember the recipe right now) are there any items that have durability, and if so, are you using fresh items or used and repaired ones?

**Comment by oks1998** [comment]
all item is fresh crafted and no loss in durability and no enchantment on it,
later i post the screenshot for you
