### ISSUE TITLE
Imbued Fire in the Nether is far too aggressive, causing major performance issues

### ISSUE THREAD

**Issue by Odysseius** [Thaumic-Tinkerer/ThaumicTinkerer#759]
http://puu.sh/iDnSD/d98e8cefe1.png
http://puu.sh/iDnVa/17d47d3081.png
http://puu.sh/iDnVJ/47af6a6818.png

This just happened within a few minutes, the TPS went down to around 5 while the area was loaded (on a server beast), the spreading does not seem to stop. This mostly happened because the feature doesn't seem to be documented very well at the moment (not intended to be rude, also might be fixed already). There are multiple things that could be done:
- Move that stuff to Kami. Anything that does stuff like that is op, and op stuff belongs to Kami.
- Possibility to disable it on the server without having it to disable on the server. Probably impossible, I'm not a coder so I have no idea.
- Lower the effect. To be honest, this is kinda ridiculous, and destroys worlds and servers.

TT version: 2.5-502 on FTB Infinity 1.6.2

**Comment by Dream-Master** [comment]
With Modtweaker you can move the research and add or delete a recipe in the Thaumcraft Book.

**Comment by Zsashas** [comment]
Moving the Elemental Flames to KAMI would definitely be the best route.

**Comment by Blue64** [comment]
2 questions:
1. Do you always have MystCraft Instability in your Nether? (Picture 2)
2. How do I make this flame? I heard lots of bad things about it, and I want to see what I can do to it lol

**Comment by Zsashas** [comment]
I don't see any mystcraft instability in that pic. Did you mean decay? I see glowshrooms though.

**Comment by Blue64** [comment]
Yeah, the decay.
