### ISSUE TITLE
Talisman of Nourishment incompatible with Hunger Overhaul

### ISSUE THREAD

**Issue by netzgeist** [Thaumic-Tinkerer/ThaumicTinkerer#760]
Porting this issue as its still relevant.

https://github.com/Flaxbeard/Thaumic_Exploration/issues/34

Tested a subset of just these 2 mods along with latest forge, can reproduce.

**Comment by nekosune** [comment]
This is not the correct place to put an issue for the other mod. The talisman is ported  for the 1.8 version only, of which hunger overhaul does not exist yet, so there is no way to 'test' whether it works or not on this version yet, please do not drag issues onto unrelated mods

**Comment by netzgeist** [comment]
Can you guide me to the correct place then? Im playing 1.7.1.0 TT and as this is pretty much ModdedMC, I thought you may find it useful to know.

**Comment by nekosune** [comment]
The talisman is in Thaumic Exploration, a different mod, one that is also on the last version before 1.8 so is not doing anything except major bug fixes, of which mod compatibility is not

**Comment by nekosune** [comment]
Basically, the talisman works with the normal values of food, the fact that hunger overhaul breaks how food works in that you can't get those values, means that the talisman part would need special coding JUST for Hunger Overhaul

**Comment by netzgeist** [comment]
Unsatisfying from users side of view but obviously not your fault. Thanks for the explanation and sorry for messing up the tracker i guess.

**Comment by nekosune** [comment]
It is something I will make sure works for 1.8 and if I find a crash bug that requires me to put another 1.7.10 version of Thaumic Exploration out, I may try and fix this one too, but i really need to put my focus into the 1.8 upgrade

**Comment by nekosune** [comment]
Made a fixed verson for any mod that uses AppleCore like Hunger overhaul 
http://jenkins.nekokittygames.com:8080/job/Thaumic%20Explorer/

**Comment by netzgeist** [comment]
Ehm wow, I didn't expect this. This is huge for me as needed a lategame solution for a heavy hunger orientated pack. Thanks. a. lot!

**Comment by nekosune** [comment]
Turns out it was the well fed effect that was causing most of the issues, For obvious reasons the talisman does not eat anything that causes potion effects, so made it ignore that specific one. then I just had to use applecore api to grab the altered food values instead of the vanilla

**Comment by bookerthegeek** [comment]
@nekosune can we drop this server side only or would clients also need to update?

**Comment by nekosune** [comment]
@bookerthegeek It would need to be both sides sorry

**Comment by bookerthegeek** [comment]
Sad, but thank you. I'll go poke some mod pack authors then.
