### ISSUE TITLE
Can't rune armor

### ISSUE THREAD

**Issue by estradus** [Thaumic-Tinkerer/ThaumicTinkerer#763]
I was trying to enhance my Ichorium robes with the runic shields infusion, but the infusion won't start. It won't work on the helmet of revealing, either. The thauminomicon says that it can be applied to any "magically stable" materials, but this doesn't seem to extend to any other thaumic equipment added by other mods, so I'm not sure if the API doesn't cover it (which would be odd) or if its just that noone thought to include whatever hook is necessary on their armors (which is just upsetting to me, as I really like the runic shielding). I really hope this can be resolved, as I'm not sure the boost in protection granted by the upgrade to ichorcloth will outweigh my old void armor with the runes, and with my world I'm prone to horrible death enough as it is.

**Comment by duhadventure** [comment]
It is not implemented in the mod.
