### ISSUE TITLE
Dynamism Tablet and Infusion Altar

### ISSUE THREAD

**Issue by CaptiveCreeper** [Thaumic-Tinkerer/ThaumicTinkerer#766]
I have seen a video on youtube from 2014 were the dynamism tablet starts the infusion altar instead of a play.  However when i try to do this is does not work.  Any help would be appreciated.

**Comment by belathus** [comment]
I had this working in my base just a few versions ago. I just tried it the other day (same setup as before with zero changes) and it didn't work.

I actually started the infusion manually after giving up with the dynamism tablet and the matrix exploded a few seconds later.
