### ISSUE TITLE
Transvector interface not accepting RF power in 1.7-final branch

### ISSUE THREAD

**Issue by Daedalus11069** [Thaumic-Tinkerer/ThaumicTinkerer#771]
This still appears to be broken, at least on my end.  Tried with Thermal Dynamics fluxducts as well as enderio conduits, and rednet cables.  All failed to work.
![2015-08-03_16 45 48](https://cloud.githubusercontent.com/assets/1094363/9050135/3b36533e-39ff-11e5-823c-5e5b03d7b825.png)

Given I don't see any commits that reference any further fixes for this issue(I'm on 507 of 1.7-final), I'm guessing something changed.  If it matters at all, I'm using the 1.5.0 Direwolf20 modpack from ftb, which of course currently uses Thermal Expansion 4/Thermal Dynamics/etc.  I'm not sure what other mods could cause this to fail.. though curiously, fluids from Thermal Dynamics still work.

**Comment by koalalord9999** [comment]
Are you linking the transvector to the pipe you want to send power to? If not, try that. Once you link a transvector to an RF source, it will take a few seconds, then recognize that it's allowed to accept and send RF, thus making connections happen. I do, however, see you have Extra Utilities possibly connected to the bottom or side of the transvector, is that where the power is coming from? Or is that where you're sending it to?

**Comment by Daedalus11069** [comment]
@koalalord9999 The pipe below the transvetor is actually an itemduct from Thermal Dynamics.  As to binding the TVI to a pipe, that works, though I'm attempting to bind it to an MFR auto-spawner, in which case the flux-duct(or any other power source) doesn't connect.

**Comment by ThunderBolt6** [comment]
same problem here, tried every conduit/pipe/energy block/generator
Binded Transvector interface to furnace, plugged to ti a RF conduit/energy block/generator/inc tesseract , it dont hcarge the machine

**Comment by ThunderBolt6** [comment]
for more info, exact problem for me, attach transvector to mfr spawner and the attach a rf conduit to transvector it doesnt attach.
Situatio that works transvector to a energy cell, attach another energy cell to  transevector, 1º energy cell is charging, works.
