### ISSUE TITLE
Bedrock dimension, bedrock not breaking.

### ISSUE THREAD

**Issue by PhoenixtheII** [Thaumic-Tinkerer/ThaumicTinkerer#776]
Using FTB Infinity 1.10.1
Thaumic Tinkerer 1.7.10 build 502

Reproduce:
1. Have full awakened ichorium robes.
   Boots are enchanted with haste III
   Awakened Ichorium Pickaxe enchanted with Efficiency V, Silk Touch I, Soulbound I, Fortune III (Yes, It gave me silk touch & fortune when enchanted by doing silk touch in osmotic enchanter, then enchant it trough auto enchanter from MFR)
2. Go to bedrock dimension
3. Set pickaxe to square mode.
4. Walk forward, while mining with the Awakened Ichorium Pickaxe.

Result:
Sometimes pickaxe only break the 1 block straight infront of you, leaving the 5x5 around it intact.
Funny side issue, sometimes the bedrock that is left over becomes unbreakable too.

Expected:

To be able to walk forward while mining and not get obstructed by bedrock that the pickaxe left behind.

**Comment by PhoenixtheII** [comment]
Screenshot of left over bedrock: 

https://www.dropbox.com/s/g1s47apblc7v9b8/Screenshot%202015-08-20%2021.01.24.png?dl=0

**Comment by Deadcerberus** [comment]
known issue with build 502, in build 505 its fixed

**Comment by PhoenixtheII** [comment]
Using build 512, Infinity expert 2.4.2 modpack, still not fixed...

**Comment by QVBA** [comment]
Still broken on 164 (latest 1.7.10 on curseforge).

**Comment by LincT** [comment]
If 1.7.10 is still being supported, I also encountered this. I tried using the pick both with and without enchantments. tried using only thaumcraft and thaumic tinkerer (and baubles) to try and limit the possibility of mod conflicts. tried with both creative spawned and crafted/infused awakened picks, tried while wearing no other gear. currently using ThaumicTinkerer-2.5-1.7.10-164
