### ISSUE TITLE
Transvector Interface request/issue

### ISSUE THREAD

**Issue by elbaslito** [Thaumic-Tinkerer/ThaumicTinkerer#777]
While making a frame quarry using RWTema's Funky Locomotion mod, I used the transvector interface to link the mining wells from buildcraft with power. They connected perfectly, but once I made the frame move the whole structure, they were no longer bound. I figured this is due to the fact that you have coded this through coordinate matching, so can you fix the issue, and I recommend matching with the block directly rather than coordinate matching. As when the mining wells moved they no longer were bound to the interface. Thanks in regards :)

**Comment by nekosune** [comment]
In minecraft you can't 'match to the block directly' As there is no unique ID for a block, the only way to ask for a certain block, unless the mod adds it's own registry, is through coordinates. A future version may, i it doesnt break other things, have them use relative coordinates however.
