### ISSUE TITLE
Essentia Funnel incompatible with other mods' Warded Jar substitutes

### ISSUE THREAD

**Issue by blaisen** [Thaumic-Tinkerer/ThaumicTinkerer#779]
I reported this to the Technomancy team thinking that their Quantum Jars were the issue; they looked into it and found that the funnel checks specifically for Thaumcraft's Warded Jars. Is there any way this could be fixed?

**Comment by nekosune** [comment]
It checks for them, and anything that inherits from them, it cant guess if a random block can also be used as a jar if it doesnt do that

**Comment by blaisen** [comment]
Here's the thread I opened on Technomancy's Github. 

https://github.com/theflogat/Technomancy/issues/145

Hopefully this can be resolved.

**Comment by nekosune** [comment]
Yeah looking into it, they made their own totally new jar that doesnt implement any thaumcraft class or interface, without deciding to code stuff specifically for Technomancy it is not easy for ANY mod to recognize that block as a jar

A lot of other mod's warded jar substitutes, DO inherit from Thaumcraft's warded jar for this reason
