### ISSUE TITLE
ThaumicTinkerer not work

### ISSUE THREAD

**Issue by EmberEdison** [Thaumic-Tinkerer/ThaumicTinkerer#781]
When I push add to minecraft the game not be crash, but the Tinkerer item and research not find.It look not work.

logout:
https://mega.nz/#!CIBWBKxD!i1XphnA0cHspY7i50in7rQUv3tB8unkVNoNOuPO2U2M

**Comment by Zsashas** [comment]
If it crashes, post the crash report.
