### ISSUE TITLE
Crash after taking "unnamed item"

### ISSUE THREAD

**Issue by avere001** [Thaumic-Tinkerer/ThaumicTinkerer#782]
Playing on the infinity modpack (1.10.1), I kept getting a weird glitch with my ae2 system. I found that there was an unusual item name "unamed item" in it. I tried taking it out and immediately crashed. I tried to log back into the server and crashed again. Here is the crash log

http://pastebin.com/GznQbg0w

**Comment by Zsashas** [comment]
What did the item look like?
