### ISSUE TITLE
Thaumic Tinkerer breaks Thaumic Energistics' CC integration

### ISSUE THREAD

**Issue by generilisk** [Thaumic-Tinkerer/ThaumicTinkerer#784]
Thaumic Tinkerer overwrites the Essentia Provider's provided API. The issue is also listed on Thaumic Energistics' github here:
https://github.com/Nividica/ThaumicEnergistics/issues/228

**Comment by nekosune** [comment]
Added a blacklist, will allow other mods to say "Dont try and Provide for this"
