### ISSUE TITLE
Server Crash upon Chunk Load

### ISSUE THREAD

**Issue by lafflam** [Thaumic-Tinkerer/ThaumicTinkerer#795]
On the official InfiTech2 Public Server, we recently had a problem where a Tablet of Necromancy appeared to be causing a server crash whenever the associated chunk was loaded.

Here is the crash report: http://pastebin.com/QHRgwcjn

That file was generated AFTER I had already tried deleting the ticking entity at 14354,82,15554 using NBTEdit.

In order to clear the problem, I had to edit /home/minecraft/McMyAdmin/Minecraft/config/forge.cfg to enable B:removeErroringTileEntities=true. Server crashing stopped after the Tablet disappeared, then I changed B:removeErroringTileEntities=true back to false.

**Comment by nekosune** [comment]
Can you provide which aspects were on pedastels nearby, and what was
intended to be summoned?

**Comment by lafflam** [comment]
According to the player on our server (Ligi):

ignis, praecantatio and volatus, to summon firebat

**Comment by nekosune** [comment]
were threre any other pedastels with anything else on nearby?

**Comment by Ligi89** [comment]
No, my infusion altar was pretty far away from the spawner room, and it didn't have any recipes going on at that time either.

**Comment by nekosune** [comment]
Okay thankyou :) that should be enough to try and reproduce easier

**Comment by JasonMcRay** [comment]
I would like to ask how is it looking with this issue? I am running through old issues of my modpack (cleaning fixed issues)
