### ISSUE TITLE
Issue with Robes of the Stratosphere in Multiplayer and Distortion Wand Focus

### ISSUE THREAD

**Issue by Wickedtemp** [Thaumic-Tinkerer/ThaumicTinkerer#796]
This is using Feed the Beast 1.4.8, I'm unsure which version of Thaumic Tinkerer this modpack uses. 

It seems the robes of the stratosphere don't work as intended when it comes to projectiles. Apparently it's supposed to work much like the distortion wand focus and, according to the description, allow 'simple' projectiles such as arrows, snowballs, and potions to go through your character. 

I don't know if it's just a multiplayer issue, but this doesn't work on the server. I tested this with the distortion wand focus and that doesn't work either.

**Comment by nekosune** [comment]
Would need to know in what way it doesnt work, and the version number, you can do that by looking inside mods/ folder and looiking at the file name

**Comment by Wickedtemp** [comment]
I looked at the name, I believe the version is 1.7.10. 

From what I understand in the thauminomicon entries, the wand focus and the robes of the stratosphere are supposed to allow projectiles like arrows to phase through you without inflicting damage. I attempted to use these items in a multiplayer server and was hit by the arrows every time. I had made sure the wand focus was draining from the wand. 

I don't know if this is a bug, maybe with the compatibility with multiplayer servers I've no clue since I don't understand code. This could also be an issue with lag, but I don't have a way to troubleshoot that at the moment and I figured filing this bug report would make the most progress in fixing this issue, or at least understand what's going on here.

**Comment by nekosune** [comment]
That is the minecraft version number, the full filename will help more
please

**Comment by Wickedtemp** [comment]
2.5-1.7.10-502 is the full file name.

**Comment by nekosune** [comment]
Thankyou will try and reproduce!

**Comment by Wickedtemp** [comment]
I recently tried a "Whirlwind Sigil" from the Bloodmagic: Alchemical Wizardry mod on the same server, and it deflects projectiles as intended. So it seems that the problem isn't caused by a laggy connection.
