### ISSUE TITLE
Ordo fire ore issues.

### ISSUE THREAD

**Issue by dominx** [Thaumic-Tinkerer/ThaumicTinkerer#799]
ThaumicTinkerer-2.5-1.7.10-502 (Infinity 1.10.1)

Had some fun with ordo imbued fire today. Great stuff! Seems a viable way of processing some ores.

Noticed some issues though:

All Thermal Foundation and Immersive Engineering ores smelt to copper.
All ProjectRed ores smelt to ruby.
All Biomes'o'plenty gem ores smelt to amethyst with in turn burns down to nothing.
Forestry ores don't burn.
Normal TiC ores don't burn, all gravel ores smelt to iron.
All dense ores smelt to iron.
Uranium doesn't burn though yellorium ore smelts to IC2 uranium blocks.
Railcraft dark ores don't burn. IIRC they are equivalent to normal ores.
Nether ores and railcraft poor ores don't burn but it's more of enhancement possibility than a bug.

There is some inconsistency in compressed dirt and cobble. Dirt burns down to compressed dirt which doesn't burn any further. Cobble burns twice to double compressed which burns down to nothing. I'm not complaining about it not smelting all the way to octuple though it would be fun and ridiculously cheap.

The fire also destroyed some blocks that shouldn't be affected if I understand it correctly. It made holes in my sandstone and chisel factory blocks kilns. I also destroyed BC filler IIRC. When replaced they got repeatedly destroyed again in the same places. Fire did not spread into the holes immediately. It happened a few times and I was unable to reproduce it. The test world got destroyed by other imbued fires.

**Comment by kutschkem** [comment]
Ars Magica Ores don't seem to work either (2.5-1.7.10-164), they can't be set on fire and don't produce blocks as expected.

**Comment by kutschkem** [comment]
regiomatches returns false when offset+length is more than the string's length. Which means the current code should fail for all ores/blocks with too short names.

**Comment by kutschkem** [comment]
Do you have a 1.7.10 branch for bugfixes in that version? For pull requests?
