### ISSUE TITLE
Strange version

### ISSUE THREAD

**Issue by Cbert** [Thaumic-Tinkerer/ThaumicTinkerer#800]
Question, Crundee Craft have version ThaumicTinkerer-2.5-1.7.10-493
https://www.dropbox.com/s/aifnurhumh9ojhp/ThaumicTinkerer-2.5-1.7.10-493.7z
I can’t find any info on “493“ version. Most resent version for 1.7.10 is ThaumicTinkerer-2.5-1.7.10-164 at minecraft.curseforge.com
Is there explanation?

**Comment by Zsashas** [comment]
I believe the version numbering is different for Curse and for other hosting sites used, although why this is, I have no idea. Those are most likely the same version.

**Comment by Cbert** [comment]
Actually there is difference.
![2015-11-16 01 09 46](https://cloud.githubusercontent.com/assets/9320867/11171705/ff8d2cde-8bfe-11e5-98e3-8e6517e6c983.png)

**Comment by justicesays** [comment]
That's the development branch, you can get the latest version of that at

http://jenkins.nekokittygames.com:8080/job/Thaumic%20Tinkerer/

There don't appear to be many release pushes to the CurseForge page, and the current version there in pretty old and has at least one nasty crash bug (Osmotic enchanter crashes world).

**Comment by Cbert** [comment]
justicesays, thank you.
