### ISSUE TITLE
Talisman of Remedium trying to purge Cleaver

### ISSUE THREAD

**Issue by deathglow** [Thaumic-Tinkerer/ThaumicTinkerer#803]
Every time I equip a cleaver from tinker's construct the talisman constantly goes off and will run its durability all the way down.  I thought maybe it was the material it was made of but I made one out of all iron and it still has same issue.

THAUMCRAFT-1.7.10-4.2.3.5
THAUMICTINKERER-2.5-1.7.10-507
TCONSTRUCT-1.7.10-1.8.5
IGUANATINKERTWEAKS-1.7.10-2.1.5

**Comment by nekosune** [comment]
this looks awkard, might have to add a hard coded in exception if cleaver is in hand.

**Comment by deathglow** [comment]
Agreed, it puts mining fatigue on you and that sounds like the only way to me.

**Comment by nekosune** [comment]
Might add an api that lets mods add / remove things from an excemption list for my 1.8 version, for now for the 1.7.10 I will just hard code in an excemption

**Comment by Zsashas** [comment]
This also happens with JABBA dollies if a chest is being carried, as it applies mining fatigue and slowness as well.

**Comment by Zsashas** [comment]
What if it only removed a potion effect if it had at least 5 seconds left in the duration? Most thigns that apply a constant effect (dollies, cleavers, etc) apply a continuous 0-second duration effect, so that should work. If it's possible, that is.
