### ISSUE TITLE
Game Crash on Piston Activation

### ISSUE THREAD

**Issue by Xraxis21** [Thaumic-Tinkerer/ThaumicTinkerer#804]
Whenever I activate a piston (Sticky or Not) the game crashes. I have gone as far as removing all mods from the mods folder except the ones that Thaumic Tinkerer requires to see if one of my other mods were causing it. It doesn't happen unless Thaumic Tinkerer is installed. I have also tried 3-4 different forge versions. Here is the link to the crash report - http://pastebin.com/vkjekU0S

**Comment by nekosune** [comment]
If it can be reproduced with only Thaumic Tinkerer, please give me the crash log from that. Not one with mods that specifically mention rendering.
When the crash is IN a rendering system

**Comment by Xraxis21** [comment]
I apologize. Here is the report with only Thaumic Tinkerer, Thaumcraft, and Code Chicken Core installed.  http://pastebin.com/ps1BWAKs

**Comment by nekosune** [comment]
Danke, will get right on investigating this

**Comment by nekosune** [comment]
Wow, that was a weird one.
