### ISSUE TITLE
Thaumic Tinkerer 2.5-1.7.10-513 Bugs

### ISSUE THREAD

**Issue by HaruDasom** [Thaumic-Tinkerer/ThaumicTinkerer#805]
Thaumcraft Version : 1.7.10-4.2.3.5
Thaumic Tinkerer Version : 2.5-1.7.10-513
1. All focus cannot be enchanted in the focal manipulator.
   (or only get an awkward enchant; for example, Treasure on the Dislocation foci)
2. All gears(Helmet of revealing, Ichorium robes, Upgraded Ichorium robes) don't accept runic shields.
   (Cannot perform a runic shielding augmentation infusion.)
3. Awakened Ichorium pickaxe breaks almost everything(include the Bedrock!) in square mode or line mode.
4. Talisman of remedium doesn't break at all. When its durability meets 0, it returns to 100, so we can use one talisman forever.
5. Talisman of remedium removes the effects of the infused potions.
6. Protoclay tries to exchange everything for ichorium pickaxe.

I have a awakened ichorium pickaxe, shovel, and axe in my inventory.
Pickaxe on a stone -> nothing happened
Pickaxe on a dirt -> nothing happened
Pickaxe on a wood -> nothing happened
Shovel on a stone -> change to the pickaxe
Shovel on a dirt -> change to the pickaxe
Shovel on a wood -> change to the pickaxe
axe on a stone -> change to the pickaxe
axe on a dirt -> change to the pickaxe
axe on a wood -> change to the pickaxe
1. Worldshaper's looking glass doesn't recognize a black hole ring in the baubles inventory.

**Comment by DavidDiack** [comment]
It breaks warded blocks too.
