### ISSUE TITLE
Compatability issue with Transvector and Thaumic Energistics {v ThaumicTinkerer-2.5-1.7.10-512}

### ISSUE THREAD

**Issue by koalalord9999** [Thaumic-Tinkerer/ThaumicTinkerer#806]
Video shows issue
https://youtu.be/hhakuNkikDw
I can't figure out how to make it pull from jars either.

**Comment by nekosune** [comment]
Not likely to happen unfortunatly, also you are misunderstanding how these work , they are not meant to work the same as the block linked to, so they don't become import busses if you link them to import busses, they are simply a way for automation to access the sides of the block, no more, no less. 

a better example would be if you had each of those going into a jar, and you put the Transvector against the import bus, and linked the transvector and the jar
