### ISSUE TITLE
Ichor research closed after being opened

### ISSUE THREAD

**Issue by Antillar** [Thaumic-Tinkerer/ThaumicTinkerer#807]
http://imgur.com/K2d0sD4
This is pretty much self-explanatory. How do I fix it?

**Comment by nekosune** [comment]
Did you add any new TC mods or mods that add stuff to TC? then you need to complete that research too

**Comment by Antillar** [comment]
Better late then never.

I did not add anything new. It is FTB Infinity pack, and I dont change anything in it. I have done all the research in one version, so updates of the modpack could not cause this problem.

**Comment by polysillycon** [comment]
I also observed this in FTB Infinity Evolved: Skyblock.  I unlocked the Ichor, Ichorium, etc in a single session.  I got as far as the Pickaxe, then realized I didn't have any Nether or Ender Shards.  The next night, I crafted mob farms, got the shards, then inspected them with the Thaumometer.  After that point, I noticed that the research icons were now black, and the text under also said Missing Research Required.  However, I could still click on the item and see that it is unlocked, and I could still infusion up Ichorium Ingots.  

Is there some other research that gets unlocked that is not detected by /iskamiunlocked ?

**Comment by Alex-hawks** [comment]
I had this issue as well, and I chased it down using a single player test world. It seems that the client expects some researches to be completed, that the server doesn't for some reason. As a temporary fix, go to a single-player test world, and rune the command `/tc research @a ICHOR` and make sure that on the server you have researched everything you just unlocked
