### ISSUE TITLE
1.8 Research bug.

### ISSUE THREAD

**Issue by XxFatalxGrinxX** [Thaumic-Tinkerer/ThaumicTinkerer#811]
Found a bug today, I do not know what is causing it, but when i try to get research notes for smoky quartz. i receive nothing in my inventory, but ink is used and the paper is taken.
EDIT: i am using the unstable pack on FTB.

**Comment by nekosune** [comment]
Please make sure you are using the most up to date version

**Comment by Flamingdonut** [comment]
Issue still persists on FTB Unstable 2.0.2. (ThaumicTinkerer-3.0-1.8-167)

**Comment by nekosune** [comment]
FTB Unstable 2.0.2. is not using the most up to date version (168)
