### ISSUE TITLE
Necromancy tablet consuming infused soul aspect

### ISSUE THREAD

**Issue by Soul1355** [Thaumic-Tinkerer/ThaumicTinkerer#813]
was looking for ways to get a good supply of ender pearls in hard mode and decided to try the necromancy tablet. finally farmed up enough alienis souls to make an infused one, and tried using it along with a regular alienis and humanus and the tablet consumed all three. I'd expect that only the regular souls be consumed or that it simply not allow mixing the types of souls, and do nothing.

**Comment by Zsashas** [comment]
If all three are infused, does it function properly? Two infused and one regular?

**Comment by Soul1355** [comment]
yes, 3 infused souls will remain on the pedestals properly, and I have not tested with 2 infused. but I randomly opened up the recent commits and found this https://github.com/Thaumic-Tinkerer/ThaumicTinkerer/commit/8e99d41772982f3f769e7b9e0b44b54eaf288701#diff-2111e0a3dc7dcdef80e530283ac562feR54 
and while this is clearly new, it's the same kind of logic I'd expect to find as the cause for this. 
also, to be clear, I'm just saying what I feel is the expected behavior is not the actual behavior. it's not inherently a bug or anything, I just wanted to give feedback and offer some suggestions(and was also kinda sad my infused soul I'd been hunting creepers and endermen for disappeared because I got impatient). at the same time, by the nature of the mod, it's also your prerogative to opt for the hand-wavey "it's magic, expect the unexpected" type answer.

**Comment by Zsashas** [comment]
Seems like it has to be all or none infused, from the little I understand of the code.
