### ISSUE TITLE
Typo or Recipe Changed?

### ISSUE THREAD

**Issue by lilrichy** [Thaumic-Tinkerer/ThaumicTinkerer#816]
The Talisman of Nourishment, says to infuse it with a "diamond" but uses a "primal charm".

![](https://i.gyazo.com/98b8402bed7d2ba4ead5716175baa0bb.png)

**Comment by Blue64** [comment]
That's also not the essence of hunger, as that would be the one related to Famine, not Growth, Trade, and Life.
