### ISSUE TITLE
WHY I CANT OPEN Thaumic tinkerer and thaumcraft?!?!

### ISSUE THREAD

**Issue by BryanTan123** [Thaumic-Tinkerer/ThaumicTinkerer#818]
When I open in 1.7.10 , it continue crash game , can't open into game ?! Why ?!?!

**Comment by BryanTan123** [comment]
* I already try all the version in 1.7.10 , still can't , and I already found in YouTube and Google , but I can't find any answer.. 😡😡😡😡

**Comment by bookerthegeek** [comment]
A crash report would be helpful
