### ISSUE TITLE
Cannot Craft Anything TT 1.8

### ISSUE THREAD

**Issue by SigmaLP** [Thaumic-Tinkerer/ThaumicTinkerer#820]
I am using both current versions of Thaumcraft 5 and have not been able to craft anything from Thaumic Tinkerer. TT is the only thaumcraft addon that I am using at the moment due to my familiarity with it from 1.7.10.

I'm trying to disable some of the limited mods I am using one at a time to see if it's just a conflict with one of the other mods present.

If there is any other information you require I will be checking on this from time to time.

**Comment by nekosune** [comment]
Which version of TT are you using?

**Comment by justicesays** [comment]
Having downloaded the latest version of TT 3 for 1.8.9 from curse forge

Thaumic Tinkerer 3.0 - 170

I can confirm that although the research works, and the recipes are registered, completing the research doesn't unlock the recipe for crafting. JEI shows the recipes with the red cross indicating it isn't unlocked.
The only recipes that actually work are smokey quartz, and the condensed/infused mob aspects.
Looks like there is a screw up in the scala code used to set up the recipes and research at the same time.
There are two "registerResearchItemI" functions, the first one isn't used, the second one must be using the wrong key somehow.
