### ISSUE TITLE
Port to Minecraft 1.8.9

### ISSUE THREAD

**Issue by McBossKiller** [Thaumic-Tinkerer/ThaumicTinkerer#822]
thaumcraft had ported to minecraft 1.8.9, Just wondering if this would come soon

**Comment by Alaric323** [comment]
Thaumcraft 5.1 was released less than two days ago, being the first version to support Minecraft 1.8.9 as far as I'm aware.  So Thaumic Tinkerer will need an API update,

**Comment by nekosune** [comment]
http://jenkins.nekokittygames.com:8080/job/Thaumic%20TInkerer%201.8.9/

**Comment by Alaric323** [comment]
Tried it before when I saw it pop up on the Jenkins.  What Codechicken version should we use?

**Comment by nekosune** [comment]
Download latest code chicken lib do not add code chicken core

**Comment by Alaric323** [comment]
No problems as far as I can tell with the new build, other than the items normally having compatibility with OpenComputers not showing up in the thaumonomicon.  However, since it's translations are missing, I'm assuming they're not implemented yet.

**Comment by nekosune** [comment]
OC support is in progress really, hence why not added yet, and creative only, it's there for people to try out and see if they like more then anything
