### ISSUE TITLE
Osmotic enchanter - dupe enchant

### ISSUE THREAD

**Issue by linkinkov** [Thaumic-Tinkerer/ThaumicTinkerer#825]
Then osmotic do enchant at the end just select +.

Edit: removed useless video

**Comment by nekosune** [comment]
Text to reproduce as well is much more useful then shoving videos in a language I do not understand.

**Comment by linkinkov** [comment]
My english are bad, but:
1) Open enchanter and select sharpness enchant.
2) Select to do enchant 
3) All time then item enchanting click on plus of level echanting
4) Thats all, you can enchant again (up to 5)

**Comment by linkinkov** [comment]
On video you will see all process

**Comment by linkinkov** [comment]
Another video to see process:
https://monosnap.com/file/bu0Cdrb57Xo8vXIs3Sh2IbCNHb76Iu

**Comment by linkinkov** [comment]
Anybody here?

**Comment by linkinkov** [comment]
@nekosune Katrina please help, its very overpowered dupe

**Comment by linkinkov** [comment]
Its possible be fixing?

**Comment by nekosune** [comment]
Also need to know which version is in use

**Comment by linkinkov** [comment]
Only last version, i always use version from build server

**Comment by linkinkov** [comment]
And, thats all that you can do?
Also know dupe with Transvector Dislocator, but anyway you will ignore it.
Always love TT mod, but today i must remover him from my server, too much dupes not fixed.

**Comment by nekosune** [comment]
It is being worked on, I dont fix things instantly, And I cant fix dupe's not reported, there hasnt been with the dislocator. The other issue you reported you STILL haven't, despite actually repeatedly asked, given a way to reproduce that is not a video. There are other, more important bugs, that have been worked on, like a world corruption bug, ones that destroy worlds or destroy peoples items, come before ones that let someone add another enchant to an item

**Comment by linkinkov** [comment]
Thank you for response, will wait.

**Comment by xSable** [comment]
If more information on this is needed, I can run the process by you neko. For the osmotic issue, I mean.

**Comment by linkinkov** [comment]
@nekosune i call pull for fix this dupe

**Comment by ensirius** [comment]
One year later still no fix xD
