### ISSUE TITLE
Experience dupe with exp wand

### ISSUE THREAD

**Issue by linkinkov** [Thaumic-Tinkerer/ThaumicTinkerer#826]
Edit: removed video

**Comment by nekosune** [comment]
Text to reproduce as well is much more useful then shoving videos in a language I do not understand.

**Comment by nekosune** [comment]
Again text to reproduce please

**Comment by linkinkov** [comment]
I can write text to reproduce

**Comment by nekosune** [comment]
Then do so, stop shoving videos

**Comment by linkinkov** [comment]
1) Need expiriece lvl little bit above 30
2) Enchant any item to 30 lvl
3) Need some experiece bootle (10 for example)
4) After take wand with expirience foci.
5) Right click on bootle to pour on the ground.
6) Right click wand and see that you have now - 27xxxx lvl

**Comment by ensirius** [comment]
1.5 year later
