### ISSUE TITLE
problems with ender IO farming station and infused seeds

### ISSUE THREAD

**Issue by adamsonich** [Thaumic-Tinkerer/ThaumicTinkerer#827]
I am using EnderIO-1.7.10-2.3.0.417_beta.
Farming station takes infused seeds and place minecraft wheat seeds.
autor of ender io says "The Farming Station is working correctly, it asks the seeds which plant to create and they answer "wheat":

https://github.com/Thaumic-Tinkerer/ThaumicTinkerer/blob/1.7-final/src/main/java/thaumic/tinkerer/common/item/ItemInfusedSeeds.java#L44"
https://github.com/SleepyTrousers/EnderIO/issues/3156

**Comment by nekosune** [comment]
Can not be fixed, asking how to disable their use in Farming machine

**Comment by adamsonich** [comment]
ummm, when or where i must download new version?
http://www.curse.com/mc-mods/minecraft/thaumic-tinkerer#t1:other-downloads
Thaumic Tinkerer 164 	Release	1.7.10	358,316	5 April 2015

**Comment by nekosune** [comment]
I am working on a final 1.7.10 release,  this will be released with it,
unless there is a major bug fix I don't release for a single feature

**Comment by adamsonich** [comment]
Ok, sad (((
will wait, but i hope it will happened very soon.
THANK YOU!

**Comment by nekosune** [comment]
If you are playing single player, grab the latest here:
http://jenkins.nekokittygames.com:8080/job/Thaumic%20Tinkerer/ It will
include the fix
