### ISSUE TITLE
Duplicate id with something in Intangible mod

### ISSUE THREAD

**Issue by Luckyday84** [Thaumic-Tinkerer/ThaumicTinkerer#832]
http://pastebin.com/kn9Ftqjg

**Comment by nekosune** [comment]
This is I am afraid not fixable, without one mod or the other breaking all
saves that use the funnel block... seeing as the release this month or next
is the final 1.7.10 release, that is not worth it. in 1.8.9 this will be
changed so this conflict can never happen again

2016-02-06 2:19 GMT+00:00 Luckyday84 <notifications@github.com>:

**Comment by nekosune** [comment]
And this is why Stating version of the mod in use helps, this will be fixed in a two step release once I have the 1.7.10 release out

**Comment by Luckyday84** [comment]
Wow thanks for the fast responses. I will remember to add the mod version for the next report I make.

**Comment by nekosune** [comment]
No problem, and yeah, The problem with this bug is, I need to partially fix in one release, wait until a reasonable amount of people are using that release, then release next that removes the duplicate ID, to make sure people dont loose expensive/fancy jars
