### ISSUE TITLE
Server crash and irrecoverable map damage

### ISSUE THREAD

**Issue by leagris** [Thaumic-Tinkerer/ThaumicTinkerer#833]
at thaumic.tinkerer.common.compat.InfusedSeedsPlanter.plant

While and EnderIO Farming Station tries to plant vanilla seeds on some place.
Reported here for the EnderIO part: https://github.com/SleepyTrousers/EnderIO/issues/3186

**Comment by nekosune** [comment]
Edit forge.cfg, select remove erroring tiile entities, that should recover the map for you at the cost of the planter, I will investigate this and produce a fix

**Comment by leagris** [comment]
Still same crash with ThaumicTinkerer-2.5-1.7.10-520
@nekosune Can you re-open issue?
[file-crash-2016-02-08_20-25-20-server-txt](https://gist.github.com/leagris/5ff8e20aecacdb1f24c8#file-crash-2016-02-08_20-25-20-server-txt)

**Comment by nekosune** [comment]
Different issue, but related, I will make a new issue for you

**Comment by nekosune** [comment]
That is fixed
