### ISSUE TITLE
Dynamism Tablet does not obey Fakeplayer Build Permissions

### ISSUE THREAD

**Issue by cookta2012** [Thaumic-Tinkerer/ThaumicTinkerer#837]
I am on a server that does not allow anyone to build unless they have been promoted i have looked in the code and the fakeplayer is in the code but it is not respecting land claims.

**Comment by nekosune** [comment]
need more information, for example the mod being used to add land claims

**Comment by cookta2012** [comment]
I am running cauldron which has world guard, and greif prevention. I do know buildcraft, and openblocks. Respect permissions.
