### ISSUE TITLE
[1.7.10] Armor conflict with KCauldron/Thermos

### ISSUE THREAD

**Issue by TerdyTheTerd** [Thaumic-Tinkerer/ThaumicTinkerer#840]
https://gitlab.prok.pw/KCauldron/KCauldron/issues/347

Basically (I know that issue says stuff about Chaos Guardian, but a few post down and I will make a post with steps to reproduce) whenever Kami is enabled while using KCauldron/Thermos any armor that uses energy or is higher tier protection than diamond gets ignored, so a zombie can easily kill a player in whatever end game armor they are wearing. Disabling Kami removes the issue. It isnt present in forge, but I felt I should at least post this here in case any dev has an idea for it. I know a lot of devs don't support modified forge versions, so if you don't wanna look into it just close the issue.

**Comment by nekosune** [comment]
I am sorry, this having to do with modified forge, and the fact it doesn't appear to be happening under forge, would make this very hard to track down the underlying cause

**Comment by DwarfyAssassin** [comment]
Does anyone know if this was ever fixed?

**Comment by TerdyTheTerd** [comment]
IIRC it was an issue with how kcauldron tried to patch one of the forge classes to work with bukkit. Not an actual Kami issue.
