### ISSUE TITLE
thaumic tinkerer 1.8.9 compatibility

### ISSUE THREAD

**Issue by Soulreaper241** [Thaumic-Tinkerer/ThaumicTinkerer#844]
it seems that thaumic tinkerer doesnt support 1.8.9 sins when i try it gives an error stating that it wants 1.8 and no further. is this a recurring thing to most or is it not yet updated to 1.8.9?

**Comment by killerjerick** [comment]
There is a 1.8.9 version but I can't get it to work with a lot of the mods I have so no guarantee it'll work but here it is: 

http://jenkins.nekokittygames.com:8080/job/Thaumic%20TInkerer%201.8.9/


As a side note, 1.8 mods do not work on 1.8.9

**Comment by Soulreaper241** [comment]
It works. Thank you
