### ISSUE TITLE
Paving Stairs of Warding and slabs not craftable

### ISSUE THREAD

**Issue by Dream-Master** [Thaumic-Tinkerer/ThaumicTinkerer#845]
Paving Stairs of Warding and slabs not craftable.

I using  ThaumicTinkerer-2.5-1.7.10-523.jar in my modpack.

https://github.com/GTNewHorizons/NewHorizons

https://www.dropbox.com/s/7qvup9jx5o8s01p/Screenshot%202016-03-23%2017.18.36.png?dl=0

https://www.dropbox.com/s/5tycm35s1dzbwc7/Screenshot%202016-03-23%2017.16.19.png?dl=0

https://www.dropbox.com/s/kzuxh2fiz1lflyi/Screenshot%202016-03-23%2017.16.16.png?dl=0

**Comment by Dream-Master** [comment]
I guess it is a metadat thing. Will try to fix it.

**Comment by nekosune** [comment]
Deliberatly not craftable as not finished.
