### ISSUE TITLE
Infused Seeds Infusion crafting only gives Aer Seeds

### ISSUE THREAD

**Issue by JasonMcRay** [Thaumic-Tinkerer/ThaumicTinkerer#847]
When attempting to infuse seeds with for example terra shards to make Terra Infused Seeds, the infusion gives only Aer Infused Seeds. This happens with all infused seeds

TT: Build 523

**Comment by thaelina** [comment]
I'm having the same issue. Tried to use minetweaker to make a workaround for it but it seems that whichever recipe I add first is the one that gets used for all 6 of the infusions.

**Comment by Jorvalt** [comment]
Same issue here, playing on the FTB Infinity Evolved Skyblock modpack. Build 512 as well.

**Comment by Jorvalt** [comment]
I'm not even exactly sure how the seeds are differentiated. They all have the exact same item ID with no data tags, and when I looked at the NEI dump there aren't separate items, just one.

**Comment by Dream-Master** [comment]
NBT data are different. Using Modtweaker to fix it.

**Comment by Jorvalt** [comment]
Yeah, I kinda figured.

Good luck with that, also.

**Comment by Jorvalt** [comment]
Let me know if you make a breakthrough.

**Comment by thaelina** [comment]
I tried using modtweaker when I first encountered the issue. Which ever recipe added last was the one all of the seed infusions made.

**Comment by nekosune** [comment]
There will be a quick release to fix this and a few other urgent bugs within a day or two

**Comment by bookerthegeek** [comment]
Question, can you sneaky update this the release included with ftb infinity? This way we can update server side while waiting for the next modpack updates?

**Comment by nekosune** [comment]
Looking into this more, may be more difficult to fix then thought, thanks to infusion ignoring nbt.

**Comment by nekosune** [comment]
Please test on latest, cofirm the problem still exists
