### ISSUE TITLE
Crash with Ender IO 2.2.8.381

### ISSUE THREAD

**Issue by Reystlin** [Thaumic-Tinkerer/ThaumicTinkerer#848]
EnderIO-1.7.10-2.2.8.381 and ThaumicTinkerer-2.5-1.7.10-523 
http://openeye.openmods.info/crashes/8b4ee908b45336b430da376f5988f805

**Comment by AnrDaemon** [comment]
Get build 517(but it have known issue with EIO Farming Station) or update EIO already.
