### ISSUE TITLE
Disabling Kami in configs does not work

### ISSUE THREAD

**Issue by SSW82** [Thaumic-Tinkerer/ThaumicTinkerer#852]
I attempted to disable TT KAMI in the configuration file for my 1.7.10 server. I have double- and triple-checked that it is indeed disabled. It is. I have set it thusly: kami.forceenabled=false. It has been set to false the entire time Thaumic Tinkerer has been in this modpack. 

TT Kami research is still appearing in the Thaumonomicon despite disabling it. To test, I completed several chains of TT Kami research successfully. 

I am using the latest version of TT for 1.7.10.

**Comment by nekosune** [comment]
Set to false on client and server?

**Comment by SSW82** [comment]
Yep!

**Comment by nekosune** [comment]
Will explore this and fix

**Comment by SSW82** [comment]
Thank you!
