### ISSUE TITLE
[1.7.10] Client crash upon connecting to Server

### ISSUE THREAD

**Issue by Deathlymad** [Thaumic-Tinkerer/ThaumicTinkerer#853]
Log upon crash: https://drive.google.com/file/d/0B_bxEKYJKQXFc0VEWExvWEJRbWM/view?usp=sharing

I know that my version is outdated but i didn't find another report of this nor did I see a fix (but it is possible that i am just blind). SoI can report that i get the given crash if i boot up minecraft and then straight connect to a server however the crash can be avoided if i start up a single player world before connecting to a server.

**Comment by nekosune** [comment]
It's a crash thanks to NotEnoughResources using this code to show charged creeper - https://github.com/hilburn/NotEnoughResources/blob/master/src/main/java/neresources/compatibility/reliquary/ReliquaryCompat.java#L115

They hurt a creeper, from nothing, and that results in a null being sent to TT where there never should be a null (There should always be something that was hurt, when a LivingEntityHurtEvent is called

**Comment by Deathlymad** [comment]
Thank you for the quick reply, I'll try to fix it and notify the ner author

**Comment by nekosune** [comment]
I will also be fixing it on my side by checking null there. But any mod that does somethign on living hurt could have weird effects due to that call calling OnLivingHurt eweirdly

**Comment by Deathlymad** [comment]
Thx <3

**Comment by nekosune** [comment]
Hey, please don't remove logs, it makes it hard to actually fix the problem

**Comment by Deathlymad** [comment]
sorry i misconfigured the link it should work now.

**Comment by Dream-Master** [comment]
are these fixes available on jenkins ?
http://jenkins.nekokittygames.com:8080/view/Thaumic%20Tinkerer/job/Thaumic%20Tinkerer/

**Comment by nekosune** [comment]
Will be, jenkins broke after I needed to change keys for security, getting it back going now

**Comment by Dream-Master** [comment]
Thanks :+1:

**Comment by nekosune** [comment]
http://jenkins.nekokittygames.com:8080/job/Thaumic%20Tinkerer/
