### ISSUE TITLE
Can not unlock the TT2 hidden research

### ISSUE THREAD

**Issue by NyanU** [Thaumic-Tinkerer/ThaumicTinkerer#854]
(on server)
Unlock all of the research include other addons,but still could not be open TT2 hiding research

Other players can unlock the research, but according to their approach but I can not unlock,i'm pretty sure in addition TT2 Hide all research research have all been unlocked because i compared the book to unlock all in single-player mode(cheat command)

All mod list:

**Comment by NyanU** [comment]
![Uploading 2.jpg…]()

**Comment by NyanU** [comment]
`http://i68.tinypic.com/2exncqo.jpg``http://i65.tinypic.com/2zp5m60.jpg`
Can not upload on github(failed)

**Comment by NyanU** [comment]
Want to unlock kami(god)
All research has unlocked contain other extensions, including
Already scanned items such as: nether star,pigman,enderman,nether fragment,ender fragment,diamond, 6 elements fragment……and more 

But DimensionSliver is missing front research

**Comment by nekosune** [comment]
Try the command /iskamiunlocked
