### ISSUE TITLE
Compatability issues?

### ISSUE THREAD

**Issue by Hexer123** [Thaumic-Tinkerer/ThaumicTinkerer#855]
So my friend is using a custom mod pack of mine and for what ever reason my 2 other friends who also have the pack and myself can load it just fine but he is unable to for whatever reason and also whenever he takes out thaumic tinkerer it loads up just fine. here's the error log he gets when he tries to load it up:

https://gist.github.com/Hexer123/417396cdd12a7ce10dc126cf408a175d#file-gistfile1-txt

**Comment by bookerthegeek** [comment]
Edit your comment so the log is on ghist or pastebin.

**Comment by nekosune** [comment]
Please only report bugs with the latest version of Thaumic Tinkerer for the minecraft version

**Comment by Hexer123** [comment]
comment edited (sorry im new to this so im not sure if I even did this correctly)

**Comment by nekosune** [comment]
Link to the latest: http://minecraft.curseforge.com/projects/thaumic-tinkerer/files/2232793
