### ISSUE TITLE
[1.8.9] Crash on Startup

### ISSUE THREAD

**Issue by HyperMan19680** [Thaumic-Tinkerer/ThaumicTinkerer#866]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  BCModPlugin (zz-backpacks 1.8.9 - 3.1.2.jar)
  MDECore-Core (mdecore-1.8.9-1.1.1.jar)
  ShadowMCCore (ShadowMC-1.8.9-3.0.0-SNAPSHOT (3).jar)
  CoreXU2 (extrautils2-1.8.9-alpha-0.0.2.jar)
  ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)
  MalisisSwitchesPlugin (malisisswitches-1.8.9-1.0.1.jar)
  FMLPlugin (InventoryTweaks-1.60-40.jar)
  LucraftForgeLoading (LucraftCore-1.8.9-1.1.0.jar)
  RenderPlayerAPIPlugin (RenderPlayerAPI-1.8.9-1.0.jar)
  thaumicinfusion (ThaumicInfusion-1.8.9-4.88.jar)
  BookshelfLoadingPlugin (Bookshelf-1.8.9-1.1.2.207.jar)
  MalisisCorePlugin (malisiscore-1.8.9-2.1.5.jar)
  RenderPlayerAPIEnhancerPlugin (RenderPlayerAPIEnhancer-1.8.9-1.0.jar)
  NowWithRendering (redstonepaste-mc1.8.8-1.7.2.jar)
  LoadingPlugin (RandomThings-MC1.8.9-3.6.6.jar)
  EnderCorePlugin (EnderCore-1.8.9-0.3.0.14-beta.jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 9/20/16 1:33 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: codechicken/lib/packet/PacketCustom$ICustomPacketHandler
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:162)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:543)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: codechicken/lib/packet/PacketCustom$ICustomPacketHandler
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:344)
	at net.minecraftforge.fml.common.ILanguageAdapter$ScalaAdapter.setInternalProxies(ILanguageAdapter.java:140)
	at net.minecraftforge.fml.common.ProxyInjector.inject(ProxyInjector.java:86)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:540)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:512)
	... 10 more
Caused by: java.lang.ClassNotFoundException: codechicken.lib.packet.PacketCustom$ICustomPacketHandler
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 36 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 126265768 bytes (120 MB) / 388108288 bytes (370 MB) up to 6429081600 bytes (6131 MB)
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UseConcMarkSweepGC -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.1902 167 mods loaded, 166 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1902-1.8.9.jar) 
	UC	Forge{11.15.1.1902} [Minecraft Forge] (forge-1.8.9-11.15.1.1902-1.8.9.jar) 
	UC	RenderPlayerAPI{1.0} [Render Player API] (minecraft.jar) 
	UC	RenderPlayerAPIEnhancer{1.0} [Render Player API Enhancer] (minecraft.jar) 
	UC	backpacks16840{3.1.2} [Backpacks!] (zz-backpacks 1.8.9 - 3.1.2.jar) 
	UC	securitycraft{v1.8.1} [SecurityCraft] ([1.8.8] SecurityCraft v1.8.1.jar) 
	UC	BuildCraft|Core{7.2.7} [BuildCraft] (buildcraft-7.2.7.jar) 
	UC	BuildCraft|Silicon{7.2.7} [BC Silicon] (buildcraft-7.2.7.jar) 
	UC	BuildCraft|Transport{7.2.7} [BC Transport] (buildcraft-7.2.7.jar) 
	UC	Waila{1.6.0} [Waila] (Waila-1.6.0-B3_1.8.8.jar) 
	UC	WailaAddonBC{1.0.0} [WailaAddonBC] ([1.8.9]WailaAddonBC-1.0.1.jar) 
	UC	BuildCraft|Energy{7.2.7} [BC Energy] (buildcraft-7.2.7.jar) 
	UC	ActuallyAdditions{1.8.9-r25} [Actually Additions] (ActuallyAdditions-1.8.9-r25.jar) 
	UC	AntMan{1.8.9-1.1.0} [AntMan] (AntMan-1.8.9-1.1.0.jar) 
	UC	Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
	UC	Thaumcraft{5.2.4} [Thaumcraft] (Thaumcraft-1.8.9-5.2.4.jar) 
	UC	Automagy{2.0.3} [Automagy] (Automagy-1.8.9-2.0.3.jar) 
	UC	bdlib{1.10.0.31} [BD Lib] (bdlib-1.10.0.31-mc1.8.9.jar) 
	UC	BetterAchievements{0.1.1} [Better Achievements] (BetterAchievements-1.8.9-0.1.1.jar) 
	UC	betterbonemeal{1.0.0} [BetterBoneMeal] (betterbonemeal-1.8.9-1.0.0.jar) 
	UC	betterbuilderswands{0.6.0} [Better Builder's Wands] (BetterBuildersWands-0.6.0-1.8.9r102+b0b2644.jar) 
	UC	betterrecords{1.8.9-1.3.0} [Better Records] (betterrecords-1.8.9-1.3.0.jar) 
	UC	bookshelf{1.1.2.207} [Bookshelf] (Bookshelf-1.8.9-1.1.2.207.jar) 
	UC	bookshelfapi{2.3.7} [Bookshelf] (Bookshelf-API-1.8.9-2.3.7.jar) 
	UC	Botania{r1.8-299} [Botania] (Botania-unofficial.r1.8-299.jar) 
	UC	BuildCraft|Builders{7.2.7} [BC Builders] (buildcraft-7.2.7.jar) 
	UC	BuildCraft|Robotics{7.2.7} [BC Robotics] (buildcraft-7.2.7.jar) 
	UC	BuildCraft|Factory{7.2.7} [BC Factory] (buildcraft-7.2.7.jar) 
	UC	IronChest{6.0.125.770} [Iron Chest] (ironchest-1.8.9-6.0.125.770.jar) 
	UC	BuildCraft|Compat{7.2.1} [BuildCraft Compat] (buildcraft-compat-7.2.1.jar) 
	UC	SonarCore{2.0.1} [SonarCore] (SonarCore-1.8.9-2.0.1.jar) 
	UC	Calculator{2.0.1} [Calculator] (Calculator-1.8.9-2.0.1.jar) 
	UC	capsule{1.0.3} [Capsule] (capsule-1.8.9-1.1.4.jar) 
	UC	Chameleon{1.8.9-1.1.4} [Chameleon] (Chameleon-1.8.9-1.1.4.jar) 
	UC	compactstorage{v2.0.0a} [CompactStorage] (compactstorage-2.1-1.8.9-rc.jar) 
	UC	correlatedpotentialistics{0.2} [Correlated Potentialistics] (CorrelatedPotentialistics-0.2.jar) 
	UC	cotv{1_8_9.0.0} [Chalice of the Void] (cotv-1_8_9.0.0.jar) 
	UC	craftingcraft{2.0.13} [CraftingCraft] (craftingcraft-mc1.8.9-2.0.13.jar) 
	UC	craftingtweaks{3.0.55} [Crafting Tweaks] (craftingtweaks-mc1.8.9-3.0.55.jar) 
	UC	creativecore{1.4.0} [CreativeCore] (CreativeCore v1.4 mc1.8.9.jar) 
	UC	drones{1.8.9-1.0.3} [CustomDrones] (CustomDrones-1.0.3-mc1.8.9.jar) 
	UC	cyclopscore{0.5.7} [Cyclops Core] (CyclopsCore-1.8.9-0.5.7.jar) 
	UC	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.8.9-alpha-0.0.2.jar) 
	UC	intangible{0.0.25} [Intangible] (intangible-1.8.9-0.0.25.jar) 
	UC	JEI{2.28.18.186} [Just Enough Items] (jei_1.8.9-2.28.18.186.jar) 
	UC	DarkUtils{1.0.0.21} [Dark Utilities] (DarkUtilities-1.8.9-1.0.0.27.jar) 
	UC	dce{1.0.4} [DiscordCE] (dce-1.8.9-1.0.4.jar) 
	UC	Ding{MC1.8.9v2} [Ding] (Ding-MC1.8.9v2.jar) 
	UC	disenchanter{1.4} [Disenchanter] (disenchanter-[1.8.9]1.4.jar) 
	UC	net.blacklab.lib{3.3.13} [EBLib] (EBLib-EL3B13-1.8.x.jar) 
	UC	eirairc{4.9.12} [EiraIRC] (eirairc-mc1.8.9-4.9.12.jar) 
	UC	enchiridion{3.1.4} [Enchiridion] (Enchiridion-1.8.9-3.1.4.jar) 
	UC	endercore{1.8.9-0.3.0.14-beta} [EnderCore] (EnderCore-1.8.9-0.3.0.14-beta.jar) 
	UC	EnderIO{1.8.9-3.0.0.26_alpha} [Ender IO] (EnderIO-1.8.9-3.0.0.26_alpha.jar) 
	UC	ShetiPhianCore{3.1.2} [ShetiPhian-Core] (ShetiPhianCore-1.8.9-3.1.2.jar) 
	UC	EnderTanks{1.2.2} [EnderTanks] (EnderTanks-1.8.9-1.2.2.jar) 
	UC	enderutilities{0.5.6} [Ender Utilities] (enderutilities-1.8.9-0.5.6.jar) 
	UC	excore{1.5.3} [EXCore] (Excore-LATEST-1.8.9.jar) 
	UC	ezstorage{1.0} [EZ Storage] (ezstorage-1.8.9-1.2.6.jar) 
	UC	ezextended{1.0.1} [EZ Extended] (ezextended-1.0.1-[1.8.9-backport].jar) 
	UC	FFS{1.8.9-1.5.5.13} [Fancy Fluid Storage] (Fancy Fluid Storage-1.8.9-1.5.5.13.jar) 
	UC	fbtoggle{1.0.0} [FBToggle] (fbtoggle-1.8.9-1.1.jar) 
	UC	ftfloocraft{1.8.9-0.2} [Floocraft] (Floocraft-1.8.9-0.2.jar) 
	UC	FloodLights{1.2.7-143} [Flood Lights] (FloodLights-1.8.9-1.2.7-143.jar) 
	UC	gemsplus{1.7} [Gems+] (gemsplus-1.7-mc1.8.9.jar) 
	UC	grapplemod{1.9.4-v7} [Grappling hook mod] (grapplemod-1.8.9-v7.jar) 
	UC	HelperTools{v2.5c} [HelperTools] (Helpertools-1.8.9-2.5b.jar) 
	UC	HelpFixer{1.8.9-1.2.12} [HelpFixer] (HelpFixer-1.8.9-1.2.12.jar) 
	UC	howlingmoon{1.1.1} [Howling Moon] (howlingMoon-1.8.9-1.1.1.jar) 
	UC	IGWMod{1.2.4-4} [In-Game wiki Mod] (IGW-Mod-1.8.9-1.2.4-4-universal.jar) 
	UC	integrateddynamics{0.3.9} [Integrated Dynamics] (IntegratedDynamics-1.8.9-0.3.9.jar) 
	UC	InventoryCenterer{1.8.9-0.1.1} [Inventory Centerer] (InventoryCenterer-1.8.9-0.1.1.jar) 
	UC	InventoryPets{1.4.8} [Inventory Pets] (inventorypets-1.8.9-1.4.8.jar) 
	UC	inventorytweaks{1.60-40-e06e29a} [Inventory Tweaks] (InventoryTweaks-1.60-40.jar) 
	UC	ironbackpacks{1.8.9-2.0.5} [Iron Backpacks] (IronBackpacks-1.8.9-2.0.5.jar) 
	UC	itemscroller{0.4.0} [Item Scroller] (itemscroller-1.8.9-0.4.0.jar) 
	UC	japta{1.5.1} [JAPTA] (JAPTA-1.5.1.jar) 
	UC	k4lib{1.8.9-1.0.18} [K4Lib] (k4lib-1.8.9-1.0.18-universal.jar) 
	UC	LucraftCore{1.8.9-1.1.0} [Lucraft: Core] (LucraftCore-1.8.9-1.1.0.jar) 
	UC	LunatriusCore{1.1.2.32} [LunatriusCore] (LunatriusCore-1.8.9-1.1.2.32-universal.jar) 
	UC	macrokey{1.8.9-1.1.5.1} [MacroKey] (macrokey-1.8.9-1.1.5.1.jar) 
	UC	magiz{1.1.0} [Magiz - Reborn] (Magiz-1.1.1 - for Minecraft 1.8.9.jar) 
	UC	malisiscore{1.8.9-2.1.5} [MalisisCore] (malisiscore-1.8.9-2.1.5.jar) 
	UC	malisisblocks{1.8.9-2.0.1} [Malisis Blocks] (malisisblocks-1.8.9-2.0.1.jar) 
	UC	malisisdoors{1.8.9-3.1.4} [MalisisDoors] (malisisdoors-1.8.9-3.1.4.jar) 
	UC	malisisswitches{1.8.9-1.0.1} [Malisis Switches] (malisisswitches-1.8.9-1.0.1.jar) 
	UC	mantle{1.8.9-0.9.2.jenkins102} [Mantle] (Mantle-1.8.9-0.9.2.jar) 
	UC	mo{0.4.2} [Matter Overdrive] (MatterOverdrive-1.8.9-0.4.2-build-34.jar) 
	UC	mcmultipart{1.0.8} [MCMultiPart] (MCMultiPart-1.0.8-universal (1).jar) 
	UC	mdecore{1.8.9-1.1.1} [MattDahEpic Core] (mdecore-1.8.9-1.1.1.jar) 
	UC	MineMenu{1.3.0} [MineMenu] (MineMenu-1.8.9-1.3.0.B45-universal.jar) 
	UC	mineTunes{1.1-6} [mineTunes] (MineTunes 1.1-6.jar) 
	UC	ModLister{1.8.9-1.0.7} [ModLister] (ModLister-1.8.9-1.0.7.jar) 
	UC	numina{0.5.0-004} [Numina] (Numina-0.5.0-004.jar) 
	UC	powersuits{0.11.0-7} [MachineMuse's Modular Powersuits] (ModularPowersuits-1.8.9-0.11.0-7.jar) 
	UC	MoreCommands{1.0.0} [MoreCommands] (MoreCommands_1.6.189.jar) 
	UC	MoreFurnaces{1.5.1} [More Furnaces] (MoreFurnaces-1.5.1-MC1.8.9.jar) 
	UC	mp3Jukebox{2.2.2} [mp3 Jukebox Mod] (mp3JUKEBOX-MC1.8.9-2.2.2.jar) 
	UC	multistorage{1.0.0} [Multi-Storage] (multistorage-1.8.9-1.0.0.jar) 
	UC	Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat] (Neat 1.1-3.jar) 
	UC	tconstruct{1.8.9-2.2.1.jenkins1005} [Tinkers' Construct] (TConstruct-1.8.9-2.2.1.jar) 
	UC	neotech{2.4.4} [NeoTech] (NeoTech-1.8.9-2.4.4.jar) 
	UC	NoFov{1.0} [No Fov] (NoFov-MC1.8-1.0.jar) 
	UC	nmsot{1.1.4-mc1.8.9} [No Mob Spawning on Trees] (NoMobSpawningOnTrees-1.1.4-mc1.8.9.jar) 
	UC	NoSlime{0.1} [Slimeless Flatworlds] (NoSlime-1.8.9-1.0.jar) 
	UC	NotEnoughCodecs{0.5} [NotEnoughCodecs] (NotEnoughCodecs-1.8.9-0.5.jar) 
	UC	notenoughkeys{@MOD_VERSION@} [NotEnoughKeys] (NotEnoughKeys-1.8.9-3.0.0b1-dev-universal.jar) 
	UC	notenoughwands{1.3.1} [Not Enough Wands] (notenoughwands-1.8.9-1.3.1.jar) 
	UC	papertazermod{1.0} [Papertazers Base Mod] (Papertazer Base Mod-1.1.jar) 
	UC	parachutemod{1.2.2} [Parachute Mod] (parachutemod-ng-1.8.9-1.2.2-341.jar) 
	UC	gunpowder{1.1_1.8.8} [Placeable Gunpowder] (PlaceableGunpowder-1.1_1.8.8.jar) 
	UC	platforms{1.0.3} [Platforms] (platforms-1.8.9-1.0.3.jar) 
	UC	PocketDimension{1.3.1} [Pocket Dimension] (PocketDimension-1.3.1.jar) 
	UC	practicalities{2.0.0-b6} [Practicalities] (practicalities-1.8.9-2.0.0-b6.jar) 
	UC	pressure{1.3.0.25} [Pressure Pipes] (pressure-1.3.0.25-mc1.8.9.jar) 
	UC	ProjectE{1.8.9-PE1.1.4} [ProjectE] (ProjectE-1.8.9-PE1.1.4.jar) 
	UC	Psi{beta-23} [Psi] (Psi-beta-23.jar) 
	UC	psiproducts{1.0.0} [Psi Dot Products] (PsiProducts-1.0.0.jar) 
	UC	quantumflux{2.0.1} [QuantumFlux] (quantumflux-1.8.9-2.0.1.jar) 
	UC	quickhotbar{1.04} [Quick Hotbar] (quickhotbar_189_1.04.jar) 
	UC	RadixCore{1.8.9-2.1.0} [RadixCore] (RadixCore-1.8.9-2.1.0-universal.jar) 
	UC	rafradek_tf2_weapons{0.5.2} [TF2 Stuff Mod] (rafradek_tf2_weapons-1.8.9-0.5.2.jar) 
	UC	RainSjaman{1.8.9-1.0.5} [Rain Sjaman] (RainSjaman-1.8.9-1.0.5-universal.jar) 
	UC	randomthings{3.6.6} [Random Things] (RandomThings-MC1.8.9-3.6.6.jar) 
	UC	rapidform{1.2} [RapidForm] (rapidform-1.8.9-1.2.jar) 
	UC	mrdimkaraytracelib{0.0.1} [MrDimka's Ray Trace Library] (RayTraceLib_1.8.9-0.0.1.jar) 
	UC	reborncore{1.4.2.19} [RebornCore] (RebornCore-1.8.9-1.4.2.19-universal.jar) 
	UC	redstonepaste{1.7.2} [Redstone Paste] (redstonepaste-mc1.8.8-1.7.2.jar) 
	UC	reforged{0.7-pre3} [Reforged] (reforged-0.7-pre3-alpha-1.8.9.jar) 
	UC	reforged_cag{1.0} [Reforged - Cross & Grave] (reforged_cag-1.8.9-0.8.1-beta.jar) 
	UC	xreliquary{1.8.9-1.3.1.296} [Reliquary] (Reliquary-1.8.9-1.3.1.296.jar) 
	UC	rftools{4.23beta40} [RFTools] (rftools-1.8.9-4.23beta40.jar) 
	UC	rftoolsdim{4.22beta32} [RFTools Dimensions] (rftoolsdim-1.8.9-4.22beta32.jar) 
	UC	rpcraft{2.0} [RP Craft] (rpcraft-1.8.9-2.1.1.jar) 
	UC	rpgadgets{1.0} [RP Craft: Gadgetry] (rpgadgets-1.8.9-1.0.2.jar) 
	UC	rplocks{1.0} [RP Craft: Locks and Keys] (rplocks-1.8.9-1.0.4.jar) 
	UC	Schematica{1.7.7.143} [Schematica] (Schematica-1.8.9-1.7.7.143-universal.jar) 
	UC	SchoolsMagic{1.0} [Schools of Magic] (SchoolsMagic-1.8.9-1.1.jar) 
	UC	seedcopy{2.0.0} [SeedCopy] (SeedCopy-1.8.9-2.0.0.jar) 
	UC	shadowmc{3.0.0-SNAPSHOT} [ShadowMC] (ShadowMC-1.8.9-3.0.0-SNAPSHOT (3).jar) 
	UC	Sigma{1.0} [Sigma] (Sigma-0.7.jar) 
	UC	smf{1.4} [Scarab's Missing Furniture Mod] (smf-1.4.jar) 
	UC	stabilizermod{3.4} [stabilizermod] (Stabilizer-3.4-1.8.9.jar) 
	UC	StorageDrawers{1.8.9-2.7.0} [Storage Drawers] (StorageDrawers-1.8.9-2.7.0.jar) 
	UC	storagenetwork{1.11.1-final} [Storage Network] (StorageNetwork-1.8.9-1.11.1-final.jar) 
	UC	storagesilo{1.2.2} [StorageSilo] (storagesilo-1.8.9-1.2.2b.jar) 
	UC	substratum{1.1.0.1} [Substratum] (Substratum-1.8.9-1.1.0.1.jar) 
	UC	thaumicadditions{0.39} [Thaumic Additions] (Thaumic Additions - 1.8.9 - 0.39.jar) 
	UC	thaumicinfusion{4.86} [Thaumic Infusion] (ThaumicInfusion-1.8.9-4.88.jar) 
	UE	thaumictinkerer{${version}} [Thaumic Tinkerer] (ThaumicTinkerer-3.0-1.8.9-170.jar) 
	UC	thutcore{2.3.3} [ThutCore] (thutcore-2.3.3.jar) 
	UC	tinker_io{beta 2.2.1a} [Tinker I/O] (tinker_io-1.8.9-beta 2.1.1a.jar) 
	UC	TinkersAddons{1.0.2} [Tinkers' Addons] (Tinkers' Addons-1.8.9-1.0.2.jar) 
	UC	tomtom{@Version@} [TomTom] (tomtom-1.8.9-b14-universal.jar) 
	UC	Tracer{1.0.0.1} [Tracer] (Tracer-1.8.9-1.0.0.1-universal.jar) 
	UC	tumbleweed{1.8.9-0.2} [Tumbleweed] (tumbleweed-1.8.9-0.2.jar) 
	UC	ultimate_unicorn_mod{1.5.4} [Wings, Horns, and Hooves, the Ultimate Unicorn Mod!] (ultimate_unicorn_mod-1.8.9-1.5.4.jar) 
	UC	utilityworlds{1.0.9} [Utility Worlds] (UtilityWorlds-1.8.9_1.0.9.jar) 
	UC	WailaHarvestability{1.1.7} [Waila Harvestability] (WailaHarvestability-mc1.8.x-1.1.7.jar) 
	UC	warpbook{3.0.1} [Warp Book] (warpbook-1.8.9_3.0.1.jar) 
	UC	wawla{1.1.4.168} [What Are We Looking At] (Wawla-1.8.9-1.1.4.171.jar) 
	UC	Waypoints{1.8.9-1.2.0c} [Waypoints] (waypoints-1.8.9-1.2.0c.jar) 
	UC	zc_entities{0.2.0} [ZC Entities] (ZC Entities-0.2.0-1.8.9.jar) 
	UC	zenotechnology{0.1} [ZenoTechology] (ZenoTechnology-1.8.9-1.1.jar) 
	UC	zoooooom{0.1.2} [Zoooooom] (Zoooooom-1.8.9-0.1.2.jar) 
	UD	mdecore-core{1.0} [MDE Core - ASM Tweaks] (minecraft.jar) 
	Loaded coremods (and transformers): 
BCModPlugin (zz-backpacks 1.8.9 - 3.1.2.jar)
  brad16840.common.asm.ClassTransformer
MDECore-Core (mdecore-1.8.9-1.1.1.jar)
  com.mattdahepic.mdecore.asm.TickrateTransformer
ShadowMCCore (ShadowMC-1.8.9-3.0.0-SNAPSHOT (3).jar)
  net.shadowfacts.shadowmc.core.ShadowMCTransformer
CoreXU2 (extrautils2-1.8.9-alpha-0.0.2.jar)
  com.rwtema.extrautils2.asm.ClassTransformerHandler
ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)
  
MalisisSwitchesPlugin (malisisswitches-1.8.9-1.0.1.jar)
  net.malisis.switches.asm.MalisisSwitchesTransformer
FMLPlugin (InventoryTweaks-1.60-40.jar)
  invtweaks.forge.asm.ContainerTransformer
LucraftForgeLoading (LucraftCore-1.8.9-1.1.0.jar)
  lucraft.mods.lucraftcore.access.LucraftClassTransformer
RenderPlayerAPIPlugin (RenderPlayerAPI-1.8.9-1.0.jar)
  api.player.forge.RenderPlayerAPITransformer
thaumicinfusion (ThaumicInfusion-1.8.9-4.88.jar)
  drunkmafia.thaumicinfusion.common.asm.BlockTransformer
  drunkmafia.thaumicinfusion.common.asm.WorldTransformer
BookshelfLoadingPlugin (Bookshelf-1.8.9-1.1.2.207.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
MalisisCorePlugin (malisiscore-1.8.9-2.1.5.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
RenderPlayerAPIEnhancerPlugin (RenderPlayerAPIEnhancer-1.8.9-1.0.jar)
  api.player.forge.RenderPlayerAPIEnhancerTransformer
NowWithRendering (redstonepaste-mc1.8.8-1.7.2.jar)
  net.fybertech.nwr.NowWithRendering
LoadingPlugin (RandomThings-MC1.8.9-3.6.6.jar)
  lumien.randomthings.asm.ClassTransformer
EnderCorePlugin (EnderCore-1.8.9-0.3.0.14-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.200.1062.1004' Renderer: 'AMD Radeon HD 8650G'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)

**Comment by nekosune** [comment]
You need code chicken lib installed

**Comment by WolfBV** [comment]
https://www.curseforge.com/minecraft/mc-mods/codechickenlib-1-8-9
