### ISSUE TITLE
can Ichorium be unlocked with banned research?

### ISSUE THREAD

**Issue by NalyKalZul** [Thaumic-Tinkerer/ThaumicTinkerer#868]
so i recently started playing on a old server i've played before(mech&magic), and thanks to a certain player testing out the elemental fire on the dam server, the research is now banned.
said person din't even have the perdito elemental fire unlocked, so seem like a definite griever.

right now where trying to figure out how to get the ichor research working, while keeping all 6 elemental fire research stay banned to prevent future grieving.
we haven't had success of trying to disabled the crafting of the items, nor have a means of full proofing protection which can be bypassed relatively easy in larger modpacks.

i tried looking around but there is hardly any documentation for this, and the client configurations don't seem to have any options to look for a fix for above, so hence i am trying to ask here.

a second thing the owner of the server would like to know, where is the config node make ./iskamiunlocked available to all player regardless of permission nodes, right now it seems only op people have access to it.
![2016-10-02_21 27 42](https://cloud.githubusercontent.com/assets/12812081/19023149/1ded0c7c-88e7-11e6-9d0f-cb120986f8f1.png)

**Comment by bookerthegeek** [comment]
So for the research, you can minetweaker the research away. Also disabling the fire in the configs will not have them be required for kami.

As for the permissions issue, that is in whichever permission plugin your using, and you just need to give it to all players.

**Comment by NalyKalZul** [comment]
thank you for the quick reply. 
the first option of minetweaker is very nice solution.

but for the second issue, got any idea what is the name of said permission node is , or where to look for it to access the command to be added to the permission plugin?
i don't have any background server access so just inquiring to get a solid answer through to the owner to help us fix this in a quick overhaul later tomorrow.

anyways i like to thank you for at least showing us a nice customized option we could apply to rework some other issue's held with ducktape.

**Comment by bookerthegeek** [comment]
First you need to know what protection plugin your server is using. 

Easier then that is to have your owner or an admin with back end access let me walk the through it over teamspeak.

[This is me](https://mineyourmind.net/forum/members/bookerthegeek.4105/)

**Comment by NalyKalZul** [comment]
do you use discord by any chance? my profile is NalyKalZul#3905 and the server invites are 30 minute expiration links only, https://discord.gg/5cy4w so if you could not get the link to work use my profile instead to join the server.

i will say that we still don't know how but randomly part of the kami research became suddenly unlocked today, the owner said he dint do anything yet.
both me and a other player that are still trying to figure it out, right now we shared the research progress a few times back and forth as we make progress with this highly random issue.

and i  have worked my was through the mod several of times to the point i know the requirement on the back of my hand, i never seen it act this way at all.
right now we do have partially kami research done after using a sharing tome back and forth, but we both have different things grayed out and others thing unlocked.
he unlocked the ichor upgraded helmet and i unlocked the strato boots, and where still missing leggings and chest in the grayed out area >.<
right now we still have randomly incomplete research for ttkami at best.
