### ISSUE TITLE
[1.7.10] NPE in ItemBloodSword onDamageTaken

### ISSUE THREAD

**Issue by Robijnvogel** [Thaumic-Tinkerer/ThaumicTinkerer#871]
See [here](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2552088?comment=113).
I wonder if the NPE on [this line](https://github.com/Thaumic-Tinkerer/ThaumicTinkerer/blob/1.7-final/src/main/java/thaumic/tinkerer/common/item/ItemBloodSword.java#L130) is caused by TT's ASM changes implied by the second line of this guy's stacktrace.

If not, it's most likely some other mod handling the LivingAttackEvent wrongly, no?

**Comment by Robijnvogel** [comment]
@nekosune are you not going to work on the MC 1.7.10 version anymore?

**Comment by nekosune** [comment]
I will be re-creating things in 1.12 I am afraid.

**Comment by Robijnvogel** [comment]
No problem. Looking forward to how Thaumic Tinkerer will turn out with Thaumcraft 6. :D
