### ISSUE TITLE
specific enchantments removed with thaumic tinkerer 3? (1.8.9)

### ISSUE THREAD

**Issue by weeqo789** [Thaumic-Tinkerer/ThaumicTinkerer#873]
i was playing FTB yesterday (Direwolf20 pack), and i found some cool enchantments, including vampirism, final strike, focused strike, etc. But when i installed thaumcraft 5 with thaumic tinkerer 3 for 1.8.9, those enchantments seems to be missing. the only enchantments i find that is NOT native to vanilla minecraft is damage, poison, confusion, infinite, haste and repair. did the developers remove them in later versions, or do i need something more to make those enchantments work?

**Comment by justicesays** [comment]
TT3 for TC5/ 1.8.9 only contains a small subset of the content from the TC4 version. None of those additional enchantments are currently implemented.
