### ISSUE TITLE
[TT3] 1.8.9 Bound jars cause TileEntity errors on client side in SMP , making world inaccessible

### ISSUE THREAD

**Issue by justicesays** [Thaumic-Tinkerer/ThaumicTinkerer#887]
Attempting to attach a jar seal to an empty warded jar causes all connected clients to crash, and crash again on reconnection, with the error:
java.lang.NullPointerException: Ticking block entity
	at com.nekokittygames.Thaumic.Tinkerer.common.data.BoundJarNetworkManager$.getAspect(BoundJarNetworkManager.scala:77)
	at com.nekokittygames.Thaumic.Tinkerer.common.tiles.TileBoundJar.func_73660_a(TileBoundJar.scala:27)
	at net.minecraft.world.World.func_72939_s(World.java:1718)
.....
This is in SMP only , bound jars/jar seals seem to work fine SSP/client side only

**Comment by justicesays** [comment]
I've done some analysis of the world save state when this bug occurs
My Jar has nbt data that indicates it is a member of the 
"FarawayEmotionalStarling" network, 
But my world/data/boundJar.dat file does not contain any networks, so I assume this is the result of a non-existent uuid being passed to the boundjarnetworkmanager from the TileEntity
Suggests it's an issue with the initial network setup rather than this specific jar display code.

**Comment by justicesays** [comment]
![boundjarnbt](https://user-images.githubusercontent.com/10358888/29006057-636820d4-7ae0-11e7-9857-c899d58b15bf.jpg)
![dodgyjarnbt](https://user-images.githubusercontent.com/10358888/29006059-6584f464-7ae0-11e7-8e0f-cc9dd2b32029.jpg)

**Comment by nekosune** [comment]
I am looking into this!

**Comment by nekosune** [comment]
Seems I may have made a bad assumption about how to store the data in multiplayer, this is being worked on
