### ISSUE TITLE
[TT3] 1.8.9 Jar bound network last essentia point doesnt update jar clones

### ISSUE THREAD

**Issue by justicesays** [Thaumic-Tinkerer/ThaumicTinkerer#888]
When the last point of essentia is removed from a bound jar, the copies of that jar fail to update to empty, leaving just one essentia point displaying. This is only a display bug, the jars are empty if they get a block update.
I have a fix for this, but putting in an issue so pull request is not out of the blue.

**Comment by nekosune** [comment]
I am working on a fix for this that is a bit more useful then making the jars update every tick, see the latest commit 906cb8e06c7e99d8ff3ac3808720e1c0b74f25ab

**Comment by justicesays** [comment]
This doesn't actually appear to be fixed, sorry to say, the same test set up I used before shows that the last essentia amount (either 1 with suction , or 8 with a phial)  is visually left in the jar clones until a block update.
SMP only as before.
