### ISSUE TITLE
Tome of Knowledge issues.

### ISSUE THREAD

**Issue by ruifung** [Thaumic-Tinkerer/ThaumicTinkerer#909]
Version: 1.12.2 5.0 ALPHA1.1

1. Craft a Tome of Knowledge
2. Bind it to yourself.
3. Use it.
4. All unlocked but unresearched researches are now complete.

In addition, a tome of knowledge previously bound to someone, when you use it again, it does not seem to grant any additional researches that they've done since they bound it. While this is not an issue, there does not appear to be a way to unbind a tome of knowledge.

**Comment by nekosune** [comment]
Fixed this for the most part, This is mostly now a record of knowledge, not a link, I will rewrite the research to reflect this. But now you can shift click to unbind the Tome. And also only complete research is written into it now.
