### ISSUE TITLE
Not completing after clicking 

### ISSUE THREAD

**Issue by TiffanyDoctorWho** [Thaumic-Tinkerer/ThaumicTinkerer#921]
So after I click to complete the research with the appropriate item. It will not complete it at all even within a few minutes.

**Comment by gdarai** [comment]
If this is the same thing - Confirming on 1.12 - transvector interface
Says it requires workbench and that I did it.
It allows to click the complete button
But after the clicking it just says "Completing..." which is never finished.

**Comment by minakitty** [comment]
FWIW, still exists an alpha 1.4.2
