### ISSUE TITLE
server crash on 5.0 ALPHA1.4.1

### ISSUE THREAD

**Issue by DEViANCEVxXXxM** [Thaumic-Tinkerer/ThaumicTinkerer#925]
`---- Minecraft Crash Report ----
// I blame nekosune, author of Thaumic Tinkerer.

Time: 2018-08-02 00:11:26 UZT
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Thaumic Tinkerer (thaumictinkerer)
Caused by: java.lang.NoClassDefFoundError: org/lwjgl/util/vector/Matrix2f
    at com.nekokittygames.thaumictinkerer.common.multiblocks.MultiblockManager.initMultiblocks(MultiblockManager.java:48)
    at com.nekokittygames.thaumictinkerer.ThaumicTinkerer.init(ThaumicTinkerer.java:59)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627)
    at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744)
    at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108)
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:337)
    at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:219)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.lwjgl.util.vector.Matrix2f
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 37 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_181, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1169414592 bytes (1115 MB) / 1883242496 bytes (1796 MB) up to 3262644224 bytes (3111 MB)
  JVM Flags: 2 total; -Xms1024M -Xmx3500M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.4.2745 66 mods loaded, 66 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                   | Version                      | Source                                  | Signature                                |
       |:----- |:-------------------- |:---------------------------- |:--------------------------------------- |:---------------------------------------- |
       | UCHI  | minecraft            | 1.12.2                       | minecraft.jar                           | None                                     |
       | UCHI  | mcp                  | 9.42                         | minecraft.jar                           | None                                     |
       | UCHI  | FML                  | 8.0.99.99                    | forge-1.12.2-14.23.4.2745-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCHI  | forge                | 14.23.4.2745                 | forge-1.12.2-14.23.4.2745-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCHI  | lagremoval           | 1.0                          | (server) Clear Lag-1.0.jar              | None                                     |
       | UCHI  | clumps               | 3.1.1                        | (server) Clumps 3.1.1.jar               | None                                     |
       | UCHI  | fastleafdecay        | v14                          | (server) Fast Leaf Decay v14.jar        | None                                     |
       | UCHI  | helpfixer            | 1.12.1-1.5.18                | (server) Help Fixer 1.5.18.jar          | None                                     |
       | UCHI  | login_shield         | 1.12.2-3-g7c6e7ac            | (server) Login Shield 3-g7c6e7ac.jar    | None                                     |
       | UCHI  | morpheus             | 1.12-3.3.2                   | (server) Morpheus 3.3.2.jar             | None                                     |
       | UCHI  | unloader             | 1.2.0                        | (server) Unloader 1.2.0.jar             | None                                     |
       | UCHI  | akashictome          | 1.2-10                       | Akashic Tome 1.2-10.jar                 | None                                     |
       | UCHI  | baubles              | 1.5.2                        | Baubles 1.5.2.jar                       | None                                     |
       | UCHI  | astralsorcery        | 1.9.4                        | Astral Sorcery 1.9.4.jar                | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
       | UCHI  | morphtool            | 1.2-16                       | Morph o Tool 1.2-16.jar                 | None                                     |
       | UCHI  | mantle               | 1.12-1.3.2.24                | Mantle 1.3.2.24.jar                     | None                                     |
       | UCHI  | thaumcraft           | 6.1.BETA19                   | Thaumcraft 6.1.BETA19.jar               | None                                     |
       | UCHI  | tconstruct           | 1.12.2-2.10.1.87             | Tinker's Construct 2.10.1.87.jar        | None                                     |
       | UCHI  | betterwithmods       | ${version}                   | Better With Mods 2.3.4.jar              | None                                     |
       | UCHI  | quark                | r1.4-125                     | Quark r1.4-125.jar                      | None                                     |
       | UCHI  | autoreglib           | 1.3-18                       | AutoRegLib 1.3-18.jar                   | None                                     |
       | UCHI  | bhc                  | 1.1.1                        | Baubley Heart 1.1.1.jar                 | 7b14aaee2dd17b12a140baecab28948fff3a263f |
       | UCHI  | bdlib                | 1.14.3.12                    | Bdlib 1.14.3.12.jar                     | None                                     |
       | UCHI  | biomesoplenty        | 7.0.1.2398                   | Biomes O Plenty 7.0.1.2398.jar          | None                                     |
       | UCHI  | botania              | r1.10-354                    | Botania r1.10-354.jar                   | None                                     |
       | UCHI  | chameleon            | 1.12-4.1.3                   | Chameleon 4.1.3.jar                     | None                                     |
       | UCHI  | codechickenlib       | 3.2.1.349                    | Code Chicken Lib 3.2.1.349.jar          | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCHI  | cucumber             | 1.1.0                        | Cucumber 1.1.0.jar                      | None                                     |
       | UCHI  | enderstorage         | 2.4.5.135                    | Ender Storage 2.4.5.135.jar             | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCHI  | fastfurnace          | 1.0.0                        | Fast Furnace 1.0.0.jar                  | None                                     |
       | UCHI  | fastbench            | 1.5.1                        | Fast Workbench 1.5.1.jar                | None                                     |
       | UCHI  | foamfix              | 0.9.9.1-1.12.2               | Foam Fix 0.9.9.1 law.jar                | None                                     |
       | UCHI  | guideapi             | 1.12-2.1.7-62                | Guide API 2.1.7-62.jar                  | None                                     |
       | UCHI  | hammercore           | 2.0.1.2                      | Hammer Core 2.0.1.2.jar                 | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | UCHI  | instantunify         | 1.1.2                        | Instant Unify 1.1.2.jar                 | None                                     |
       | UCHI  | inventorytweaks      | 1.64-dev+release.110.b4fac73 | Inventory Tweaks 1.64-dev.jar           | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | UCHI  | ironbackpacks        | 1.12.2-3.0.8-12              | Iron Backpacks 3.0.8-12.jar             | None                                     |
       | UCHI  | ironchest            | 1.12.2-7.0.46.831            | Iron Chest 7.0.46.831.jar               | None                                     |
       | UCHI  | mysticalagriculture  | 1.6.12                       | Mystical agriculture 1.6.12.jar         | None                                     |
       | UCHI  | mysticalagradditions | 1.2.8                        | Mystical agradditions 1.2.8.jar         | None                                     |
       | UCHI  | jaopcaagriculture    | 1.12.2-1.2.1.13              | JAOPCA Agriculture 1.2.1.13.jar         | None                                     |
       | UCHI  | jaopca               | 1.12.2-2.2.8.90              | JAOPCA 2.2.8.90.jar                     | None                                     |
       | UCHI  | oredictinit          | 1.12.2-2.2.1.68              | JAOPCA 2.2.8.90.jar                     | None                                     |
       | UCHI  | jaopcaadditions      | 1.12.2-2.2.1.9               | JAOPCA Additions 2.2.1.9.jar            | None                                     |
       | UCHI  | jeid                 | 1.0.1-16                     | Just Enough IDs 1.0.1-16.jar            | None                                     |
       | UCHI  | lex                  | 1.0.4                        | LibEx 1.0.4.jar                         | None                                     |
       | UCHI  | mcmultipart          | 2.5.1                        | MC MultiPart 2.5.1.jar                  | None                                     |
       | UCHI  | mercurius            | 1.0.6                        | Mercurius 1.12.2.jar                    | None                                     |
       | UCHI  | nex                  | 2.0.4                        | NetherEx 2.0.4.jar                      | None                                     |
       | UCHI  | harvestcraft         | 1.12.2u                      | Pam's HarvestCraft 1.12.2u.jar          | None                                     |
       | UCHI  | plustic              | 6.5.2.0                      | Plustic 6.5.2.0.jar                     | None                                     |
       | UCHI  | primal               | 0.6.67                       | Primal Core 0.6.67.jar                  | 67a0e286dc0d4b502f3c92ac20b953517b52d0a9 |
       | UCHI  | roots                | 0.104                        | Roots 2-0.104.jar                       | None                                     |
       | UCHI  | sereneseasons        | 1.2.5                        | Serene Seasons 1.2.5.jar                | None                                     |
       | UCHI  | servertabinfo        | 1.2.1                        | Server Tab Info 1.2.1.jar               | None                                     |
       | UCHI  | sonarcore            | 5.0.15                       | Sonar Core 5.0.15-13.jar                | None                                     |
       | UCHI  | spartanshields       | 1.4.1                        | Spartan Shields 1.4.1.jar               | None                                     |
       | UCHI  | storagedrawers       | 1.12-5.3.5                   | Storage Drawers 5.3.7.jar               | None                                     |
       | UCHI  | storagedrawersextra  | @VERSION@                    | Storage Drawers Extras 3.1.0.jar        | None                                     |
       | UCHI  | taiga                | 1.3.2                        | Taiga 1.3.2.jar                         | None                                     |
       | UCHI  | thaumadditions       | 3r                           | Thaumic Additions 3r.jar                | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | UCHEE | thaumictinkerer      | 1.12.2-5.0-a99254a           | Thaumic Tinkerer 5.0-a99254a.jar        | None                                     |
       | UCH   | vanillafix           | 1.0.9-97                     | Vanilla Fix 1.0.9-97.jar                | None                                     |
       | UCH   | wanionlib            | 1.12.2-1.5                   | Wanion Lib 1.5.jar                      | None                                     |
       | UCH   | zerocore             | 1.12-0.1.2.2                 | Zero Core 0.1.2.2.jar                   | None                                     |
       | UCH   | wrapup               | 1.12-1.1.3                   | Wrap Up 1.1.3.jar                       | None                                     |
  Loaded coremods (and transformers): SSLoadingPlugin (Serene Seasons 1.2.5.jar)
                                        sereneseasons.asm.transformer.EntityRendererTransformer
                                        sereneseasons.asm.transformer.WorldTransformer
                                      Inventory Tweaks Coremod (Inventory Tweaks 1.64-dev.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      JEIDLoadingPlugin (Just Enough IDs 1.0.1-16.jar)
                                        
                                      VanillaFixLoadingPlugin (Vanilla Fix 1.0.9-97.jar)
                                        
                                      AstralCore (Astral Sorcery 1.9.4.jar)
                                        
                                      HCASM (Hammer Core 2.0.1.2.jar)
                                        com.zeitheron.hammercore.asm.HammerCoreTransformer
                                      LoadingPlugin (Quark r1.4-125.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      LoadingPlugin (Resource Loader 1.5.3.jar)
                                        lumien.resourceloader.asm.ClassTransformer
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
  Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
                           OreDictionary Info: Registered 2909 names; 4088 stacks.
                           Configuration Info: IyBDb25maWd1cmF0aW9uIGZpbGUNCg0KY2xpZW50IHsNCiAgICAjIFNob3VsZCBIYW1tZXIgQ29yZSByZXBsYWNlIGVuY2hhbnRtZW50IGdsaW50IGNvbG9yIHdpdGggbW9yZSBtYXRjaGluZyBjb2xvcnMgZm9yIHNvbWUgdmFuaWxsYSBpdGVtcz8gW2RlZmF1bHQ6IHRydWVdDQogICAgQjoiQ3VzdG9tIEVuY2hhbnRtZW50IENvbG9ycyBmb3IgVmFuaWxsYSBJdGVtcyI9dHJ1ZQ0KDQogICAgIyBTaG91bGQgSGFtbWVyIENvcmUgcG9ydGZvcndhcmQgeW91ciBsb2NhbCB3b3JsZCB3aGVuIHlvdSBzaGFyZSB3aXRoIGl0IHRvIExBTj8NCiAgICAjIFRoaXMgZmVhdHVyZSBkb2Vzbid0IHdvcmsgb24gYWxsIGNsaWVudHMsIHlvdSBhcmUgZ29pbmcgdG8gZ2V0IGEgbWVzc2FnZSBpbiBjaGF0IGlmIGl0IHdhcyBzdWNjZXNzZnVsL3Vuc3VjY2Vzc2Z1bCBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJMQU4gVVBuUCI9dHJ1ZQ0KDQogICAgIyBSZXBsYWNlIHZhbmlsbGEgZnVybmFjZSBhbmQgYnJld2luZyBzdGFuZCBwcm9ncmVzcyBiYXJzIHRvIHVzZSBzbW9vdGggcmVuZGVyaW5nPyBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJTbW9vdGggVmFuaWxsYSBHdWlzIj10cnVlDQp9DQoNCg0KaXdyZW5jaCB7DQogICAgIyBXaGF0IGlzIHRoZSBjb2xvciB3aGVuIHRoZSBob3ZlcmVkIGJsb2NrIGlzIHdyZW5jaGFibGU/IChjb2xvciBlbmNvZGVkIGluIGhleCBmb3JtIHN1Y2ggYXMgUlJHR0JCKQ0KICAgIFM6R3JlZW49MjJGRjIyDQoNCiAgICAjIFdoYXQgaXMgdGhlIGNvbG9yIHdoZW4gdGhlIGhvdmVyZWQgYmxvY2sgaXMgTk9UIHdyZW5jaGFibGU/IChjb2xvciBlbmNvZGVkIGluIGhleCBmb3JtIHN1Y2ggYXMgUlJHR0JCKQ0KICAgIFM6UmVkPUZGMjIyMg0KfQ0KDQoNCiJ2YW5pbGxhIGltcHJvdmVtZW50cyIgew0KICAgICMgU2hvdWxkIEhhbW1lciBDb3JlIGZvcmNlLXNwYXduIEVuZGVyIERyYWdvbiBFZ2cgb24gRW5kZXIgRHJhZ29uIGRlYXRoPyBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJBbHdheXMgU3Bhd24gRHJhZ29uIEVnZyI9dHJ1ZQ0KfQ0KDQoNCg==
                           Pastebin Connection: Okay.
  List of loaded APIs: * Baubles|API (1.4.0.2) from Baubles 1.5.2.jar
                       * betteradvancements|API (0.0.8.50) from Better Advancements 0.0.8.50.jar
                       * betterwithmodsAPI (${version}) from Better With Mods 2.3.4.jar
                       * BetterWithModsAPI (Beta 0.6) from Quark r1.4-125.jar
                       * BotaniaAPI (79) from Akashic Tome 1.2-10.jar
                       * Guide-API|API (2.0.0) from Guide API 2.1.7-62.jar
                       * QuarkAPI (2) from Quark r1.4-125.jar
                       * sonarapi (1.0.1) from Sonar Core 5.0.15-13.jar
                       * StorageDrawersAPI (2.1.0) from Storage Drawers 5.3.7.jar
                       * StorageDrawersAPI|event (2.1.0) from Storage Drawers 5.3.7.jar
                       * StorageDrawersAPI|registry (2.1.0) from Storage Drawers 5.3.7.jar
                       * StorageDrawersAPI|render (2.1.0) from Storage Drawers 5.3.7.jar
                       * StorageDrawersAPI|storage (2.1.0) from Storage Drawers 5.3.7.jar
                       * StorageDrawersAPI|storage-attribute (2.1.0) from Storage Drawers 5.3.7.jar
                       * Thaumcraft|API (6.0.2) from Thaumcraft 6.1.BETA19.jar
                       * zerocore|API|multiblock (1.10.2-0.0.2) from Zero Core 0.1.2.2.jar
                       * zerocore|API|multiblock|rectangular (1.10.2-0.0.2) from Zero Core 0.1.2.2.jar
                       * zerocore|API|multiblock|tier (1.10.2-0.0.2) from Zero Core 0.1.2.2.jar
                       * zerocore|API|multiblock|validation (1.10.2-0.0.2) from Zero Core 0.1.2.2.jar
  Suspected Mods: Thaumic Tinkerer (thaumictinkerer)
  Profiler Position: N/A (disabled)
  Is Modded: Definitely; Server brand changed to 'fml,forge'
  Type: Dedicated Server (map_server.txt)
`

**Comment by nekosune** [comment]
I totally forgot about that, I will fix
