### ISSUE TITLE
Game Crash on startup

### ISSUE THREAD

**Issue by demfels** [Thaumic-Tinkerer/ThaumicTinkerer#926]
I updated from 1.3 to 1.4 and then tried 1.4.1.  Appears to be a total crash, see pastebin.  Spending a bit more time on this troubleshooting, but thinking I might just have to remove it from my modpack.

https://pastebin.com/idXTDaXF

**Comment by nekosune** [comment]
Sorry about that, I had some minor trouble finding which would work in server vs client, that should be fixed in 1.4.2

**Comment by demfels** [comment]
Awesome, updating now and testing.  Thanks man.
