### ISSUE TITLE
Essentia Funnel issues

### ISSUE THREAD

**Issue by angelnc1989** [Thaumic-Tinkerer/ThaumicTinkerer#929]
Minecraft 1.12.2
Forge 14.23.4.27.56
Thaumcraft 6.1 BETA 24
Thaumic Tinkerer 2.5.0-353c71c

1. Breaking a Essentia Funnel with a Jar placed in it only drops the Essentia Funnel, not the Jar. (Only tested with Warded Jar)
2. Removing an empty Jar with rightclicking the Essentia Funnel returns an empty Jar with NBT tags, so it doesn't stack with Jars in your inventory. (<thaumcraft:jar_normal>.withTag({Aspects: []}))
3. The Essentia Funnel sometimes doesn't fill Jars with a capacity over 250. I was able to transfer 2 Warded Jars of Metallum into a Void Fortified Jar (Thaumic Additions: Reconstructed). When I tried to do the same with Vitium Jars it stopped filling at 250.
![2018-09-09_12 33 40](https://user-images.githubusercontent.com/5382585/45263613-a5526000-b42c-11e8-9a3d-93b14a74e92f.png)

**Comment by nekosune** [comment]
Will work on these tonight

**Comment by nekosune** [comment]
Please however in the future do one bug per issue, this allows me to keep better track of bugs and when fixed, and reduces delay in fixes when one fix is more complicated then the other

**Comment by nekosune** [comment]
3 will be one of the difficult ones, as there does not seem to be away to check the capacity of a jar anymore

**Comment by nekosune** [comment]
Sadly the whole 250 issue, won't be easily fixed, I have added an API that other mods may use, if they wish, to let the funnel add more then 250 to their jars.
