### ISSUE TITLE
[1.12.2] Osmotic Enchanter/Multiblock Guide Bugs/Feedback

### ISSUE THREAD

**Issue by TechnoMysterio** [Thaumic-Tinkerer/ThaumicTinkerer#949]
Summary of discoveries made when testing the Osmotic Enchanter and the Multiblock Guide. I understand it's still in development, but here's what I've found anyway:

Osmotic Enchanter:
1. Can't seem to form the OE Multiblock when built around the outline the guide created. Tried Salis Mundus and some other things, but I couldn't get the thing to form.
2. Osmotic Enchanter didn't drop the tool it was holding when I broke it. This was in creative mode.
3. Stored item in OE rendered in the world above the OE was coloured entirely black.
4. Had a crash when I tried to put a non-enchantable object in the OE. Crash log: https://pastebin.com/sFxB89wE
5. Do all OE Enchantments require Mortuus and Perditio Essentia Crystals? That's what I noticed when I saw what was needed for some enchantments. This might be on me and my poor memory though.

Multiblock Guide:
1. Outline blocks spawned when right-clicking OE didn't disappear when OE was broken.
2. I can break multiblock guide blocks with a single punch in survival. They should probably be fully intangible, so you can punch through them. They should probably disappear when the central block is broken or after some time has passed.

**Comment by nekosune** [comment]
> Can't seem to form the OE Multiblock when built around the outline the guide created. Tried Salis Mundus and some other things, but I couldn't get the thing to form.
The Caster is used to form the multi-block, you are right in that sdalis may make sense also, will see which
