### ISSUE TITLE
[1.12.2] Transvector/Dissimulation Block Bugs/Feedback

### ISSUE THREAD

**Issue by TechnoMysterio** [Thaumic-Tinkerer/ThaumicTinkerer#950]
Testing of the Transvector Interface, Transvector Dislocator and the Dissimulation Block:

Dissimulation Block:
1. When placed down, disguised as another block and then broken in creative mode, some kind of ghost block is left behind. When you try to walk into the space where the block was, you jitter and can't walk through it. The block will reappear in two ways. Firstly, relog. Secondly, if you right-click the 'empty' space with another block, the block will reappear. This happens with any disguiseable block, not just the dissimulation block. This doesn't happen in survival, where the block breaks normally and drops the block it was disguised as.
2. Is there a way to clear a block's disguise without breaking it?

Transvector Interface:
1. It's recipe doesn't use a dissimulation block despite the fact that it can be disguised. There's also another problem with the recipe that it shares with other recipes, so I'll cover that in another issue later on.
2. I couldn't get it to work with pipes from Embers Rekindled, neither item nor fluid pipes. I also tried linking it to a Fluid Vessel from embers, and when I used a water bucket on the interface it just poured water on top of it instead of storing the water in the vessel.
3. It would be good to be able to see where a Transvector Interface is linked to just by holding the Linking device in your hand, perhaps just via a faint line leading out of the Interface and into the linked block. This also applies to the Transvector Dislocator.

Transvector Dislocator:
1. This device can move bedrock. I assume it also moves other unbreakable blocks. Might wanna change that. A further note: might this also move blocks in protected chunks or areas, if such a mod were installed?
2. The texture/model for the Dislocator doesn't make it very clear what side it'll swap blocks to/from. I did notice that it was the animated side that it swaps to, but this isn't immediately apparent.

**Comment by nekosune** [comment]
>When placed down, disguised as another block and then broken in creative mode, some kind of ghost block is left behind. When you try to walk into the space where the block was, you jitter and can't walk through it. The block will reappear in two ways. Firstly, relog. Secondly, if you right-click the 'empty' space with another block, the block will reappear. This happens with any disguiseable block, not just the dissimulation block

Can not reproduce

**Comment by TechnoMysterio** [comment]
I don't know how that issue might have been affected after the various changes you made, so I'll have to test it again after the mod is updated. As I recall though, it only occured in creative, so I don't think it's too much to worry about for the meantime.

**Comment by nekosune** [comment]
Was able to reproduce using a seperate client/server setup

**Comment by nekosune** [comment]
you can already see where the Transvector interface is pointed by right clicking it with the linker again to select it, shift right clicking into air to clear once seen
