### ISSUE TITLE
[1.12.2] Osmotic Enchanter Multiblock Doesn't Preserve Nitor Colours

### ISSUE THREAD

**Issue by TechnoMysterio** [Thaumic-Tinkerer/ThaumicTinkerer#955]
When the Osmotic Enchanter Multiblock is formed, any coloured Nitor used in its construction turns to the standard yellow.

**Comment by nekosune** [comment]
Unfortunatly, to fix this would involve more modification of the multiblock system, and converting the enchantment pillars to tile entities for no other reason. The research entry will state that forming the multiblock drains the nitor of most of its energy, causing the color loss.
