### ISSUE TITLE
[1.12.2] Telekinesis Aspect/Lore Suggestions

### ISSUE THREAD

**Issue by TechnoMysterio** [Thaumic-Tinkerer/ThaumicTinkerer#957]
Some suggestions for the Telekinesis effect and its lore.

Firstly, it might be better to have its aspect be Praecantatio (magic), with the lore reason being that it sends out energy in the Aural Field to move objects instead of moving air. This makes it more magicy, and also explains why it works in areas that might be limited in air (deep underground, in space, etc).

Secondly, with the aspect changed to Praecantatio, it would be good to set the effect's colour to be purple, pink, magenta or some mix of the three (since the aspect is of a similar colour). The colour change would help to make it stand out, and its also in line with the colour of the Focus in earlier Tinkerer versions.

Oh, and I put these two things in the same issue since they're very closely related and can probably done together.

**Comment by nekosune** [comment]
Please note this will not change  the colour of already created focii, you will need to recreate a focus to see the new colour
