### ISSUE TITLE
[1.12.2] Osmotic Enchanter Structure Oddities

### ISSUE THREAD

**Issue by TechnoMysterio** [Thaumic-Tinkerer/ThaumicTinkerer#971]
I noticed something strange about the block arrangement of the Osmotic Enchanter, namely in the base layer. I'll explain this via the magic of pictures, since me cannot word no good...

The multiblock diagram in the book shows the structure as such:
![2019-06-28_14 11 59](https://user-images.githubusercontent.com/5113920/60344667-f37e2300-99ae-11e9-8ca1-0c70ad5f0d8d.png)

Firstly, the Osmotic Enchanter itself isn't included in the block tally. However, the main problem I wish to address can be seen in the way the base is meant to be laid out, like so:
![2019-06-28_14 13 22](https://user-images.githubusercontent.com/5113920/60344786-41932680-99af-11e9-8959-46a391ca7066.png)

For some reason, the ring of Arcane Bricks around the central quartz blocks isn't consistent at the east and west sides. It would look better if the base had to be laid out like so:
![2019-06-28_14 13 35](https://user-images.githubusercontent.com/5113920/60344801-4c4dbb80-99af-11e9-9967-08e699d0960f.png)

**Comment by nekosune** [comment]
That was the original layout, I just missed part when typing it in
