### ISSUE TITLE
[1.12.2] Osmotic Enchanter Debug Messages

### ISSUE THREAD

**Issue by TechnoMysterio** [Thaumic-Tinkerer/ThaumicTinkerer#977]
When I click on OE pillars or an Osmotic Enchanter block without the multiblock built, I get what appear to be debug messages appearing, like 'Direction - 4' or 'InComplete'. The pillar ones should probably be removed once they serve no purpose, but the Osmotic Enchanter message may serve a useful purpose by colouring it the usual purple that Thaumcraft on screen messages have (like the ones for Warp effects) and changing the message to something like 'You need the Mystical Construct assembled in order to use the Osmotic Enchanter!'

**Comment by nekosune** [comment]
![image](https://user-images.githubusercontent.com/690546/60722207-174de580-9f28-11e9-8f98-0104fc21cf4b.png)
