### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by lolka13372** [Thaumic-Tinkerer/ThaumicTinkerer#985]
Log:
* What went wrong:
Execution failed for task ':applyBinaryPatches'.
> There is a binary discrepency between the expected input class net.minecraft.client.renderer.entity.layers.LayerHeldItem (ccc) and the actual class. Checksum on disk is da0f6687, in patch 5f7c661a. Things are probably about to go very wrong. Did you put something into the jar file?
Could not resolve: net.minecraftforge:forgeBin:1.12.2-14.23.5.2838

**Comment by nekosune** [comment]
Hi there. This seems to be an error with your setup, This mod does not even have any access transformers
