### ISSUE TITLE
[1.12.2] EvilCraft Enchantment Names Missing

### ISSUE THREAD

**Issue by TechnoMysterio** [Thaumic-Tinkerer/ThaumicTinkerer#997]
Bit of a strange one, while enchantments from other mods are all localised correctly (ableit lacking icons), ones from EvilCraft are not. Dunno if this is EvilCraft's fault or not, but if it is then I'll close this issue and report it on the EvilCraft github instead.

![2019-11-10_20 49 16](https://user-images.githubusercontent.com/5113920/68550552-b1a0c700-03fb-11ea-9321-119314a10df7.png)

**Comment by nekosune** [comment]
The lack of icons is fixable with a resource pack, or by other mod authors, the localisation issue is ... weird, I will have to investigate further

**Comment by nekosune** [comment]
Fixed this issue, and improved existing enchantment translation! 
![image](https://user-images.githubusercontent.com/690546/72099425-7dbd2180-3318-11ea-9062-9047e411bf23.png)
