### ISSUE TITLE
Tome of sharing knowledge will not function. 

### ISSUE THREAD

**Issue by JustLiam040** [Thaumic-Tinkerer/ThaumicTinkerer#999]
Minecraft version: 1.12.2
Modpack: Enigmatica 2

Issue: Upon clicking the Tome of knowledge I get the standard message, however when throw the time to my friends they do not get my knowledge. I've tried clearing it and then resharing it, restarting the server etc, nothing seems to work.

I'm unsure whether this is an issue on my part, or simply an error with the time?

**Comment by nekosune** [comment]
Tested, can not Reproduce
